/**
 * EVLab Sewerage & Wastewater Treatment Plant (STP) Engineering Platform
 * Master STP Parameter Registry & Automated Parameter Audit Engine
 * @license Apache-2.0
 */

import { ParameterDefinition, ParameterAuditReport } from '../types/stp';

export const MASTER_PARAMETER_CATALOG: Record<string, ParameterDefinition> = {
  // ==========================================================================
  // DEMOGRAPHICS & POPULATION
  // ==========================================================================
  'STP.DEMO.P_PRES': {
    id: 'STP.DEMO.P_PRES',
    category: 'DEMOGRAPHICS',
    subcategory: 'POPULATION',
    name: 'Present Served Population',
    symbol: 'P_pres',
    unit: 'capita',
    datatype: 'NUMBER',
    min: 100,
    max: 10000000,
    defaultValue: 50000,
    designValue: 50000,
    source: 'Census / Master Plan',
    standardReference: 'CPHEEO Manual / Metcalf & Eddy Ch. 2',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-DEMO-001'],
    dependencies: [],
    formulaDependencies: ['CALC-DEMO-DESIGN_POP'],
    reportSections: ['02 Design Basis', '03 Population & Flow'],
    boqDependencies: [],
    bimProperties: ['Pset_StpGeneral.PresentPopulation'],
    scadaTags: [],
  },

  'STP.DEMO.GR_PCT': {
    id: 'STP.DEMO.GR_PCT',
    category: 'DEMOGRAPHICS',
    subcategory: 'POPULATION',
    name: 'Annual Population Growth Rate',
    symbol: 'r_g',
    unit: '%',
    datatype: 'NUMBER',
    min: 0.1,
    max: 6.0,
    defaultValue: 2.5,
    designValue: 2.5,
    source: 'Urban Planning Data',
    standardReference: 'Geometric Increase Method',
    isRequired: true,
    isAssumed: true,
    validationRules: ['VAL-DEMO-002'],
    dependencies: ['STP.DEMO.P_PRES'],
    formulaDependencies: ['CALC-DEMO-DESIGN_POP'],
    reportSections: ['02 Design Basis'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.DEMO.HORIZON': {
    id: 'STP.DEMO.HORIZON',
    category: 'DEMOGRAPHICS',
    subcategory: 'DESIGN_PERIOD',
    name: 'Design Horizon Period',
    symbol: 'N_des',
    unit: 'day', // stored internally, UI converts to years (30 yrs)
    datatype: 'NUMBER',
    min: 10,
    max: 50,
    defaultValue: 30,
    designValue: 30,
    source: 'Engineering Standards',
    standardReference: 'AWWA / CPHEEO 30-Year Standard',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-DEMO-003'],
    dependencies: [],
    formulaDependencies: ['CALC-DEMO-DESIGN_POP', 'CALC-COST-LCCA'],
    reportSections: ['02 Design Basis', '35 LCCA'],
    boqDependencies: [],
    bimProperties: ['Pset_StpGeneral.DesignHorizonYears'],
    scadaTags: [],
  },

  'STP.DEMO.P_DES': {
    id: 'STP.DEMO.P_DES',
    category: 'DEMOGRAPHICS',
    subcategory: 'POPULATION',
    name: 'Design Population (Target Horizon)',
    symbol: 'P_des',
    unit: 'capita',
    datatype: 'NUMBER',
    min: 100,
    max: 20000000,
    defaultValue: 104877,
    designValue: 104877,
    source: 'Calculated from Geometric Growth',
    standardReference: 'Metcalf & Eddy Eq. 2-1',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-DEMO-004'],
    dependencies: ['STP.DEMO.P_PRES', 'STP.DEMO.GR_PCT', 'STP.DEMO.HORIZON'],
    formulaDependencies: ['CALC-FLOW-ADWF', 'CALC-FLOW-BOD_LOAD'],
    reportSections: ['03 Population & Flow'],
    boqDependencies: ['BOQ-CIV-001'],
    bimProperties: ['Pset_StpGeneral.DesignPopulation'],
    scadaTags: [],
  },

  // ==========================================================================
  // WATER DEMAND & WASTEWATER GENERATION
  // ==========================================================================
  'STP.FLOW.PER_CAP_DEMAND': {
    id: 'STP.FLOW.PER_CAP_DEMAND',
    category: 'FLOW_HYDRAULICS',
    subcategory: 'DEMAND',
    name: 'Per Capita Domestic Water Demand',
    symbol: 'q_cap',
    unit: 'L/day',
    datatype: 'NUMBER',
    min: 50,
    max: 400,
    defaultValue: 135,
    designValue: 135,
    source: 'Municipal Water Supply Standard',
    standardReference: 'WHO / CPHEEO 135 LPD Standard',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-FLOW-001'],
    dependencies: [],
    formulaDependencies: ['CALC-FLOW-DOMESTIC'],
    reportSections: ['03 Population & Flow'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.FLOW.RETURN_FACTOR': {
    id: 'STP.FLOW.RETURN_FACTOR',
    category: 'FLOW_HYDRAULICS',
    subcategory: 'GENERATION',
    name: 'Sewerage Return Factor',
    symbol: 'C_ret',
    unit: '%',
    datatype: 'NUMBER',
    min: 0.60,
    max: 0.95,
    defaultValue: 0.80,
    designValue: 0.80,
    source: 'Sanitary Engineering Practice',
    standardReference: 'Metcalf & Eddy / CPHEEO Table 3.1',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-FLOW-002'],
    dependencies: [],
    formulaDependencies: ['CALC-FLOW-ADWF'],
    reportSections: ['03 Population & Flow'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.FLOW.COMMERCIAL': {
    id: 'STP.FLOW.COMMERCIAL',
    category: 'FLOW_HYDRAULICS',
    subcategory: 'DEMAND',
    name: 'Commercial Wastewater Flow Contribution',
    symbol: 'Q_comm',
    unit: 'm3/day',
    datatype: 'NUMBER',
    min: 0,
    max: 50000,
    defaultValue: 500,
    designValue: 500,
    source: 'Commercial District Survey',
    standardReference: 'Project Specific Survey',
    isRequired: false,
    isAssumed: true,
    validationRules: [],
    dependencies: [],
    formulaDependencies: ['CALC-FLOW-ADWF'],
    reportSections: ['03 Population & Flow'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.FLOW.INDUSTRIAL': {
    id: 'STP.FLOW.INDUSTRIAL',
    category: 'FLOW_HYDRAULICS',
    subcategory: 'DEMAND',
    name: 'Industrial Wastewater Flow Contribution',
    symbol: 'Q_ind',
    unit: 'm3/day',
    datatype: 'NUMBER',
    min: 0,
    max: 100000,
    defaultValue: 1000,
    designValue: 1000,
    source: 'Industrial Zone Discharge Permits',
    standardReference: 'Local EPA Permits',
    isRequired: false,
    isAssumed: true,
    validationRules: ['VAL-FLOW-003'],
    dependencies: [],
    formulaDependencies: ['CALC-FLOW-ADWF', 'CALC-MASS-LOADINGS'],
    reportSections: ['03 Population & Flow', '04 Wastewater Characterization'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.FLOW.INFILTRATION': {
    id: 'STP.FLOW.INFILTRATION',
    category: 'FLOW_HYDRAULICS',
    subcategory: 'INFLOW_INFILTRATION',
    name: 'Groundwater Infiltration Allowance',
    symbol: 'Q_inf',
    unit: 'L/s',
    datatype: 'NUMBER',
    min: 0,
    max: 500,
    defaultValue: 15.0,
    designValue: 15.0,
    source: 'Sewer Network Hydrogeology',
    standardReference: 'WEF Manual of Practice No. 9',
    isRequired: true,
    isAssumed: true,
    validationRules: ['VAL-FLOW-004'],
    dependencies: [],
    formulaDependencies: ['CALC-FLOW-AWWF', 'CALC-FLOW-PWWF'],
    reportSections: ['03 Population & Flow', '05 Sewerage Network'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.FLOW.PEAK_FACTOR': {
    id: 'STP.FLOW.PEAK_FACTOR',
    category: 'FLOW_HYDRAULICS',
    subcategory: 'PEAKING',
    name: 'Hourly Peak Flow Factor',
    symbol: 'PF',
    unit: '%', // stored as multiplier
    datatype: 'NUMBER',
    min: 1.5,
    max: 4.5,
    defaultValue: 2.25,
    designValue: 2.25,
    source: 'Babbit / Harmon Formula',
    standardReference: 'Harmon Equation: PF = 1 + 14/(4 + sqrt(P_in_thousands))',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-FLOW-005'],
    dependencies: ['STP.DEMO.P_DES'],
    formulaDependencies: ['CALC-FLOW-PDWF', 'CALC-FLOW-PWWF'],
    reportSections: ['03 Population & Flow', '10 Hydraulic Design'],
    boqDependencies: [],
    bimProperties: ['Pset_StpHydraulic.PeakFactor'],
    scadaTags: [],
  },

  'STP.FLOW.ADWF': {
    id: 'STP.FLOW.ADWF',
    category: 'FLOW_HYDRAULICS',
    subcategory: 'FLOW_SUMMARY',
    name: 'Average Dry Weather Flow',
    symbol: 'ADWF',
    unit: 'm3/day',
    datatype: 'NUMBER',
    min: 10,
    max: 1000000,
    defaultValue: 12826,
    designValue: 12826,
    source: 'Calculated Design Basis',
    standardReference: 'Metcalf & Eddy Ch. 3',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-FLOW-006'],
    dependencies: ['STP.DEMO.P_DES', 'STP.FLOW.PER_CAP_DEMAND', 'STP.FLOW.RETURN_FACTOR', 'STP.FLOW.COMMERCIAL', 'STP.FLOW.INDUSTRIAL'],
    formulaDependencies: ['CALC-PROCESS-REACTOR_VOLUME', 'CALC-SLUDGE-PRODUCTION'],
    reportSections: ['01 Executive Summary', '03 Population & Flow', '09 Process Design'],
    boqDependencies: ['BOQ-MECH-001'],
    bimProperties: ['Pset_StpHydraulic.ADWF'],
    scadaTags: ['FIT_INLET_ADWF'],
  },

  'STP.FLOW.PWWF': {
    id: 'STP.FLOW.PWWF',
    category: 'FLOW_HYDRAULICS',
    subcategory: 'FLOW_SUMMARY',
    name: 'Peak Wet Weather Flow (Design Hydraulic Capacity)',
    symbol: 'PWWF',
    unit: 'm3/day',
    datatype: 'NUMBER',
    min: 20,
    max: 3000000,
    defaultValue: 30154,
    designValue: 30154,
    source: 'Calculated Hydraulic Peak',
    standardReference: 'Ten State Standards / WEF MOP 8',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-FLOW-007'],
    dependencies: ['STP.FLOW.ADWF', 'STP.FLOW.PEAK_FACTOR', 'STP.FLOW.INFILTRATION'],
    formulaDependencies: ['CALC-HYD-HGL', 'CALC-CLARIFIER-SOR', 'CALC-DISINFECTION-UV'],
    reportSections: ['01 Executive Summary', '03 Population & Flow', '10 Hydraulic Design'],
    boqDependencies: ['BOQ-HYD-001', 'BOQ-CIV-002'],
    bimProperties: ['Pset_StpHydraulic.PWWF', 'Pset_StpHydraulic.PeakFlowLps'],
    scadaTags: ['FIT_INLET_PWWF'],
  },

  // ==========================================================================
  // INFLUENT WATER QUALITY & POLLUTANT CHARACTERISTICS
  // ==========================================================================
  'STP.QUAL.BOD5': {
    id: 'STP.QUAL.BOD5',
    category: 'INFLUENT_QUALITY',
    subcategory: 'ORGANICS',
    name: 'Influent 5-Day Biochemical Oxygen Demand',
    symbol: 'BOD5',
    unit: 'mg/L',
    datatype: 'NUMBER',
    min: 50,
    max: 1200,
    defaultValue: 250,
    designValue: 250,
    source: 'Laboratory Analysis / Standard Domestic Range',
    standardReference: 'Standard Methods 5210 B',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-QUAL-001'],
    dependencies: [],
    formulaDependencies: ['CALC-BIO-OXYGEN_REQ', 'CALC-MASS-BOD_LOAD'],
    reportSections: ['04 Wastewater Characterization', '09 Process Design'],
    boqDependencies: [],
    bimProperties: ['Pset_StpProcess.InfluentBOD'],
    scadaTags: ['AI_BOD_INLET'],
  },

  'STP.QUAL.COD': {
    id: 'STP.QUAL.COD',
    category: 'INFLUENT_QUALITY',
    subcategory: 'ORGANICS',
    name: 'Influent Chemical Oxygen Demand',
    symbol: 'COD',
    unit: 'mg/L',
    datatype: 'NUMBER',
    min: 100,
    max: 2500,
    defaultValue: 450,
    designValue: 450,
    source: 'Laboratory Analysis',
    standardReference: 'Standard Methods 5220 C',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-QUAL-002'],
    dependencies: ['STP.QUAL.BOD5'],
    formulaDependencies: ['CALC-BIO-MASS_BALANCE'],
    reportSections: ['04 Wastewater Characterization'],
    boqDependencies: [],
    bimProperties: ['Pset_StpProcess.InfluentCOD'],
    scadaTags: ['AI_COD_INLET'],
  },

  'STP.QUAL.TSS': {
    id: 'STP.QUAL.TSS',
    category: 'INFLUENT_QUALITY',
    subcategory: 'SOLIDS',
    name: 'Influent Total Suspended Solids',
    symbol: 'TSS',
    unit: 'mg/L',
    datatype: 'NUMBER',
    min: 80,
    max: 1000,
    defaultValue: 280,
    designValue: 280,
    source: 'Laboratory Analysis',
    standardReference: 'Standard Methods 2540 D',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-QUAL-003'],
    dependencies: [],
    formulaDependencies: ['CALC-PRIMARY-SLUDGE', 'CALC-SECONDARY-SLUDGE'],
    reportSections: ['04 Wastewater Characterization', '18 Sludge Balance'],
    boqDependencies: ['BOQ-SLUDGE-001'],
    bimProperties: ['Pset_StpProcess.InfluentTSS'],
    scadaTags: ['AI_TSS_INLET'],
  },

  'STP.QUAL.TKN': {
    id: 'STP.QUAL.TKN',
    category: 'INFLUENT_QUALITY',
    subcategory: 'NUTRIENTS',
    name: 'Influent Total Kjeldahl Nitrogen',
    symbol: 'TKN',
    unit: 'mg/L',
    datatype: 'NUMBER',
    min: 15,
    max: 120,
    defaultValue: 45,
    designValue: 45,
    source: 'Laboratory Analysis',
    standardReference: 'Standard Methods 4500-Norg C',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-QUAL-004'],
    dependencies: [],
    formulaDependencies: ['CALC-BNR-NITRIFICATION_O2'],
    reportSections: ['04 Wastewater Characterization', '12 Nitrogen Removal'],
    boqDependencies: [],
    bimProperties: ['Pset_StpProcess.InfluentTKN'],
    scadaTags: ['AI_TKN_INLET'],
  },

  'STP.QUAL.NH3N': {
    id: 'STP.QUAL.NH3N',
    category: 'INFLUENT_QUALITY',
    subcategory: 'NUTRIENTS',
    name: 'Influent Ammonia Nitrogen',
    symbol: 'NH3-N',
    unit: 'mg/L',
    datatype: 'NUMBER',
    min: 10,
    max: 80,
    defaultValue: 30,
    designValue: 30,
    source: 'Laboratory Analysis',
    standardReference: 'Standard Methods 4500-NH3 C',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-QUAL-005'],
    dependencies: ['STP.QUAL.TKN'],
    formulaDependencies: ['CALC-BNR-NITRIFICATION_RATE'],
    reportSections: ['04 Wastewater Characterization'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: ['AI_NH4_INLET'],
  },

  'STP.QUAL.TP': {
    id: 'STP.QUAL.TP',
    category: 'INFLUENT_QUALITY',
    subcategory: 'NUTRIENTS',
    name: 'Influent Total Phosphorus',
    symbol: 'TP',
    unit: 'mg/L',
    datatype: 'NUMBER',
    min: 2,
    max: 25,
    defaultValue: 8.0,
    designValue: 8.0,
    source: 'Laboratory Analysis',
    standardReference: 'Standard Methods 4500-P E',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-QUAL-006'],
    dependencies: [],
    formulaDependencies: ['CALC-P-CHEMICAL_DOSE'],
    reportSections: ['04 Wastewater Characterization', '13 Phosphorus Removal'],
    boqDependencies: ['BOQ-CHEM-001'],
    bimProperties: ['Pset_StpProcess.InfluentTP'],
    scadaTags: ['AI_PO4_INLET'],
  },

  'STP.QUAL.TEMP': {
    id: 'STP.QUAL.TEMP',
    category: 'INFLUENT_QUALITY',
    subcategory: 'PHYSICAL',
    name: 'Minimum Design Wastewater Temperature',
    symbol: 'T_min',
    unit: '°C',
    datatype: 'NUMBER',
    min: 5,
    max: 40,
    defaultValue: 18.0,
    designValue: 18.0,
    source: 'Seasonal Meteorological Record',
    standardReference: 'Minimum Winter Temperature for Kinetic Rates',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-QUAL-007'],
    dependencies: [],
    formulaDependencies: ['CALC-BIO-KINETIC_TEMP_CORR', 'CALC-AERATION-KLA'],
    reportSections: ['02 Design Basis', '09 Process Design'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: ['TI_INLET_TEMP'],
  },

  // ==========================================================================
  // BIOLOGICAL PROCESS KINETICS
  // ==========================================================================
  'STP.BIO.MLSS': {
    id: 'STP.BIO.MLSS',
    category: 'BIOLOGICAL_TREATMENT',
    subcategory: 'KINETICS',
    name: 'Mixed Liquor Suspended Solids',
    symbol: 'MLSS',
    unit: 'mg/L',
    datatype: 'NUMBER',
    min: 1500,
    max: 12000,
    defaultValue: 3500,
    designValue: 3500,
    source: 'Process Design Standard',
    standardReference: 'Metcalf & Eddy Table 8-12',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-BIO-001'],
    dependencies: [],
    formulaDependencies: ['CALC-BIO-REACTOR_VOLUME', 'CALC-CLARIFIER-SLR'],
    reportSections: ['09 Process Design', '14 Secondary Clarification'],
    boqDependencies: ['BOQ-CIV-003'],
    bimProperties: ['Pset_StpProcess.MLSS'],
    scadaTags: ['AIT_AERATION_MLSS'],
  },

  'STP.BIO.SRT': {
    id: 'STP.BIO.SRT',
    category: 'BIOLOGICAL_TREATMENT',
    subcategory: 'KINETICS',
    name: 'Solids Retention Time (Sludge Age)',
    symbol: 'θ_c',
    unit: 'day',
    datatype: 'NUMBER',
    min: 3,
    max: 30,
    defaultValue: 12.0,
    designValue: 12.0,
    source: 'Nitrification Kinetics Design',
    standardReference: 'SRT = 1 / (mu_max_net)',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-BIO-002'],
    dependencies: ['STP.QUAL.TEMP'],
    formulaDependencies: ['CALC-BIO-WAS_RATE', 'CALC-BIO-SLUDGE_YIELD'],
    reportSections: ['09 Process Design'],
    boqDependencies: [],
    bimProperties: ['Pset_StpProcess.SRT'],
    scadaTags: [],
  },

  'STP.BIO.FM_RATIO': {
    id: 'STP.BIO.FM_RATIO',
    category: 'BIOLOGICAL_TREATMENT',
    subcategory: 'KINETICS',
    name: 'Food-to-Microorganism Ratio',
    symbol: 'F/M',
    unit: 'kg/day', // kg BOD / kg MLVSS / day
    datatype: 'NUMBER',
    min: 0.05,
    max: 0.60,
    defaultValue: 0.22,
    designValue: 0.22,
    source: 'Calculated Process Parameter',
    standardReference: 'F/M = (Q * S0) / (V * X_vss)',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-BIO-003'],
    dependencies: ['STP.FLOW.ADWF', 'STP.QUAL.BOD5', 'STP.BIO.MLSS'],
    formulaDependencies: [],
    reportSections: ['09 Process Design'],
    boqDependencies: [],
    bimProperties: ['Pset_StpProcess.FMRatio'],
    scadaTags: [],
  },

  // ==========================================================================
  // COSTING & LCCA
  // ==========================================================================
  'STP.COST.ELEC_RATE': {
    id: 'STP.COST.ELEC_RATE',
    category: 'BOQ_COSTING',
    subcategory: 'TARIFFS',
    name: 'Industrial Electricity Tariff Rate',
    symbol: 'C_elec',
    unit: 'USD', // per kWh
    datatype: 'NUMBER',
    min: 0.02,
    max: 0.50,
    defaultValue: 0.12,
    designValue: 0.12,
    source: 'Local Power Utility Tariff Schedule',
    standardReference: 'Utility Tariff Sheet',
    isRequired: true,
    isAssumed: true,
    validationRules: [],
    dependencies: [],
    formulaDependencies: ['CALC-COST-OPEX_POWER'],
    reportSections: ['23 OPEX', '35 LCCA'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.COST.DISCOUNT_RATE': {
    id: 'STP.COST.DISCOUNT_RATE',
    category: 'BOQ_COSTING',
    subcategory: 'FINANCIAL',
    name: 'Financial Discount Rate for LCCA NPV',
    symbol: 'i_disc',
    unit: '%',
    datatype: 'NUMBER',
    min: 1.0,
    max: 15.0,
    defaultValue: 6.0,
    designValue: 6.0,
    source: 'Central Bank / Project Financial Criteria',
    standardReference: 'NPV Discount Rate Standard',
    isRequired: true,
    isAssumed: true,
    validationRules: [],
    dependencies: [],
    formulaDependencies: ['CALC-COST-LCCA_NPV'],
    reportSections: ['35 LCCA'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  // ==========================================================================
  // PHASE 02 DESIGN BASIS & FLOW HYDRAULICS EXTENDED
  // ==========================================================================
  'STP.DEMO.POP_METHOD': {
    id: 'STP.DEMO.POP_METHOD',
    category: 'DEMOGRAPHICS',
    subcategory: 'POPULATION',
    name: 'Population Projection Calculation Method',
    symbol: 'Meth_pop',
    unit: 'enum',
    datatype: 'ENUM',
    defaultValue: 'GEOMETRIC',
    designValue: 'GEOMETRIC',
    source: 'Demographic Study Selection',
    standardReference: 'CPHEEO Manual / Metcalf & Eddy Ch. 2',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: [],
    formulaDependencies: ['CALC-DEMO-DESIGN_POP'],
    reportSections: ['02 Design Basis'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.DEMO.P_INTERMEDIATE': {
    id: 'STP.DEMO.P_INTERMEDIATE',
    category: 'DEMOGRAPHICS',
    subcategory: 'POPULATION',
    name: 'Intermediate Stage Design Population',
    symbol: 'P_inter',
    unit: 'capita',
    datatype: 'NUMBER',
    min: 100,
    max: 10000000,
    defaultValue: 75000,
    designValue: 75000,
    source: 'Phase 1 Construction Horizon (Year 15)',
    standardReference: 'CPHEEO Section 2.4',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.DEMO.P_PRES', 'STP.DEMO.GR_PCT'],
    formulaDependencies: ['CALC-FLOW-STAGE_INTERMEDIATE'],
    reportSections: ['02 Design Basis', '03 Population & Flow'],
    boqDependencies: [],
    bimProperties: ['Pset_StpGeneral.IntermediatePopulation'],
    scadaTags: [],
  },

  'STP.FLOW.PDWF': {
    id: 'STP.FLOW.PDWF',
    category: 'FLOW_HYDRAULICS',
    subcategory: 'FLOW_SUMMARY',
    name: 'Peak Dry Weather Flow',
    symbol: 'PDWF',
    unit: 'm3/day',
    datatype: 'NUMBER',
    min: 10,
    max: 2000000,
    defaultValue: 28858,
    designValue: 28858,
    source: 'Calculated Dry Weather Peak',
    standardReference: 'PDWF = (Sanitary Flow * PF) + Industrial + Infiltration',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.FLOW.ADWF', 'STP.FLOW.PEAK_FACTOR'],
    formulaDependencies: ['CALC-HYD-SEWER_CAPACITY'],
    reportSections: ['03 Population & Flow', '10 Hydraulic Design'],
    boqDependencies: [],
    bimProperties: ['Pset_StpHydraulic.PDWF'],
    scadaTags: ['FIT_INLET_PDWF'],
  },

  'STP.FLOW.AWWF': {
    id: 'STP.FLOW.AWWF',
    category: 'FLOW_HYDRAULICS',
    subcategory: 'FLOW_SUMMARY',
    name: 'Average Wet Weather Flow',
    symbol: 'AWWF',
    unit: 'm3/day',
    datatype: 'NUMBER',
    min: 10,
    max: 2500000,
    defaultValue: 14122,
    designValue: 14122,
    source: 'Calculated Wet Weather Seasonal Average',
    standardReference: 'AWWF = ADWF + Average Rain Inflow',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.FLOW.ADWF', 'STP.FLOW.INFILTRATION'],
    formulaDependencies: ['CALC-BIO-AERATION_LOAD'],
    reportSections: ['03 Population & Flow'],
    boqDependencies: [],
    bimProperties: ['Pset_StpHydraulic.AWWF'],
    scadaTags: [],
  },

  'STP.FLOW.MIN_FLOW': {
    id: 'STP.FLOW.MIN_FLOW',
    category: 'FLOW_HYDRAULICS',
    subcategory: 'FLOW_SUMMARY',
    name: 'Minimum Diurnal Flow (Dry Weather)',
    symbol: 'Q_min',
    unit: 'm3/day',
    datatype: 'NUMBER',
    min: 5,
    max: 500000,
    defaultValue: 4235,
    designValue: 4235,
    source: 'Night Minimum Diurnal Flow Hydrograph',
    standardReference: 'Q_min = 0.25 * ADWF + Infiltration',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-HYD-001'],
    dependencies: ['STP.FLOW.ADWF'],
    formulaDependencies: ['CALC-SEWER-SELF_CLEANSING'],
    reportSections: ['03 Population & Flow', '05 Sewerage Network'],
    boqDependencies: [],
    bimProperties: ['Pset_StpHydraulic.MinFlow'],
    scadaTags: [],
  },

  'STP.FLOW.PEAKING_METHOD': {
    id: 'STP.FLOW.PEAKING_METHOD',
    category: 'FLOW_HYDRAULICS',
    subcategory: 'PEAKING',
    name: 'Peaking Factor Formula Selection',
    symbol: 'Meth_pf',
    unit: 'enum',
    datatype: 'ENUM',
    defaultValue: 'HARMON',
    designValue: 'HARMON',
    source: 'Engineering Standard Selection',
    standardReference: 'Harmon / Babbit / Gifft / Fair-Geyer / ATV',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: [],
    formulaDependencies: ['CALC-FLOW-PEAK_FACTOR'],
    reportSections: ['02 Design Basis', '03 Population & Flow'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.FLOW.INFILTRATION_METHOD': {
    id: 'STP.FLOW.INFILTRATION_METHOD',
    category: 'FLOW_HYDRAULICS',
    subcategory: 'INFLOW_INFILTRATION',
    name: 'Infiltration Calculation Model',
    symbol: 'Meth_inf',
    unit: 'enum',
    datatype: 'ENUM',
    defaultValue: 'PIPE_LENGTH',
    designValue: 'PIPE_LENGTH',
    source: 'Sewer Network Modeling Method',
    standardReference: 'WEF MOP 9',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: [],
    formulaDependencies: ['CALC-FLOW-INFILTRATION'],
    reportSections: ['03 Population & Flow'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.FLOW.RAIN_INFLOW': {
    id: 'STP.FLOW.RAIN_INFLOW',
    category: 'FLOW_HYDRAULICS',
    subcategory: 'INFLOW_INFILTRATION',
    name: 'Rain-Derived Direct Storm Inflow Allowance',
    symbol: 'Q_rdi',
    unit: 'L/s',
    datatype: 'NUMBER',
    min: 0,
    max: 1000,
    defaultValue: 25.0,
    designValue: 25.0,
    source: 'Hydrological Catchment Storm Allowance',
    standardReference: 'ASCE MOP 60 Rain-Derived Inflow',
    isRequired: true,
    isAssumed: true,
    validationRules: [],
    dependencies: [],
    formulaDependencies: ['CALC-FLOW-PWWF'],
    reportSections: ['03 Population & Flow'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  // ==========================================================================
  // PHASE 02 WASTEWATER QUALITY & RATIOS EXTENDED
  // ==========================================================================
  'STP.QUAL.COD_SOLUBLE': {
    id: 'STP.QUAL.COD_SOLUBLE',
    category: 'INFLUENT_QUALITY',
    subcategory: 'ORGANICS',
    name: 'Influent Soluble Chemical Oxygen Demand',
    symbol: 'COD_sol',
    unit: 'mg/L',
    datatype: 'NUMBER',
    min: 20,
    max: 1200,
    defaultValue: 200,
    designValue: 200,
    source: 'Filtered Lab Sample Analysis (0.45µm)',
    standardReference: 'Standard Methods 5220 D',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.QUAL.COD'],
    formulaDependencies: ['CALC-BIO-DENITRIFICATION_RATE'],
    reportSections: ['04 Wastewater Characterization'],
    boqDependencies: [],
    bimProperties: ['Pset_StpProcess.InfluentSolubleCOD'],
    scadaTags: [],
  },

  'STP.QUAL.COD_INERT': {
    id: 'STP.QUAL.COD_INERT',
    category: 'INFLUENT_QUALITY',
    subcategory: 'ORGANICS',
    name: 'Influent Unbiodegradable Inert COD Fraction',
    symbol: 'COD_i',
    unit: 'mg/L',
    datatype: 'NUMBER',
    min: 10,
    max: 300,
    defaultValue: 50,
    designValue: 50,
    source: 'Respirometric Lab Assay',
    standardReference: 'IWA Activated Sludge Model No. 1 (ASM1)',
    isRequired: true,
    isAssumed: true,
    validationRules: [],
    dependencies: ['STP.QUAL.COD'],
    formulaDependencies: ['CALC-SLUDGE-INERT_ACCUMULATION'],
    reportSections: ['04 Wastewater Characterization', '18 Sludge Balance'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.QUAL.TN': {
    id: 'STP.QUAL.TN',
    category: 'INFLUENT_QUALITY',
    subcategory: 'NUTRIENTS',
    name: 'Influent Total Nitrogen',
    symbol: 'TN',
    unit: 'mg/L',
    datatype: 'NUMBER',
    min: 15,
    max: 150,
    defaultValue: 48,
    designValue: 48,
    source: 'Laboratory Analysis (TKN + NO3 + NO2)',
    standardReference: 'Standard Methods 4500-N',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.QUAL.TKN'],
    formulaDependencies: ['CALC-BNR-TN_REMOVAL_EFFICIENCY'],
    reportSections: ['04 Wastewater Characterization', '12 Nitrogen Removal'],
    boqDependencies: [],
    bimProperties: ['Pset_StpProcess.InfluentTN'],
    scadaTags: ['AI_TN_INLET'],
  },

  'STP.QUAL.ORG_N': {
    id: 'STP.QUAL.ORG_N',
    category: 'INFLUENT_QUALITY',
    subcategory: 'NUTRIENTS',
    name: 'Influent Organic Nitrogen',
    symbol: 'Org-N',
    unit: 'mg/L',
    datatype: 'NUMBER',
    min: 5,
    max: 60,
    defaultValue: 15,
    designValue: 15,
    source: 'Calculated: TKN - NH3-N',
    standardReference: 'Standard Methods 4500-Norg',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.QUAL.TKN', 'STP.QUAL.NH3N'],
    formulaDependencies: ['CALC-BNR-AMMONIFICATION'],
    reportSections: ['04 Wastewater Characterization'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.QUAL.PO4_P': {
    id: 'STP.QUAL.PO4_P',
    category: 'INFLUENT_QUALITY',
    subcategory: 'NUTRIENTS',
    name: 'Influent Orthophosphate',
    symbol: 'PO4-P',
    unit: 'mg/L',
    datatype: 'NUMBER',
    min: 1.0,
    max: 18.0,
    defaultValue: 5.0,
    designValue: 5.0,
    source: 'Filtered Lab Sample Analysis',
    standardReference: 'Standard Methods 4500-P F',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.QUAL.TP'],
    formulaDependencies: ['CALC-EBPR-PHOSPHATE_RELEASE'],
    reportSections: ['04 Wastewater Characterization', '13 Phosphorus Removal'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.QUAL.BOD_COD_RATIO': {
    id: 'STP.QUAL.BOD_COD_RATIO',
    category: 'INFLUENT_QUALITY',
    subcategory: 'CHARACTERIZATION_RATIOS',
    name: 'BOD5 / COD Biodegradability Index Ratio',
    symbol: 'BOD/COD',
    unit: 'ratio',
    datatype: 'NUMBER',
    min: 0.15,
    max: 0.85,
    defaultValue: 0.55,
    designValue: 0.55,
    source: 'Calculated Characterization Ratio',
    standardReference: 'Metcalf & Eddy Section 3-4',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-QUAL-002'],
    dependencies: ['STP.QUAL.BOD5', 'STP.QUAL.COD'],
    formulaDependencies: ['CALC-FEASIBILITY-BIODEGRADABILITY'],
    reportSections: ['04 Wastewater Characterization'],
    boqDependencies: [],
    bimProperties: ['Pset_StpProcess.BODtoCODRatio'],
    scadaTags: [],
  },

  'STP.QUAL.COD_TKN_RATIO': {
    id: 'STP.QUAL.COD_TKN_RATIO',
    category: 'INFLUENT_QUALITY',
    subcategory: 'CHARACTERIZATION_RATIOS',
    name: 'COD / TKN Carbon to Nitrogen Ratio for Denitrification',
    symbol: 'COD/TKN',
    unit: 'ratio',
    datatype: 'NUMBER',
    min: 4.0,
    max: 25.0,
    defaultValue: 10.0,
    designValue: 10.0,
    source: 'Calculated Characterization Ratio',
    standardReference: 'IWA Biological Wastewater Treatment',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.QUAL.COD', 'STP.QUAL.TKN'],
    formulaDependencies: ['CALC-FEASIBILITY-DENITRIFICATION'],
    reportSections: ['04 Wastewater Characterization', '12 Nitrogen Removal'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.QUAL.BOD_TP_RATIO': {
    id: 'STP.QUAL.BOD_TP_RATIO',
    category: 'INFLUENT_QUALITY',
    subcategory: 'CHARACTERIZATION_RATIOS',
    name: 'BOD5 / TP Ratio for Bio-P EBPR Feasibility',
    symbol: 'BOD/TP',
    unit: 'ratio',
    datatype: 'NUMBER',
    min: 10.0,
    max: 80.0,
    defaultValue: 31.25,
    designValue: 31.25,
    source: 'Calculated Characterization Ratio',
    standardReference: 'WEF MOP 8 Biological Phosphorus Removal',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.QUAL.BOD5', 'STP.QUAL.TP'],
    formulaDependencies: ['CALC-FEASIBILITY-EBPR'],
    reportSections: ['04 Wastewater Characterization', '13 Phosphorus Removal'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.QUAL.VSS_TSS_RATIO': {
    id: 'STP.QUAL.VSS_TSS_RATIO',
    category: 'INFLUENT_QUALITY',
    subcategory: 'CHARACTERIZATION_RATIOS',
    name: 'VSS / TSS Volatile Fraction',
    symbol: 'VSS/TSS',
    unit: 'ratio',
    datatype: 'NUMBER',
    min: 0.50,
    max: 0.95,
    defaultValue: 0.80,
    designValue: 0.80,
    source: 'Calculated Volatile Solids Fraction',
    standardReference: 'Standard Methods 2540 E',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.QUAL.TSS', 'STP.QUAL.VSS'],
    formulaDependencies: ['CALC-SLUDGE-VOLATILE_MASS'],
    reportSections: ['04 Wastewater Characterization', '18 Sludge Balance'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.QUAL.ALK_TKN_RATIO': {
    id: 'STP.QUAL.ALK_TKN_RATIO',
    category: 'INFLUENT_QUALITY',
    subcategory: 'CHARACTERIZATION_RATIOS',
    name: 'Alkalinity / TKN Nitrification Buffer Ratio',
    symbol: 'Alk/TKN',
    unit: 'ratio',
    datatype: 'NUMBER',
    min: 2.0,
    max: 15.0,
    defaultValue: 4.44,
    designValue: 4.44,
    source: 'Calculated Alkalinity Buffer Factor',
    standardReference: '7.14 g CaCO3 required per g NH4-N nitrified',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.QUAL.alkalinity', 'STP.QUAL.TKN'],
    formulaDependencies: ['CALC-FEASIBILITY-ALKALINITY'],
    reportSections: ['04 Wastewater Characterization', '12 Nitrogen Removal'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  // ==========================================================================
  // PHASE 02 POLLUTANT MASS LOADINGS & INDUSTRIAL CONTRIBUTIONS
  // ==========================================================================
  'STP.MASS.BOD_DAILY': {
    id: 'STP.MASS.BOD_DAILY',
    category: 'INFLUENT_QUALITY',
    subcategory: 'MASS_LOADINGS',
    name: 'Average Daily BOD5 Mass Load Rate',
    symbol: 'M_BOD',
    unit: 'kg/day',
    datatype: 'NUMBER',
    min: 10,
    max: 500000,
    defaultValue: 3206.5,
    designValue: 3206.5,
    source: 'Calculated Mass Load (ADWF * BOD5 / 1000)',
    standardReference: 'Metcalf & Eddy Section 3-4',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.FLOW.ADWF', 'STP.QUAL.BOD5'],
    formulaDependencies: ['CALC-BIO-AERATION_SIZING', 'CALC-SLUDGE-YIELD'],
    reportSections: ['01 Executive Summary', '04 Wastewater Characterization', '09 Process Design'],
    boqDependencies: ['BOQ-MECH-BLOWER'],
    bimProperties: ['Pset_StpProcess.BODDailyMassKg'],
    scadaTags: [],
  },

  'STP.MASS.COD_DAILY': {
    id: 'STP.MASS.COD_DAILY',
    category: 'INFLUENT_QUALITY',
    subcategory: 'MASS_LOADINGS',
    name: 'Average Daily COD Mass Load Rate',
    symbol: 'M_COD',
    unit: 'kg/day',
    datatype: 'NUMBER',
    min: 20,
    max: 1000000,
    defaultValue: 5771.7,
    designValue: 5771.7,
    source: 'Calculated Mass Load (ADWF * COD / 1000)',
    standardReference: 'Metcalf & Eddy Section 3-4',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.FLOW.ADWF', 'STP.QUAL.COD'],
    formulaDependencies: ['CALC-BIO-MASS_BALANCE'],
    reportSections: ['04 Wastewater Characterization'],
    boqDependencies: [],
    bimProperties: ['Pset_StpProcess.CODDailyMassKg'],
    scadaTags: [],
  },

  'STP.MASS.TSS_DAILY': {
    id: 'STP.MASS.TSS_DAILY',
    category: 'INFLUENT_QUALITY',
    subcategory: 'MASS_LOADINGS',
    name: 'Average Daily TSS Mass Load Rate',
    symbol: 'M_TSS',
    unit: 'kg/day',
    datatype: 'NUMBER',
    min: 10,
    max: 500000,
    defaultValue: 3591.3,
    designValue: 3591.3,
    source: 'Calculated Mass Load (ADWF * TSS / 1000)',
    standardReference: 'Metcalf & Eddy Section 3-4',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.FLOW.ADWF', 'STP.QUAL.TSS'],
    formulaDependencies: ['CALC-PRIMARY-SLUDGE', 'CALC-DEWATERING-THICKENER'],
    reportSections: ['04 Wastewater Characterization', '18 Sludge Balance'],
    boqDependencies: ['BOQ-SLUDGE-001'],
    bimProperties: ['Pset_StpProcess.TSSDailyMassKg'],
    scadaTags: [],
  },

  'STP.MASS.TKN_DAILY': {
    id: 'STP.MASS.TKN_DAILY',
    category: 'INFLUENT_QUALITY',
    subcategory: 'MASS_LOADINGS',
    name: 'Average Daily TKN Mass Load Rate',
    symbol: 'M_TKN',
    unit: 'kg/day',
    datatype: 'NUMBER',
    min: 2,
    max: 50000,
    defaultValue: 577.2,
    designValue: 577.2,
    source: 'Calculated Mass Load (ADWF * TKN / 1000)',
    standardReference: 'Metcalf & Eddy Section 3-4',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.FLOW.ADWF', 'STP.QUAL.TKN'],
    formulaDependencies: ['CALC-BNR-O2_NITRIFICATION'],
    reportSections: ['04 Wastewater Characterization', '12 Nitrogen Removal'],
    boqDependencies: [],
    bimProperties: ['Pset_StpProcess.TKNDailyMassKg'],
    scadaTags: [],
  },

  'STP.MASS.TP_DAILY': {
    id: 'STP.MASS.TP_DAILY',
    category: 'INFLUENT_QUALITY',
    subcategory: 'MASS_LOADINGS',
    name: 'Average Daily TP Mass Load Rate',
    symbol: 'M_TP',
    unit: 'kg/day',
    datatype: 'NUMBER',
    min: 0.5,
    max: 10000,
    defaultValue: 102.6,
    designValue: 102.6,
    source: 'Calculated Mass Load (ADWF * TP / 1000)',
    standardReference: 'Metcalf & Eddy Section 3-4',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.FLOW.ADWF', 'STP.QUAL.TP'],
    formulaDependencies: ['CALC-P-ALUM_DOSE'],
    reportSections: ['04 Wastewater Characterization', '13 Phosphorus Removal'],
    boqDependencies: ['BOQ-CHEM-ALUM'],
    bimProperties: ['Pset_StpProcess.TPDailyMassKg'],
    scadaTags: [],
  },

  'STP.IND.FLOW_TOTAL': {
    id: 'STP.IND.FLOW_TOTAL',
    category: 'FLOW_HYDRAULICS',
    subcategory: 'INDUSTRIAL_CONTRIBUTION',
    name: 'Total Industrial Wastewater Flow Rate',
    symbol: 'Q_ind_tot',
    unit: 'm3/day',
    datatype: 'NUMBER',
    min: 0,
    max: 200000,
    defaultValue: 1000,
    designValue: 1000,
    source: 'Sum of Industrial Discharger Profiles',
    standardReference: 'EPA Pretreatment Standards',
    isRequired: false,
    isAssumed: true,
    validationRules: [],
    dependencies: [],
    formulaDependencies: ['CALC-FLOW-ADWF', 'CALC-MASS-BLENDED_QUALITY'],
    reportSections: ['03 Population & Flow', '04 Wastewater Characterization'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  'STP.IND.BOD_CONTRIB': {
    id: 'STP.IND.BOD_CONTRIB',
    category: 'INFLUENT_QUALITY',
    subcategory: 'INDUSTRIAL_CONTRIBUTION',
    name: 'Industrial Percentage Share of Total BOD Load',
    symbol: 'Pct_BOD_ind',
    unit: '%',
    datatype: 'NUMBER',
    min: 0,
    max: 100,
    defaultValue: 15.6,
    designValue: 15.6,
    source: 'Calculated Mass Share',
    standardReference: 'Industrial Mass Balance',
    isRequired: false,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.IND.FLOW_TOTAL', 'STP.MASS.BOD_DAILY'],
    formulaDependencies: ['CALC-SEWER-FLOW_ACCUM'],
    reportSections: ['04 Wastewater Characterization'],
    boqDependencies: [],
    bimProperties: [],
    scadaTags: [],
  },

  // ==========================================================================
  // PHASE 03 — SEWERAGE COLLECTION NETWORK, PUMPING STATION & FORCE MAIN
  // ==========================================================================
  'STP.SWR.PIPE.LENGTH': {
    id: 'STP.SWR.PIPE.LENGTH',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'PIPELINE_GEOMETRY',
    name: 'Sewer Trunk Pipeline Length',
    symbol: 'L_swr',
    unit: 'm',
    datatype: 'NUMBER',
    min: 1,
    max: 50000,
    defaultValue: 250,
    designValue: 250,
    source: 'Sewerage Masterplan GIS Alignment',
    standardReference: 'CPHEEO Sewerage Manual / ASCE MOP 60',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-SWR-001'],
    dependencies: [],
    formulaDependencies: ['CALC-SWR-MANNING_CAPACITY', 'CALC-SWR-HGL_PROFILE'],
    reportSections: ['05 Sewerage Collection Network'],
    boqDependencies: ['BOQ-SWR-PIPE_TRENCH'],
    bimProperties: ['Pset_SewerSegment.Length'],
    scadaTags: [],
  },

  'STP.SWR.PIPE.DIAMETER': {
    id: 'STP.SWR.PIPE.DIAMETER',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'PIPELINE_GEOMETRY',
    name: 'Sewer Pipe Nominal Internal Diameter',
    symbol: 'D_swr',
    unit: 'mm',
    datatype: 'NUMBER',
    min: 150,
    max: 3500,
    defaultValue: 375,
    designValue: 375,
    source: 'Hydraulic Diameter Sizing Engine',
    standardReference: 'Manning Equation Full/Partial Flow',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-SWR-002'],
    dependencies: ['STP.FLOW.PWWF'],
    formulaDependencies: ['CALC-SWR-MANNING_CAPACITY', 'CALC-SWR-PARTIAL_DEPTH'],
    reportSections: ['05 Sewerage Collection Network'],
    boqDependencies: ['BOQ-SWR-PIPE_SUPPLY'],
    bimProperties: ['Pset_SewerSegment.Diameter'],
    scadaTags: [],
  },

  'STP.SWR.PIPE.SLOPE': {
    id: 'STP.SWR.PIPE.SLOPE',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'PIPELINE_GEOMETRY',
    name: 'Gravity Sewer Longitudinal Invert Bed Slope',
    symbol: 'S_swr',
    unit: 'm/m',
    datatype: 'NUMBER',
    min: 0.0005,
    max: 0.10,
    defaultValue: 0.0035,
    designValue: 0.0035,
    source: 'Topographical Profile Gradient',
    standardReference: 'Self-Cleansing Velocity Slope Criteria (1/D)',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-SWR-003'],
    dependencies: ['STP.SWR.PIPE.DIAMETER'],
    formulaDependencies: ['CALC-SWR-MANNING_CAPACITY', 'CALC-SWR-VELOCITY'],
    reportSections: ['05 Sewerage Collection Network'],
    boqDependencies: [],
    bimProperties: ['Pset_SewerSegment.Slope'],
    scadaTags: [],
  },

  'STP.SWR.PIPE.ROUGHNESS': {
    id: 'STP.SWR.PIPE.ROUGHNESS',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'HYDRAULIC_COEFFICIENTS',
    name: "Manning Roughness Coefficient 'n'",
    symbol: 'n_manning',
    unit: 's/m^(1/3)',
    datatype: 'NUMBER',
    min: 0.008,
    max: 0.020,
    defaultValue: 0.010,
    designValue: 0.010,
    source: 'Pipe Material Specification (uPVC/HDPE/RCC)',
    standardReference: 'Metcalf & Eddy Table 3-5 / CPHEEO',
    isRequired: true,
    isAssumed: true,
    validationRules: ['VAL-SWR-004'],
    dependencies: [],
    formulaDependencies: ['CALC-SWR-MANNING_CAPACITY'],
    reportSections: ['05 Sewerage Collection Network'],
    boqDependencies: [],
    bimProperties: ['Pset_SewerSegment.ManningRoughness'],
    scadaTags: [],
  },

  'STP.SWR.PIPE.FLOW': {
    id: 'STP.SWR.PIPE.FLOW',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'HYDRAULIC_OPERATING',
    name: 'Peak Design Sewage Flow in Sewer Pipe',
    symbol: 'Q_swr_peak',
    unit: 'L/s',
    datatype: 'NUMBER',
    min: 0.1,
    max: 5000,
    defaultValue: 80.0,
    designValue: 80.0,
    source: 'Accumulated Catchment Hydraulics',
    standardReference: 'Peak Wet Weather Flow Allocation',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-SWR-005'],
    dependencies: ['STP.FLOW.PWWF'],
    formulaDependencies: ['CALC-SWR-PARTIAL_DEPTH', 'CALC-SWR-VELOCITY'],
    reportSections: ['05 Sewerage Collection Network'],
    boqDependencies: [],
    bimProperties: ['Pset_SewerSegment.DesignFlow'],
    scadaTags: ['FIT_SEWER_TRUNK'],
  },

  'STP.SWR.PIPE.VELOCITY': {
    id: 'STP.SWR.PIPE.VELOCITY',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'HYDRAULIC_OPERATING',
    name: 'Actual Operating Flow Velocity in Sewer',
    symbol: 'V_swr',
    unit: 'm/s',
    datatype: 'NUMBER',
    min: 0.1,
    max: 5.0,
    defaultValue: 1.15,
    designValue: 1.15,
    source: 'Manning Partial Flow Calculation',
    standardReference: 'Self-Cleansing (V >= 0.6 m/s) & Non-Scouring (V <= 3.0 m/s)',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-SWR-006'],
    dependencies: ['STP.SWR.PIPE.FLOW', 'STP.SWR.PIPE.DIAMETER', 'STP.SWR.PIPE.SLOPE'],
    formulaDependencies: ['CALC-SWR-HGL_PROFILE'],
    reportSections: ['05 Sewerage Collection Network'],
    boqDependencies: [],
    bimProperties: ['Pset_SewerSegment.ActualVelocity'],
    scadaTags: [],
  },

  'STP.SWR.PIPE.HGL': {
    id: 'STP.SWR.PIPE.HGL',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'HYDRAULIC_LEVELS',
    name: 'Hydraulic Grade Line Elevation at Node',
    symbol: 'HGL_swr',
    unit: 'm',
    datatype: 'NUMBER',
    min: -50,
    max: 5000,
    defaultValue: 22.1,
    designValue: 22.1,
    source: 'Hydraulic Gradient Energy Balance',
    standardReference: 'Longitudinal Profile Continuity',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-SWR-007'],
    dependencies: ['STP.SWR.PIPE.VELOCITY'],
    formulaDependencies: ['CALC-SWR-HGL_PROFILE'],
    reportSections: ['05 Sewerage Collection Network'],
    boqDependencies: [],
    bimProperties: ['Pset_SewerNode.HGL'],
    scadaTags: ['LIT_MH_LEVEL'],
  },

  'STP.SWR.MH.INVERT': {
    id: 'STP.SWR.MH.INVERT',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'MANHOLE_LEVELS',
    name: 'Manhole Invert Level Elevation',
    symbol: 'IL_mh',
    unit: 'm',
    datatype: 'NUMBER',
    min: -50,
    max: 5000,
    defaultValue: 21.7,
    designValue: 21.7,
    source: 'Civil Site Survey & Sewer Grading',
    standardReference: 'Topographic Survey / Invert Benchmarking',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: [],
    formulaDependencies: ['CALC-SWR-SLOPE', 'CALC-SWR-COVER_DEPTH'],
    reportSections: ['05 Sewerage Collection Network'],
    boqDependencies: ['BOQ-CIV-MANHOLE'],
    bimProperties: ['Pset_Manhole.InvertLevel'],
    scadaTags: [],
  },

  'STP.SWR.MH.GROUND': {
    id: 'STP.SWR.MH.GROUND',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'MANHOLE_LEVELS',
    name: 'Manhole Cover Ground / Road Elevation',
    symbol: 'GL_mh',
    unit: 'm',
    datatype: 'NUMBER',
    min: -50,
    max: 5000,
    defaultValue: 23.5,
    designValue: 23.5,
    source: 'Finished Ground Road Level',
    standardReference: 'Topographic Ground Benchmark',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: [],
    formulaDependencies: ['CALC-SWR-COVER_DEPTH'],
    reportSections: ['05 Sewerage Collection Network'],
    boqDependencies: ['BOQ-CIV-MANHOLE_COVER'],
    bimProperties: ['Pset_Manhole.GroundLevel'],
    scadaTags: [],
  },

  'STP.PS.WETWELL.ACTIVE_VOLUME': {
    id: 'STP.PS.WETWELL.ACTIVE_VOLUME',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'PUMPING_STATION',
    name: 'Lift Station Wet Well Effective Active Storage Volume',
    symbol: 'V_active',
    unit: 'm3',
    datatype: 'NUMBER',
    min: 1,
    max: 10000,
    defaultValue: 15.75,
    designValue: 15.75,
    source: 'Pump Cycle Time Optimization Formula',
    standardReference: 'V_active = (Q_pump * T_min) / 4 (WEF MOP 8 / HI Standards)',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-PS-001'],
    dependencies: ['STP.FLOW.PWWF'],
    formulaDependencies: ['CALC-PS-CYCLE_TIME', 'CALC-PS-WETWELL_DIMENSIONS'],
    reportSections: ['06 Sewage Pumping Station'],
    boqDependencies: ['BOQ-CIV-WETWELL_CONCRETE'],
    bimProperties: ['Pset_WetWell.ActiveVolume'],
    scadaTags: ['LIT_WETWELL_LEVEL'],
  },

  'STP.PS.PUMP.DUTY_FLOW': {
    id: 'STP.PS.PUMP.DUTY_FLOW',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'PUMPING_STATION',
    name: 'Single Duty Sewage Pump Rated Flow Capacity',
    symbol: 'Q_pump_duty',
    unit: 'L/s',
    datatype: 'NUMBER',
    min: 5,
    max: 5000,
    defaultValue: 87.5,
    designValue: 87.5,
    source: 'Pump Staging Strategy (Peak Inflow / Duty Count)',
    standardReference: 'Hydraulic Institute Standard / HI 9.6',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-PS-002'],
    dependencies: ['STP.FLOW.PWWF'],
    formulaDependencies: ['CALC-PS-TDH', 'CALC-PS-POWER_HYDRAULIC'],
    reportSections: ['06 Sewage Pumping Station'],
    boqDependencies: ['BOQ-MECH-SEWAGE_PUMP'],
    bimProperties: ['Pset_Pump.DutyFlow'],
    scadaTags: ['FIT_PUMP_DISCHARGE'],
  },

  'STP.PS.PUMP.STATIC_HEAD': {
    id: 'STP.PS.PUMP.STATIC_HEAD',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'PUMPING_STATION',
    name: 'Pumping Station Static Elevation Lift Head',
    symbol: 'H_stat',
    unit: 'm',
    datatype: 'NUMBER',
    min: 1,
    max: 300,
    defaultValue: 16.0,
    designValue: 16.0,
    source: 'Discharge Invert Elevation Minus Wet Well Low Water Level',
    standardReference: 'Topographic Static Lift Head',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.SWR.MH.INVERT'],
    formulaDependencies: ['CALC-PS-TDH'],
    reportSections: ['06 Sewage Pumping Station'],
    boqDependencies: [],
    bimProperties: ['Pset_Pump.StaticHead'],
    scadaTags: [],
  },

  'STP.PS.PUMP.FRICTION_HEAD': {
    id: 'STP.PS.PUMP.FRICTION_HEAD',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'PUMPING_STATION',
    name: 'Force Main Friction Headloss at Peak Discharge',
    symbol: 'h_f_main',
    unit: 'm',
    datatype: 'NUMBER',
    min: 0.1,
    max: 200,
    defaultValue: 4.85,
    designValue: 4.85,
    source: 'Hazen-Williams / Darcy-Weisbach Formulation',
    standardReference: 'Hazen-Williams C=150 / Darcy Colebrook-White',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-PS-003'],
    dependencies: ['STP.PS.PUMP.DUTY_FLOW'],
    formulaDependencies: ['CALC-PS-TDH'],
    reportSections: ['06 Sewage Pumping Station', '07 Force Main Hydraulics'],
    boqDependencies: [],
    bimProperties: ['Pset_ForceMain.FrictionLoss'],
    scadaTags: ['PIT_PUMP_DISCHARGE'],
  },

  'STP.PS.PUMP.TDH': {
    id: 'STP.PS.PUMP.TDH',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'PUMPING_STATION',
    name: 'Total Dynamic Head (TDH) for Pump Selection',
    symbol: 'TDH',
    unit: 'm',
    datatype: 'NUMBER',
    min: 2,
    max: 350,
    defaultValue: 21.8,
    designValue: 21.8,
    source: 'TDH = Static Head + Friction Head + Minor Fittings Losses',
    standardReference: 'Hydraulic Institute Standards HI 1.3 / 9.6',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-PS-004'],
    dependencies: ['STP.PS.PUMP.STATIC_HEAD', 'STP.PS.PUMP.FRICTION_HEAD'],
    formulaDependencies: ['CALC-PS-POWER_HYDRAULIC', 'CALC-PS-MOTOR_KW'],
    reportSections: ['06 Sewage Pumping Station'],
    boqDependencies: ['BOQ-MECH-PUMP_PROCUREMENT'],
    bimProperties: ['Pset_Pump.TDH'],
    scadaTags: ['PIT_DISCHARGE_MANIFOLD'],
  },

  'STP.PS.PUMP.POWER': {
    id: 'STP.PS.PUMP.POWER',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'PUMPING_STATION',
    name: 'Installed Motor Electrical Power Rating per Pump',
    symbol: 'P_motor_kw',
    unit: 'kW',
    datatype: 'NUMBER',
    min: 0.75,
    max: 1000,
    defaultValue: 30.0,
    designValue: 30.0,
    source: 'P_elec = (rho * g * Q * TDH) / (eta_pump * eta_motor)',
    standardReference: 'IEC Electric Motor Sizing Standard with 20% Reserve',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-PS-005'],
    dependencies: ['STP.PS.PUMP.TDH', 'STP.PS.PUMP.DUTY_FLOW'],
    formulaDependencies: ['CALC-ELEC-PUMP_STATION_LOAD'],
    reportSections: ['06 Sewage Pumping Station', '21 Electrical Systems'],
    boqDependencies: ['BOQ-ELEC-VFD_PANEL', 'BOQ-ELEC-MCC'],
    bimProperties: ['Pset_ElectricalDevice.MotorRatingKw'],
    scadaTags: ['II_PUMP_CURRENT', 'PI_PUMP_KW'],
  },

  'STP.FM.HEADLOSS': {
    id: 'STP.FM.HEADLOSS',
    category: 'SEWER_HYDRAULICS',
    subcategory: 'FORCE_MAIN',
    name: 'Total Force Main Pressure Headloss Gradient',
    symbol: 'h_fm_tot',
    unit: 'm',
    datatype: 'NUMBER',
    min: 0.1,
    max: 200,
    defaultValue: 5.8,
    designValue: 5.8,
    source: 'Sum of Pipe Friction and Minor Losses (Valves, Bends, Exit)',
    standardReference: 'AWWA M11 / Hazen-Williams Equation',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.PS.PUMP.FRICTION_HEAD'],
    formulaDependencies: ['CALC-PS-TDH'],
    reportSections: ['07 Force Main Hydraulics'],
    boqDependencies: ['BOQ-MECH-FORCE_MAIN'],
    bimProperties: ['Pset_ForceMain.TotalLoss'],
    scadaTags: [],
  },

  // ==========================================================================
  // PHASE 04: PRELIMINARY TREATMENT & SCREENING
  // ==========================================================================
  'STP.PRELIM.SCREEN.BAR_OPENING': {
    id: 'STP.PRELIM.SCREEN.BAR_OPENING',
    category: 'PRELIMINARY_TREATMENT',
    subcategory: 'SCREENING',
    name: 'Coarse Screen Bar Clear Opening Spacing',
    symbol: 'b_scr',
    unit: 'mm',
    datatype: 'NUMBER',
    min: 6,
    max: 50,
    defaultValue: 20,
    designValue: 20,
    source: 'Process Design Standard',
    standardReference: 'Metcalf & Eddy Table 5-2 / CPHEEO 5.2.2',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-SCR-001'],
    dependencies: [],
    formulaDependencies: ['CALC-SCR-HEADLOSS', 'CALC-SCR-OPEN_AREA'],
    reportSections: ['08 Preliminary Screening'],
    boqDependencies: ['BOQ-MECH-BAR_SCREEN'],
    bimProperties: ['Pset_Screen.BarSpacing'],
    scadaTags: [],
  },

  'STP.PRELIM.SCREEN.APPROACH_VEL': {
    id: 'STP.PRELIM.SCREEN.APPROACH_VEL',
    category: 'PRELIMINARY_TREATMENT',
    subcategory: 'SCREENING',
    name: 'Inlet Channel Approach Velocity',
    symbol: 'v_approach',
    unit: 'm/s',
    datatype: 'NUMBER',
    min: 0.3,
    max: 1.2,
    defaultValue: 0.6,
    designValue: 0.6,
    source: 'v_a = Q_peak / (W_ch * d_w)',
    standardReference: 'WEF Manual of Practice 8 (0.4 - 0.9 m/s range)',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-SCR-002'],
    dependencies: ['STP.PRELIM.SCREEN.BAR_OPENING'],
    formulaDependencies: ['CALC-SCR-HEADLOSS'],
    reportSections: ['08 Preliminary Screening'],
    boqDependencies: [],
    bimProperties: ['Pset_Screen.ApproachVelocity'],
    scadaTags: ['FIT_INLET_CHANNEL'],
  },

  'STP.PRELIM.SCREEN.THROUGH_VEL': {
    id: 'STP.PRELIM.SCREEN.THROUGH_VEL',
    category: 'PRELIMINARY_TREATMENT',
    subcategory: 'SCREENING',
    name: 'Flow Velocity Through Screen Bars',
    symbol: 'v_through',
    unit: 'm/s',
    datatype: 'NUMBER',
    min: 0.5,
    max: 1.5,
    defaultValue: 0.85,
    designValue: 0.85,
    source: 'v_t = Q_peak / A_effective',
    standardReference: 'CPHEEO Manual 5.2.2 (Max 1.25 m/s clean, 1.40 m/s clogged)',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-SCR-003'],
    dependencies: ['STP.PRELIM.SCREEN.APPROACH_VEL'],
    formulaDependencies: ['CALC-SCR-HEADLOSS'],
    reportSections: ['08 Preliminary Screening'],
    boqDependencies: [],
    bimProperties: ['Pset_Screen.ThroughVelocity'],
    scadaTags: [],
  },

  'STP.PRELIM.SCREEN.CLEAN_HL': {
    id: 'STP.PRELIM.SCREEN.CLEAN_HL',
    category: 'PRELIMINARY_TREATMENT',
    subcategory: 'SCREENING',
    name: 'Kirschmer Clean Screen Headloss',
    symbol: 'h_L_clean',
    unit: 'm',
    datatype: 'NUMBER',
    min: 0.005,
    max: 0.25,
    defaultValue: 0.045,
    designValue: 0.045,
    source: 'h_L = beta * (s/b)^(4/3) * (v_a^2 / 2g) * sin(theta)',
    standardReference: 'Kirschmer Equation / Metcalf & Eddy Eq. 5-3',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-SCR-004'],
    dependencies: ['STP.PRELIM.SCREEN.BAR_OPENING'],
    formulaDependencies: ['CALC-PLANT-HGL'],
    reportSections: ['08 Preliminary Screening', '12 Plant Hydraulics & HGL'],
    boqDependencies: [],
    bimProperties: ['Pset_Screen.CleanHeadloss'],
    scadaTags: ['PDIT_SCREEN_DIFF_PRESS'],
  },

  'STP.PRELIM.SCREEN.CLOGGED_HL': {
    id: 'STP.PRELIM.SCREEN.CLOGGED_HL',
    category: 'PRELIMINARY_TREATMENT',
    subcategory: 'SCREENING',
    name: 'Design Clogged Screen Headloss (50% Blockage)',
    symbol: 'h_L_clogged',
    unit: 'm',
    datatype: 'NUMBER',
    min: 0.05,
    max: 0.8,
    defaultValue: 0.22,
    designValue: 0.22,
    source: 'Orifice Headloss with 50% screen blinded area',
    standardReference: 'CPHEEO / WEF MOP 8 (Max 0.40 m allowable)',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-SCR-005'],
    dependencies: ['STP.PRELIM.SCREEN.CLEAN_HL'],
    formulaDependencies: ['CALC-PLANT-HGL'],
    reportSections: ['08 Preliminary Screening'],
    boqDependencies: [],
    bimProperties: ['Pset_Screen.CloggedHeadloss'],
    scadaTags: ['PDIT_SCREEN_CLOG_ALARM'],
  },

  'STP.PRELIM.SCREEN.YIELD_VOL': {
    id: 'STP.PRELIM.SCREEN.YIELD_VOL',
    category: 'PRELIMINARY_TREATMENT',
    subcategory: 'SCREENING',
    name: 'Screenings Wet Volume Generation Rate',
    symbol: 'V_screenings',
    unit: 'm3/day',
    datatype: 'NUMBER',
    min: 0.01,
    max: 20,
    defaultValue: 0.35,
    designValue: 0.35,
    source: '(Q_m3d / 1000) * (Yield_L_per_1000m3 / 1000)',
    standardReference: 'Metcalf & Eddy Table 5-4 (15 - 30 L/1000m3)',
    isRequired: true,
    isAssumed: true,
    validationRules: [],
    dependencies: [],
    formulaDependencies: ['CALC-SOLID-WASTE_MANAGEMENT'],
    reportSections: ['08 Preliminary Screening', '25 Solid Waste Handling'],
    boqDependencies: ['BOQ-SOLID-SCREENINGS_SKIP'],
    bimProperties: ['Pset_SolidWaste.DailyScreeningsM3'],
    scadaTags: [],
  },

  // ==========================================================================
  // PHASE 04: GRIT REMOVAL
  // ==========================================================================
  'STP.PRELIM.GRIT.DETENTION': {
    id: 'STP.PRELIM.GRIT.DETENTION',
    category: 'PRELIMINARY_TREATMENT',
    subcategory: 'GRIT_REMOVAL',
    name: 'Grit Chamber Hydraulic Retention Time',
    symbol: 'HRT_grit',
    unit: 's',
    datatype: 'NUMBER',
    min: 20,
    max: 360,
    defaultValue: 210,
    designValue: 210,
    source: 'V_chamber / Q_peak',
    standardReference: 'CPHEEO / WEF MOP 8 (3.0 - 5.0 min aerated, 45-60s horizontal)',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-GRIT-001'],
    dependencies: [],
    formulaDependencies: ['CALC-GRIT-SIZING'],
    reportSections: ['09 Grit Removal'],
    boqDependencies: ['BOQ-CIVIL-GRIT_CHAMBER'],
    bimProperties: ['Pset_GritChamber.HRT'],
    scadaTags: [],
  },

  'STP.PRELIM.GRIT.VELOCITY': {
    id: 'STP.PRELIM.GRIT.VELOCITY',
    category: 'PRELIMINARY_TREATMENT',
    subcategory: 'GRIT_REMOVAL',
    name: 'Controlled Horizontal Velocity in Grit Channel',
    symbol: 'v_grit',
    unit: 'm/s',
    datatype: 'NUMBER',
    min: 0.2,
    max: 0.5,
    defaultValue: 0.30,
    designValue: 0.30,
    source: 'Velocity controlled by downstream proportional weir or flume',
    standardReference: 'Camp-Grit Criterion (0.30 m/s critical scouring velocity)',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-GRIT-002'],
    dependencies: ['STP.PRELIM.GRIT.DETENTION'],
    formulaDependencies: ['CALC-GRIT-SIZING'],
    reportSections: ['09 Grit Removal'],
    boqDependencies: [],
    bimProperties: ['Pset_GritChamber.Velocity'],
    scadaTags: [],
  },

  'STP.PRELIM.GRIT.AIRFLOW': {
    id: 'STP.PRELIM.GRIT.AIRFLOW',
    category: 'PRELIMINARY_TREATMENT',
    subcategory: 'GRIT_REMOVAL',
    name: 'Total Air Supply to Aerated Grit Chamber',
    symbol: 'Q_air_grit',
    unit: 'Nm3/h',
    datatype: 'NUMBER',
    min: 10,
    max: 5000,
    defaultValue: 210,
    designValue: 210,
    source: 'q_air * Tank_Length * 60 (0.2 - 0.5 m3/min per m)',
    standardReference: 'Metcalf & Eddy Section 5-3',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-GRIT-003'],
    dependencies: ['STP.PRELIM.GRIT.DETENTION'],
    formulaDependencies: ['CALC-ELEC-GRIT_BLOWER_POWER'],
    reportSections: ['09 Grit Removal', '21 Electrical Systems'],
    boqDependencies: ['BOQ-MECH-GRIT_BLOWER', 'BOQ-MECH-AIR_DIFFUSERS'],
    bimProperties: ['Pset_GritChamber.AirflowNm3h'],
    scadaTags: ['FIT_GRIT_BLOWER_AIR'],
  },

  'STP.PRELIM.GRIT.YIELD_VOL': {
    id: 'STP.PRELIM.GRIT.YIELD_VOL',
    category: 'PRELIMINARY_TREATMENT',
    subcategory: 'GRIT_REMOVAL',
    name: 'Grit Generation Volume per Day',
    symbol: 'V_grit',
    unit: 'm3/day',
    datatype: 'NUMBER',
    min: 0.01,
    max: 20,
    defaultValue: 0.42,
    designValue: 0.42,
    source: '(Q_m3d / 1000) * (GritYield_L_per_1000m3 / 1000)',
    standardReference: 'Metcalf & Eddy Table 5-6 (15 - 45 L/1000m3)',
    isRequired: true,
    isAssumed: true,
    validationRules: [],
    dependencies: [],
    formulaDependencies: ['CALC-SOLID-WASTE_MANAGEMENT'],
    reportSections: ['09 Grit Removal', '25 Solid Waste Handling'],
    boqDependencies: ['BOQ-SOLID-GRIT_CLASSIFIER', 'BOQ-SOLID-GRIT_SKIP'],
    bimProperties: ['Pset_SolidWaste.DailyGritM3'],
    scadaTags: [],
  },

  // ==========================================================================
  // PHASE 04: FOG MANAGEMENT
  // ==========================================================================
  'STP.PRELIM.FOG.REMOVAL': {
    id: 'STP.PRELIM.FOG.REMOVAL',
    category: 'PRELIMINARY_TREATMENT',
    subcategory: 'FOG_MANAGEMENT',
    name: 'Target FOG Removal Efficiency',
    symbol: 'R_fog',
    unit: '%',
    datatype: 'NUMBER',
    min: 30,
    max: 95,
    defaultValue: 70.0,
    designValue: 70.0,
    source: 'Grease trap and surface skimming baffle performance',
    standardReference: 'EPA Wastewater Technology Fact Sheet (60 - 80% FOG removal)',
    isRequired: true,
    isAssumed: true,
    validationRules: ['VAL-FOG-001'],
    dependencies: [],
    formulaDependencies: ['CALC-MASS_BALANCE-FOG'],
    reportSections: ['10 FOG & Grease Management'],
    boqDependencies: ['BOQ-MECH-GREASE_SKIMMER'],
    bimProperties: ['Pset_Skimmer.RemovalEfficiency'],
    scadaTags: [],
  },

  'STP.PRELIM.FOG.MASS_REM': {
    id: 'STP.PRELIM.FOG.MASS_REM',
    category: 'PRELIMINARY_TREATMENT',
    subcategory: 'FOG_MANAGEMENT',
    name: 'Daily Floatable FOG & Scum Mass Separated',
    symbol: 'M_fog_rem',
    unit: 'kg/day',
    datatype: 'NUMBER',
    min: 0.1,
    max: 5000,
    defaultValue: 378.0,
    designValue: 378.0,
    source: 'Q_m3d * Influent_FOG_mgL * R_fog / 1000',
    standardReference: 'Mass Balance Model',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.PRELIM.FOG.REMOVAL'],
    formulaDependencies: ['CALC-MASS_BALANCE-FOG'],
    reportSections: ['10 FOG & Grease Management'],
    boqDependencies: [],
    bimProperties: ['Pset_Skimmer.DailyScumKg'],
    scadaTags: [],
  },

  // ==========================================================================
  // PHASE 04: PRIMARY TREATMENT & CLARIFIER
  // ==========================================================================
  'STP.PRIM.CLAR.SOR_PEAK': {
    id: 'STP.PRIM.CLAR.SOR_PEAK',
    category: 'PRIMARY_TREATMENT',
    subcategory: 'PRIMARY_SEDIMENTATION',
    name: 'Peak Surface Overflow Rate (SOR)',
    symbol: 'SOR_peak',
    unit: 'm3/m2/day',
    datatype: 'NUMBER',
    min: 15,
    max: 70,
    defaultValue: 38.0,
    designValue: 38.0,
    source: 'Q_peak / Total_Clarifier_Surface_Area',
    standardReference: 'CPHEEO Section 5.3 / Metcalf & Eddy Table 5-16 (30 - 45 m3/m2/d)',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-PST-001'],
    dependencies: [],
    formulaDependencies: ['CALC-PST-DIMENSIONS', 'CALC-PST-HYDRAULICS'],
    reportSections: ['11 Primary Clarification'],
    boqDependencies: ['BOQ-CIVIL-PRIMARY_CLARIFIER'],
    bimProperties: ['Pset_Clarifier.SORPeak'],
    scadaTags: [],
  },

  'STP.PRIM.CLAR.HRT_PEAK': {
    id: 'STP.PRIM.CLAR.HRT_PEAK',
    category: 'PRIMARY_TREATMENT',
    subcategory: 'PRIMARY_SEDIMENTATION',
    name: 'Hydraulic Retention Time at Peak Flow',
    symbol: 'HRT_peak',
    unit: 'h',
    datatype: 'NUMBER',
    min: 1.0,
    max: 5.0,
    defaultValue: 2.1,
    designValue: 2.1,
    source: 'Total_Tank_Volume / (Q_peak / 24)',
    standardReference: 'CPHEEO Manual 5.3 (1.5 - 2.5 hours at peak)',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-PST-002'],
    dependencies: ['STP.PRIM.CLAR.SOR_PEAK'],
    formulaDependencies: ['CALC-PST-DIMENSIONS'],
    reportSections: ['11 Primary Clarification'],
    boqDependencies: [],
    bimProperties: ['Pset_Clarifier.HRTPeak'],
    scadaTags: [],
  },

  'STP.PRIM.CLAR.WEIR_LOADING': {
    id: 'STP.PRIM.CLAR.WEIR_LOADING',
    category: 'PRIMARY_TREATMENT',
    subcategory: 'PRIMARY_SEDIMENTATION',
    name: 'Effluent Weir Overflow Loading Rate at Peak Flow',
    symbol: 'WLR_peak',
    unit: 'm3/m/day',
    datatype: 'NUMBER',
    min: 20,
    max: 300,
    defaultValue: 155.0,
    designValue: 155.0,
    source: 'Q_peak / Total_Weir_Length',
    standardReference: 'CPHEEO / WEF MOP 8 (Max 180 - 250 m3/m/d)',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-PST-003'],
    dependencies: [],
    formulaDependencies: ['CALC-PST-WEIR_HYDRAULICS', 'CALC-PLANT-HGL'],
    reportSections: ['11 Primary Clarification', '12 Plant Hydraulics & HGL'],
    boqDependencies: ['BOQ-MECH-V_NOTCH_WEIR'],
    bimProperties: ['Pset_Clarifier.WeirLoadingRate'],
    scadaTags: [],
  },

  'STP.PRIM.CLAR.TSS_REM': {
    id: 'STP.PRIM.CLAR.TSS_REM',
    category: 'PRIMARY_TREATMENT',
    subcategory: 'PRIMARY_SEDIMENTATION',
    name: 'Primary Sedimentation TSS Removal Efficiency',
    symbol: 'R_tss_prim',
    unit: '%',
    datatype: 'NUMBER',
    min: 30,
    max: 80,
    defaultValue: 60.0,
    designValue: 60.0,
    source: 'Metcalf & Eddy Empirical Curve: R_tss = t / (a + b*t)',
    standardReference: 'Metcalf & Eddy Eq. 5-18 (50 - 70% TSS removal)',
    isRequired: true,
    isAssumed: true,
    validationRules: ['VAL-PST-004'],
    dependencies: ['STP.PRIM.CLAR.HRT_PEAK'],
    formulaDependencies: ['CALC-MASS_BALANCE-PRIMARY', 'CALC-SLUDGE-PRIMARY_YIELD'],
    reportSections: ['11 Primary Clarification', '13 Mass Balance Matrix'],
    boqDependencies: [],
    bimProperties: ['Pset_Clarifier.TSSRemovalPct'],
    scadaTags: ['AIT_PRIMARY_EFFLUENT_TSS'],
  },

  'STP.PRIM.CLAR.BOD_REM': {
    id: 'STP.PRIM.CLAR.BOD_REM',
    category: 'PRIMARY_TREATMENT',
    subcategory: 'PRIMARY_SEDIMENTATION',
    name: 'Primary Sedimentation BOD5 Removal Efficiency',
    symbol: 'R_bod_prim',
    unit: '%',
    datatype: 'NUMBER',
    min: 15,
    max: 50,
    defaultValue: 35.0,
    designValue: 35.0,
    source: 'Metcalf & Eddy Empirical Curve: R_bod = t / (a + b*t)',
    standardReference: 'Metcalf & Eddy Eq. 5-17 (25 - 40% BOD removal)',
    isRequired: true,
    isAssumed: true,
    validationRules: ['VAL-PST-005'],
    dependencies: ['STP.PRIM.CLAR.HRT_PEAK'],
    formulaDependencies: ['CALC-MASS_BALANCE-PRIMARY'],
    reportSections: ['11 Primary Clarification', '13 Mass Balance Matrix'],
    boqDependencies: [],
    bimProperties: ['Pset_Clarifier.BODRemovalPct'],
    scadaTags: ['AIT_PRIMARY_EFFLUENT_BOD'],
  },

  // ==========================================================================
  // PHASE 04: PRIMARY SLUDGE ENGINE
  // ==========================================================================
  'STP.PRIM.SLUDGE.DRY_SOLIDS': {
    id: 'STP.PRIM.SLUDGE.DRY_SOLIDS',
    category: 'PRIMARY_TREATMENT',
    subcategory: 'PRIMARY_SLUDGE',
    name: 'Primary Sludge Dry Solids Mass Production',
    symbol: 'M_ds_prim',
    unit: 'kg DS/day',
    datatype: 'NUMBER',
    min: 10,
    max: 50000,
    defaultValue: 2430.0,
    designValue: 2430.0,
    source: 'Q_avg * Influent_TSS * R_tss_prim / 1000',
    standardReference: 'Solids Mass Balance Standard',
    isRequired: true,
    isAssumed: false,
    validationRules: [],
    dependencies: ['STP.PRIM.CLAR.TSS_REM'],
    formulaDependencies: ['CALC-SLUDGE-PRIMARY_VOLUME', 'CALC-SLUDGE-DIGESTER_SIZING'],
    reportSections: ['11 Primary Clarification', '20 Sludge Treatment'],
    boqDependencies: [],
    bimProperties: ['Pset_Sludge.DrySolidsKgDay'],
    scadaTags: [],
  },

  'STP.PRIM.SLUDGE.WET_VOLUME': {
    id: 'STP.PRIM.SLUDGE.WET_VOLUME',
    category: 'PRIMARY_TREATMENT',
    subcategory: 'PRIMARY_SLUDGE',
    name: 'Primary Raw Sludge Wet Volume Withdrawal Rate',
    symbol: 'V_sludge_prim',
    unit: 'm3/day',
    datatype: 'NUMBER',
    min: 0.5,
    max: 2000,
    defaultValue: 59.3,
    designValue: 59.3,
    source: 'M_ds_prim / (rho_sludge * (SolidsConc / 100))',
    standardReference: 'Metcalf & Eddy Section 13-2 (3.0 - 5.0% solids)',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-SLUDGE-001'],
    dependencies: ['STP.PRIM.SLUDGE.DRY_SOLIDS'],
    formulaDependencies: ['CALC-SLUDGE-PRIMARY_PUMPING'],
    reportSections: ['11 Primary Clarification', '20 Sludge Treatment'],
    boqDependencies: ['BOQ-MECH-PRIMARY_SLUDGE_PUMP'],
    bimProperties: ['Pset_Sludge.DailyVolumeM3'],
    scadaTags: ['FIT_PRIMARY_SLUDGE_PUMP'],
  },

  'STP.PRIM.SLUDGE.PUMP_FLOW': {
    id: 'STP.PRIM.SLUDGE.PUMP_FLOW',
    category: 'PRIMARY_TREATMENT',
    subcategory: 'PRIMARY_SLUDGE',
    name: 'Primary Sludge Underflow Pump Design Flow Rate',
    symbol: 'Q_pump_prim_sludge',
    unit: 'm3/h',
    datatype: 'NUMBER',
    min: 1.0,
    max: 200,
    defaultValue: 45.0,
    designValue: 45.0,
    source: '(V_sludge_prim / CyclesPerDay) / (DurationMin / 60)',
    standardReference: 'Hydraulic Institute Sludge Pumping Standard',
    isRequired: true,
    isAssumed: false,
    validationRules: ['VAL-SLUDGE-002'],
    dependencies: ['STP.PRIM.SLUDGE.WET_VOLUME'],
    formulaDependencies: ['CALC-ELEC-SLUDGE_PUMP_POWER'],
    reportSections: ['11 Primary Clarification', '20 Sludge Treatment'],
    boqDependencies: ['BOQ-MECH-PRIMARY_SLUDGE_PUMP', 'BOQ-ELEC-VFD_SLUDGE'],
    bimProperties: ['Pset_Pump.SludgePumpCapacityM3h'],
    scadaTags: ['PIT_SLUDGE_DISCHARGE'],
  },
};

/**
 * Runs an automated Parameter Audit across the catalog and active project state.
 */
export function runParameterAudit(
  catalog: Record<string, ParameterDefinition> = MASTER_PARAMETER_CATALOG
): ParameterAuditReport {
  const parameters = Object.values(catalog);
  const totalParameters = parameters.length;

  let usedParameters = 0;
  let unusedParameters = 0;
  let missingUnits = 0;
  let missingFormulas = 0;
  let missingReferences = 0;

  const orphanedParameters: string[] = [];
  const details: string[] = [];

  const seenIds = new Set<string>();
  let duplicateParameters = 0;

  parameters.forEach((param) => {
    if (seenIds.has(param.id)) {
      duplicateParameters++;
      details.push(`Duplicate parameter ID found: ${param.id}`);
    } else {
      seenIds.add(param.id);
    }

    if (!param.unit || param.unit.trim() === '') {
      missingUnits++;
      details.push(`Parameter ${param.id} (${param.name}) is missing a unit.`);
    }

    if (!param.standardReference || param.standardReference.trim() === '') {
      missingReferences++;
      details.push(`Parameter ${param.id} (${param.name}) is missing a standard reference.`);
    }

    const isUsedInCalculations = param.formulaDependencies.length > 0;
    const isUsedInReport = param.reportSections.length > 0;
    const isUsedInBimOrScada = param.bimProperties.length > 0 || param.scadaTags.length > 0;

    if (isUsedInCalculations || isUsedInReport || isUsedInBimOrScada) {
      usedParameters++;
    } else {
      unusedParameters++;
      orphanedParameters.push(param.id);
      details.push(`Orphaned parameter detected (not used in formulas or reports): ${param.id}`);
    }

    if (param.isRequired && param.dependencies.length > 0 && !isUsedInCalculations) {
      missingFormulas++;
      details.push(`Required parameter ${param.id} has dependencies but no formula usage.`);
    }
  });

  const missingParameters = 0; // Baseline catalog checks

  let auditStatus: 'HEALTHY' | 'WARNINGS_FOUND' | 'CRITICAL_ERRORS' = 'HEALTHY';
  if (duplicateParameters > 0 || missingUnits > 0) {
    auditStatus = 'CRITICAL_ERRORS';
  } else if (unusedParameters > 0 || missingReferences > 0) {
    auditStatus = 'WARNINGS_FOUND';
  }

  return {
    timestamp: new Date().toISOString(),
    totalParameters,
    usedParameters,
    unusedParameters,
    missingParameters,
    duplicateParameters,
    missingUnits,
    missingFormulas,
    missingReferences,
    orphanedParameters,
    auditStatus,
    details,
  };
}
