/**
 * EVLab — Stage 05 Deep Career Mastery Service
 * Dynamically resolves and synthesizes professional learning and career content
 * for all Focus Areas across all 26 Engineering Disciplines.
 */

import { RoadmapNode } from '../types/roadmap';
import {
  Stage05MasteryRecord,
  GoverningEquation,
  InputVariable,
  SoftwareToolItem,
  StandardCodeItem,
  DetailedWorkflow,
  PracticalTask,
  DeliverableItem,
  ProjectCaseStudy,
  PortfolioProject,
  CareerRoleTarget,
  IndustryOrg,
  CoursePath,
  PluginItemRef,
  ResourceRef,
  TimelinePhase,
  CommonMistake,
  QaQcCheckItem,
  AdvancedTopicItem,
  CareerReadyCheckItem,
  GlobalRelevance,
} from '../types/stage05';

import {
  getKnowledgeItem,
  getSoftwareItem,
  getStandardItem,
  getWorkflowItem,
  getProjectItem,
  getOrganizationItem,
  getCourseItem,
  getCareerRoleItem,
  getSkillItem,
  getResourceItem,
  getPluginItem,
  getDrawingItem,
  getTemplateItem,
} from '../utils/registryLookup';

// Internal memory cache for ultra-fast instant lookups
const masteryCache: Record<string, Stage05MasteryRecord> = {};

/**
 * Standing disclaimer shown wherever Stage-05 content is displayed. This content is
 * generated by this platform from its own roadmap taxonomy and registries — it is a
 * study/reference aid, not verified labor-market research, and should not be quoted
 * as an authoritative source for salary, hiring, or timeline figures.
 */
export const STAGE05_CONTENT_DISCLAIMER =
  'This page is auto-generated study guidance from the EVLab roadmap taxonomy. Governing equations and standards references are technical facts; timelines, practice-task durations, and the Global Relevance % are indicative estimates for comparison only — always verify against current official sources before relying on them professionally.';

/**
 * Determine which of the platform's known domain categories a node belongs to, based
 * on keyword matching against its title/branch/field/specialization. Shared by the
 * equation generator and the Global Relevance scorer so both stay consistent.
 */
function detectDomainCategory(
  nodeTitle: string,
  fieldTitle: string,
  branchTitle: string,
  specTitle: string
): 'structural' | 'water' | 'power' | 'general' {
  const t = `${nodeTitle} ${specTitle} ${branchTitle} ${fieldTitle}`.toLowerCase();
  if (t.includes('concrete') || t.includes('beam') || t.includes('column') || t.includes('slab') || t.includes('foundation') || t.includes('structural')) {
    return 'structural';
  }
  if (t.includes('water') || t.includes('hydraulic') || t.includes('pipe') || t.includes('channel') || t.includes('drainage') || t.includes('fluid')) {
    return 'water';
  }
  if (t.includes('power') || t.includes('electrical') || t.includes('voltage') || t.includes('transformer') || t.includes('circuit') || t.includes('grid')) {
    return 'power';
  }
  return 'general';
}

/**
 * Global Relevance Score (0-100%) — a transparent, formula-based indicator, NOT a
 * market-research statistic. It combines:
 *   1. A base weight for the node's domain category (structural / water / power are
 *      long-standing, globally widespread infrastructure disciplines and start higher;
 *      other topics start at a moderate baseline).
 *   2. A connectivity bonus based on how many software tools, standards, projects,
 *      and career roles this platform has linked to the node — more cross-links
 *      generally means the topic is more established/central in the taxonomy.
 * The methodology is always returned in `note` so it is never mistaken for verified
 * salary or hiring data.
 */
function computeGlobalRelevance(
  nodeTitle: string,
  fieldTitle: string,
  branchTitle: string,
  specTitle: string,
  connectivityCount: number,
  seniorityBonus: number = 0
): GlobalRelevance {
  const category = detectDomainCategory(nodeTitle, fieldTitle, branchTitle, specTitle);
  const baseScore = category === 'general' ? 62 : 76;
  const connectivityBonus = Math.min(connectivityCount * 1.5, 15);
  const rawScore = baseScore + connectivityBonus + seniorityBonus;
  const score = Math.max(35, Math.min(97, Math.round(rawScore)));

  let tier: GlobalRelevance['tier'];
  if (score >= 85) tier = 'Very High';
  else if (score >= 70) tier = 'High';
  else if (score >= 55) tier = 'Moderate';
  else tier = 'Emerging';

  return {
    score,
    tier,
    note: 'Indicative estimate derived from domain classification and platform data connectivity — not sourced from a specific labor-market survey.',
  };
}

/**
 * Domain-specific equation & physics dictionary generator
 */
function getDomainEquations(
  nodeTitle: string,
  fieldTitle: string,
  branchTitle: string,
  specTitle: string
): { equations: GoverningEquation[]; variables: InputVariable[]; assumptions: string[]; outputs: string[]; validation: string[] } {
  const t = `${nodeTitle} ${specTitle} ${branchTitle} ${fieldTitle}`.toLowerCase();

  if (t.includes('concrete') || t.includes('beam') || t.includes('column') || t.includes('slab') || t.includes('foundation') || t.includes('structural')) {
    return {
      equations: [
        {
          name: 'Flexural Nominal Moment Capacity (ACI 318 / Eurocode 2)',
          formula: 'M_n = A_s · f_y · (d - a / 2), where a = (A_s · f_y) / (0.85 · f\'_c · b)',
          description: 'Calculates the ultimate bending resistance of singly reinforced concrete flexural members under factored ultimate loads.',
          variables: ['M_n', 'A_s', 'f_y', 'd', 'a', "f'_c", 'b'],
        },
        {
          name: 'Shear Strength of Concrete Section (ACI 318)',
          formula: 'V_n = V_c + V_s = 2 · λ · √(f\'_c) · b_w · d + (A_v · f_yt · d) / s',
          description: 'Evaluates the combined nominal shear capacity of the uncracked concrete web and transverse shear stirrup reinforcement.',
          variables: ['V_n', 'V_c', 'V_s', 'b_w', 'd', 'A_v', 's', 'f_yt'],
        },
        {
          name: 'Euler Critical Buckling & P-Delta Moment Magnification',
          formula: 'P_cr = (π² · E · I) / (K · L)²,  M_c = δ_ns · M_1ns + δ_s · M_1s',
          description: 'Computes stability limits and second-order geometric non-linear magnification for slender compression elements.',
          variables: ['P_cr', 'E', 'I', 'K', 'L', 'δ_ns', 'M_c'],
        },
      ],
      variables: [
        { name: 'Compressive Strength of Concrete', symbol: "f'c", unit: 'MPa (or psi)', description: '28-day cylinder standard compressive strength' },
        { name: 'Yield Strength of Reinforcing Steel', symbol: 'fy', unit: 'MPa (or ksi)', description: 'Specified minimum yield stress of rebar' },
        { name: 'Effective Member Depth', symbol: 'd', unit: 'mm (or in)', description: 'Distance from extreme compression fiber to centroid of longitudinal tension steel' },
        { name: 'Web Width', symbol: 'b / bw', unit: 'mm (or in)', description: 'Width of compression face or web thickness' },
        { name: 'Factored Design Moment', symbol: 'Mu', unit: 'kN·m (or kip-ft)', description: 'Ultimate bending moment from structural analysis load combinations' },
      ],
      assumptions: [
        'Plane sections before bending remain plane after bending (Bernoulli-Euler hypothesis).',
        'Tensile strength of concrete is neglected in ultimate flexural capacity.',
        'Maximum usable concrete strain at ultimate limit state is ε_cu = 0.003 (ACI) or 0.0035 (EC2).',
        'Perfect strain compatibility and mechanical bond between steel and surrounding concrete matrix.',
      ],
      outputs: [
        'Required longitudinal rebar area (As_req) and rebar spacing schedule',
        'Transverse shear link diameter and pitch spacing (Av/s)',
        'Deflection and serviceability crack width compliance checks (w_max ≤ 0.3 mm)',
        'Strength reduction factor ϕ / γ_m verification against code limit states',
      ],
      validation: [
        'Independent hand-calculation benchmark using strain compatibility analysis.',
        'Cross-check 3D finite element shell/frame moments with simplified 2D continuous beam tables.',
        'Equilibrium check of joint reactions against tributary static gravity loads.',
      ],
    };
  }

  if (t.includes('water') || t.includes('hydraulic') || t.includes('pipe') || t.includes('channel') || t.includes('drainage') || t.includes('fluid')) {
    return {
      equations: [
        {
          name: 'Hazen-Williams Pipe Friction Head Loss',
          formula: 'h_f = 10.67 · L · Q^1.852 / (C^1.852 · D^4.87)',
          description: 'Calculates continuous frictional head loss through pressurized water transmission pipelines.',
          variables: ['h_f', 'L', 'Q', 'C', 'D'],
        },
        {
          name: 'Manning Open Channel Discharge Equation',
          formula: 'Q = (1 / n) · A · R_h^(2/3) · S^(1/2)',
          description: 'Governs gravity flow capacity in open storm canals, culverts, and non-pressurized sewers.',
          variables: ['Q', 'n', 'A', 'R_h', 'S'],
        },
        {
          name: 'Darcy-Weisbach General Friction Formula',
          formula: 'h_f = f · (L / D) · (v² / (2 · g))',
          description: 'Fundamental fluid mechanics equation for head loss using the Colebrook-White friction factor.',
          variables: ['h_f', 'f', 'L', 'D', 'v', 'g'],
        },
      ],
      variables: [
        { name: 'Volumetric Flow Rate', symbol: 'Q', unit: 'm³/s (or L/s, MGD)', description: 'Peak design volumetric discharge or demand' },
        { name: 'Pipe Internal Diameter', symbol: 'D', unit: 'mm (or m, in)', description: 'Nominal inner diameter of fluid conduit' },
        { name: 'Frictional Roughness Coefficient', symbol: 'C / n', unit: 'dimensionless', description: 'Hazen-Williams C factor or Manning roughness coefficient n' },
        { name: 'Hydraulic Gradient / Slope', symbol: 'S', unit: 'm/m (%)', description: 'Energy slope or channel bed slope' },
        { name: 'Flow Velocity', symbol: 'v', unit: 'm/s (or ft/s)', description: 'Mean fluid velocity across the cross-sectional area' },
      ],
      assumptions: [
        'Steady, incompressible, uniform fluid flow regime.',
        'Minor losses at bends, valves, and fittings are accounted for via equivalent length or K-loss coefficients.',
        'Atmospheric pressure at free water surface for open channel conditions.',
      ],
      outputs: [
        'Hydraulic Grade Line (HGL) and Energy Grade Line (EGL) elevations',
        'Residual dynamic pressure at critical consumer nodal junctions (≥ 15-20 psi / 15-20 m)',
        'Pipe flow velocity (maintained within scouring and deposition limits: 0.6 m/s ≤ v ≤ 2.5 m/s)',
        'Water hammer / transient surge peak pressures and surge vessel sizing',
      ],
      validation: [
        'Mass conservation balance (ΣQ_in = ΣQ_out) at all network nodes.',
        'Hardy-Cross loop head loss closure check (Σh_f ≈ 0 around closed loops).',
        'EPANET / WaterCAD calibrated pressure logging comparisons with SCADA field telemetry.',
      ],
    };
  }

  if (t.includes('power') || t.includes('electrical') || t.includes('voltage') || t.includes('transformer') || t.includes('circuit') || t.includes('grid')) {
    return {
      equations: [
        {
          name: 'Three-Phase Apparent, Active & Reactive Power Equations',
          formula: 'S = √3 · V_L · I_L,  P = √3 · V_L · I_L · cos(θ),  Q = √3 · V_L · I_L · sin(θ)',
          description: 'Calculates primary power flow vector components in balanced three-phase AC power networks.',
          variables: ['S', 'P', 'Q', 'V_L', 'I_L', 'cos(θ)'],
        },
        {
          name: 'Symmetrical Fault Current (Per-Unit Impedance Method)',
          formula: 'I_sc = V_pre / (Z_thevenin + Z_fault),  I_sc(kA) = S_base / (√3 · V_base · Z_pu)',
          description: 'Evaluates maximum short-circuit interrupting duties for circuit breakers and switchgear.',
          variables: ['I_sc', 'V_pre', 'Z_thevenin', 'Z_pu', 'S_base'],
        },
        {
          name: 'Voltage Drop in Distribution Feeders',
          formula: 'ΔV ≈ √3 · I · (R · cos(θ) + X · sin(θ)) · L',
          description: 'Determines steady-state voltage drop along cable conductors and busways.',
          variables: ['ΔV', 'I', 'R', 'X', 'θ', 'L'],
        },
      ],
      variables: [
        { name: 'Line-to-Line Voltage', symbol: 'VL', unit: 'kV (or V)', description: 'Nominal operational voltage level of the system' },
        { name: 'Phase Current', symbol: 'IL', unit: 'A (or kA)', description: 'Root-mean-square (RMS) load or fault current' },
        { name: 'Power Factor', symbol: 'cos(θ)', unit: '0.0 - 1.0 (lag/lead)', description: 'Ratio of real working power to apparent power' },
        { name: 'Conductor Resistance & Reactance', symbol: 'R, X', unit: 'Ω/km', description: 'Positive sequence line impedance parameters' },
      ],
      assumptions: [
        'Balanced three-phase sinusoidal steady-state operating condition.',
        'Thermal ratings of conductors are based on standard ambient temperature and soil thermal resistivity.',
        'Sub-transient reactance (X"d) used for maximum short-circuit protection coordination.',
      ],
      outputs: [
        'Ampacity sizing and conductor cross-sectional area (mm² / AWG / kcmil)',
        'Circuit breaker short-circuit withstand and interrupting rating (kA IC)',
        'Percent voltage drop under peak load (enforcing ≤ 3% feeder, ≤ 5% overall code limits)',
        'Protective relay time-current characteristic (TCC) coordination curves',
      ],
      validation: [
        'Power balance convergence in Newton-Raphson load flow (P-Q bus tolerance < 0.001 MW).',
        'Comparison of short-circuit MVA with utility interconnect point-of-common-coupling (PCC) limits.',
        'ETAP / PSCAD transient stability simulation benchmark against IEEE 141 / 242 guidelines.',
      ],
    };
  }

  // Universal Default Engineering Mechanics & Calculation Matrix
  return {
    equations: [
      {
        name: 'Fundamental Conservation & Governing Equilibrium Relation',
        formula: 'Σ F_x = 0,  Σ F_y = 0,  Σ M_z = 0  /  dE/dt = Q_in - W_out + Σ(m·h)',
        description: 'Enforces fundamental mechanical, structural, thermodynamic, or operational equilibrium across the system control volume.',
        variables: ['F', 'M', 'E', 'Q', 'W', 'm', 'h'],
      },
      {
        name: 'Constitutive Engineering Material & Performance Equation',
        formula: 'σ = E · ε,  τ = G · γ,  Rate = (Driving Force) / (System Resistance)',
        description: 'Relates applied operational demands to internal system stresses, strains, or transfer flux rates.',
        variables: ['σ', 'E', 'ε', 'τ', 'G', 'γ'],
      },
      {
        name: 'Design Factor of Safety & Limit State Capacity Ratio',
        formula: 'DCR = (Factored Demand S_u) / (Design Resistance ϕ · R_n) ≤ 1.00',
        description: 'Verifies structural, thermal, hydraulic, or electrical safety margins under governing design standards.',
        variables: ['DCR', 'S_u', 'ϕ', 'R_n'],
      },
    ],
    variables: [
      { name: 'Applied Design Demand / Load', symbol: 'Demand (Q / P / S)', unit: 'Discipline-Specific', description: 'Peak factored operational demand or environmental load' },
      { name: 'System Capacity / Resistance', symbol: 'Resistance (Rn / Cap)', unit: 'Discipline-Specific', description: 'Nominal material or component ultimate threshold' },
      { name: 'Resistance / Safety Factor', symbol: 'ϕ / SF', unit: 'dimensionless', description: 'Code-specified safety margin factor' },
      { name: 'Material Modulus / Property', symbol: 'E / k / C', unit: 'Discipline-Specific', description: 'Governing material stiffness, conductivity, or flow factor' },
    ],
    assumptions: [
      'Linear elastic / steady-state behavior within standard operating serviceability envelopes.',
      'Homogeneous and isotropic material properties unless specifically classified as composite.',
      'Environmental boundary conditions adhere to statistical design return periods (e.g., 50-year / 100-year events).',
    ],
    outputs: [
      'Comprehensive Design Calculation Package with step-by-step mathematical proofs',
      'Demand-to-Capacity Ratios (DCR) confirming all limit states ≤ 1.00',
      'Engineered Bill of Materials (BOM) / Quantities (BOQ) with exact specifications',
      'Detailed Technical Drawings, Shop Details, and Digital CAD/BIM Assemblies',
    ],
    validation: [
      'Independent second-engineer calculation review and hand-check verification.',
      'Parametric sensitivity analysis under ±15% variation of key geotechnical/operational parameters.',
      'Code compliance cross-check against governing national and international engineering standards.',
    ],
  };
}

/**
 * Generate rich, comprehensive Stage-05 record for any Focus Area node
 */
export function getStage05MasteryRecord(
  node: RoadmapNode,
  parentPath: {
    field?: RoadmapNode;
    branch?: RoadmapNode;
    specialization?: RoadmapNode;
  }
): Stage05MasteryRecord {
  // Check memory cache
  if (masteryCache[node.id]) {
    return masteryCache[node.id];
  }

  const fieldTitle = parentPath.field?.title || 'Engineering Field';
  const branchTitle = parentPath.branch?.title || 'Engineering Branch';
  const specTitle = parentPath.specialization?.title || 'Engineering Specialization';
  const nodeTitle = node.title;
  const rel = node.relations || {};

  // Count how many registry items are actually linked to this node — used as the
  // "connectivity" input to the Global Relevance Score (see computeGlobalRelevance).
  const connectivityCount = Object.values(rel).reduce(
    (sum, list) => sum + (Array.isArray(list) ? list.length : 0),
    0
  );
  const nodeGlobalRelevance = computeGlobalRelevance(nodeTitle, fieldTitle, branchTitle, specTitle, connectivityCount);

  // 1. Resolve Software from Registry
  const softwareItems: SoftwareToolItem[] = (rel.software || []).map((id) => {
    const reg = getSoftwareItem(id);
    return {
      id,
      name: reg?.name || id.replace(/-/g, ' ').toUpperCase(),
      category: reg?.category || 'Engineering Software',
      vendor: reg?.vendor || reg?.developer || '',
      purpose: reg?.description || `Primary industry tool for ${nodeTitle} design, simulation, and analysis.`,
      proficiencyLevel: 'Essential',
      primaryWorkflow: `Used in the computational modeling, design optimization, and drafting phase of ${nodeTitle}.`,
      output: `Analytical models, calculation reports, and engineering data export files.`,
      url: reg?.url || '',
    };
  });

  // If no software in relation, supply domain-standard tools
  if (softwareItems.length === 0) {
    softwareItems.push({
      id: 'autocad',
      name: 'AutoCAD / Specialized CAD Suite',
      category: 'CAD & 2D/3D Drafting',
      vendor: 'Autodesk',
      purpose: `2D detailed engineering drafting and drawing production for ${nodeTitle}.`,
      proficiencyLevel: 'Essential',
      primaryWorkflow: 'Drafting construction drawings, details, and schematic diagrams.',
      output: 'Production DWG and PDF drawing sets.',
      url: 'https://www.autodesk.com',
    });
    softwareItems.push({
      id: 'excel-engineering',
      name: 'Mathcad / MS Excel Engineering Worksheets',
      category: 'Calculation & Computation',
      vendor: 'PTC / Microsoft',
      purpose: `Parametric design calculations, unit-checked formulas, and verification sheets for ${nodeTitle}.`,
      proficiencyLevel: 'Essential',
      primaryWorkflow: 'Preliminary sizing, code equation evaluation, and QA/QC hand-checks.',
      output: 'Formal design calculation packages and QA/QC verification spreadsheets.',
    });
  }

  // 2. Resolve Standards from Registry
  const standardItems: StandardCodeItem[] = (rel.standards || []).map((id) => {
    const reg = getStandardItem(id);
    return {
      id,
      code: reg?.code || reg?.name || id.toUpperCase(),
      name: reg?.name || id.replace(/-/g, ' ').toUpperCase(),
      organization: reg?.organization || 'Standard Regulatory Body',
      purpose: reg?.description || `Mandatory engineering design code governing ${nodeTitle} criteria and safety factors.`,
      scope: `Specifies design loads, material allowable limits, calculation methods, and construction inspection requirements.`,
    };
  });

  if (standardItems.length === 0) {
    standardItems.push({
      id: 'iso-9001-engineering',
      code: 'ISO / National Building & Engineering Code',
      name: 'International & National Engineering Design Codes',
      organization: 'ISO / National Standards Board',
      purpose: `Enforces regulatory compliance, design safety margins, and QA/QC procedures for ${nodeTitle}.`,
      scope: 'General engineering quality management, structural integrity, and statutory approval guidelines.',
    });
  }

  // 3. Resolve Workflows from Registry
  const workflowItems: DetailedWorkflow[] = (rel.workflow || []).map((id) => {
    const reg = getWorkflowItem(id);
    return {
      id,
      title: reg?.name || `${nodeTitle} Engineering Workflow`,
      summary: reg?.description || `Standard operating procedure from project inception to final deliverables.`,
      steps: [
        {
          stepNumber: 1,
          name: 'Project Inception & Design Criteria Basis',
          description: `Gather client requirements, geotechnical/site surveys, environmental criteria, and code parameters for ${nodeTitle}.`,
          toolUsed: 'Design Basis Memorandum (DBM), Excel Criteria Sheets',
          deliverable: 'Approved Design Criteria Document',
        },
        {
          stepNumber: 2,
          name: 'Preliminary Sizing & Conceptual Sizing',
          description: `Establish geometric layout, primary dimensions, and run preliminary hand-calculations.`,
          toolUsed: 'Mathcad / Hand Calculations / Preliminary CAD Layout',
          deliverable: 'Concept Design Report & General Arrangement Layout',
        },
        {
          stepNumber: 3,
          name: 'Computational Modeling & Simulation',
          description: `Build detailed 2D/3D numerical models, assign material properties, boundary supports, and load cases.`,
          toolUsed: softwareItems[0]?.name || 'Specialized Engineering Software',
          deliverable: 'Validated Numerical Model File (.etabs / .dwg / .inp)',
        },
        {
          stepNumber: 4,
          name: 'Code Compliance Analysis & Optimization',
          description: `Evaluate Demand-Capacity Ratios (DCR), serviceability limit states, and optimize cross-sections for cost and safety.`,
          toolUsed: standardItems[0]?.code || 'Governing Design Standards',
          deliverable: 'Design Verification Matrix & Stress/Capacity Logs',
        },
        {
          stepNumber: 5,
          name: 'Detailed Engineering Drawings & Detailing',
          description: `Translate analytical design into fully dimensioned, buildable construction drawings and schedules.`,
          toolUsed: 'AutoCAD / Revit / Tekla',
          deliverable: 'Detailed Engineering Drawings (DWG / PDF) with Rebar/Component Schedules',
        },
        {
          stepNumber: 6,
          name: 'Bill of Quantities (BOQ) & Technical Specifications',
          description: `Extract material takeoff quantities, formulate construction specifications (CSI Division), and estimate budget.`,
          toolUsed: 'Excel / CostX / MasterFormat Specs',
          deliverable: 'Priced BOQ and CSI Standard Technical Specifications',
        },
        {
          stepNumber: 7,
          name: 'Internal Peer Review & QA/QC Verification',
          description: `Execute four-eyes principle review, calculation spot-checking, interdisciplinary clash detection, and sign-off.`,
          toolUsed: 'QA/QC Checklist / Navisworks Clash Review',
          deliverable: 'Signed QA/QC Design Review Record',
        },
        {
          stepNumber: 8,
          name: 'Final Package Issue & Authority Approval',
          description: `Collate sealed calculations, drawing sets, and certificates for statutory authority permits and construction issue (IFC).`,
          toolUsed: 'Digital Signature / Authority Permitting Portal',
          deliverable: 'Issue For Construction (IFC) Stamped Package',
        },
      ],
    };
  });

  if (workflowItems.length === 0) {
    workflowItems.push({
      id: `${node.id}-workflow`,
      title: `${nodeTitle} Professional Engineering Workflow`,
      summary: `Standard end-to-end 8-stage industry workflow for executing ${nodeTitle} design packages.`,
      steps: [
        {
          stepNumber: 1,
          name: 'Data Collection & Design Basis',
          description: `Establish project boundary conditions, load requirements, and applicable codes for ${nodeTitle}.`,
          deliverable: 'Design Criteria Report',
        },
        {
          stepNumber: 2,
          name: 'Initial Sizing & Hand Calculations',
          description: `Compute fundamental dimensions and manual verification formulas before computer modeling.`,
          deliverable: 'Preliminary Sizing Calculation Sheet',
        },
        {
          stepNumber: 3,
          name: 'Advanced Software Modeling',
          description: `Perform detailed finite element, hydraulic, electrical, or thermal simulation.`,
          deliverable: 'Simulation Model & Output Data',
        },
        {
          stepNumber: 4,
          name: 'Standards Compliance & Safety Checks',
          description: `Check all stress, strain, deflection, voltage, or pressure values against statutory limits.`,
          deliverable: 'Code Compliance Verification Table',
        },
        {
          stepNumber: 5,
          name: 'Production of Engineering Drawings',
          description: `Produce full 2D/3D fabrication or construction drawing packages with full callouts.`,
          deliverable: 'Issued Engineering Drawings (IFC)',
        },
        {
          stepNumber: 6,
          name: 'Material Takeoff & Cost Estimation',
          description: `Generate Bill of Quantities (BOQ) and technical execution specifications.`,
          deliverable: 'BOQ & Technical Specifications',
        },
        {
          stepNumber: 7,
          name: 'QA/QC Cross-Check & Clash Detection',
          description: `Rigorous peer check of math, code references, and multi-discipline integration.`,
          deliverable: 'Signed QA/QC Verification Audit',
        },
        {
          stepNumber: 8,
          name: 'Permitting & Construction Support',
          description: `Submit for municipal/client approval and respond to construction Requests for Information (RFI).`,
          deliverable: 'Approved Permitting Package & RFI Log',
        },
      ],
    });
  }

  // 4. Resolve Projects from Registry
  const projectItems: ProjectCaseStudy[] = (rel.projects || []).map((id) => {
    const reg = getProjectItem(id);
    return {
      id,
      name: reg?.name || id.replace(/-/g, ' ').toUpperCase(),
      client: reg?.client || 'Infrastructure & Industry Client',
      location: reg?.location || 'Major Infrastructure Project',
      sector: reg?.category || 'Engineering Infrastructure',
      relevance: reg?.description || `Real-world application demonstrating advanced ${nodeTitle} design principles in action.`,
      engineerRole: `Lead ${branchTitle} Engineer responsible for analysis, modeling, and construction drawing production.`,
      challenge: `Managing complex boundary conditions, aggressive timeline constraints, and stringent code compliance criteria.`,
      deliverables: [
        'Complete Design Calculation Package (150+ pages)',
        '3D BIM / Analytical Model Repository',
        'Issue For Construction (IFC) Drawing Set',
      ],
    };
  });

  if (projectItems.length === 0) {
    projectItems.push({
      id: `${node.id}-flagship-case`,
      name: `Major Regional ${nodeTitle} Implementation Project`,
      client: 'Government Authority / Private Industrial Developer',
      location: 'National / International Infrastructure Corridor',
      sector: fieldTitle,
      relevance: `Comprehensive real-world engineering project showing standard industrial execution of ${nodeTitle}.`,
      engineerRole: `Lead Design Engineer & Technical Modeler for ${nodeTitle}.`,
      challenge: `Balancing strict budget constraints with high-durability performance and strict environmental sustainability standards.`,
      deliverables: [
        'Detailed Engineering Design Report & Calculations',
        'AutoCAD / Revit Complete Construction Drawings',
        'Technical Specifications and Bill of Quantities (BOQ)',
        'Authority Permitting Approval Dossier',
      ],
    });
  }

  // 5. Resolve Career Roles from Registry
  const careerRoleItems: CareerRoleTarget[] = (rel.careerRoles || []).map((id) => {
    const reg = getCareerRoleItem(id);
    return {
      id,
      title: reg?.name || id.replace(/-/g, ' ').toUpperCase(),
      demand: 'High',
      experienceLevel: '2 - 8 Years Professional Experience',
      responsibilities: [
        `Lead calculation and modeling workflows for ${nodeTitle}.`,
        `Produce and review engineering drawings, schedules, and technical memorandums.`,
        `Coordinate with multi-disciplinary engineering teams, clients, and contractors.`,
        `Enforce quality control, code compliance, and safety standards across all deliverables.`,
      ],
      globalRelevance: computeGlobalRelevance(nodeTitle, fieldTitle, branchTitle, specTitle, connectivityCount),
    };
  });

  if (careerRoleItems.length === 0) {
    careerRoleItems.push({
      id: `${node.id}-lead-engineer`,
      title: `${branchTitle} Design Engineer`,
      demand: 'High',
      experienceLevel: '3 - 6 Years',
      responsibilities: [
        `Perform advanced engineering calculations and computer simulations for ${nodeTitle}.`,
        `Develop detailed construction drawings, material specifications, and tender documents.`,
        `Conduct site inspections and address site RFIs during the construction/commissioning phase.`,
      ],
      globalRelevance: computeGlobalRelevance(nodeTitle, fieldTitle, branchTitle, specTitle, connectivityCount),
    });
    careerRoleItems.push({
      id: `${node.id}-specialist-consultant`,
      title: `Senior ${nodeTitle} Specialist`,
      demand: 'Very High',
      experienceLevel: '7+ Years',
      responsibilities: [
        `Act as technical authority and signing engineer (PE / CEng) for complex ${nodeTitle} schemes.`,
        `Direct junior engineers and oversee high-risk design verification audits.`,
        `Interface directly with clients, regulatory agencies, and forensic review boards.`,
      ],
      globalRelevance: computeGlobalRelevance(nodeTitle, fieldTitle, branchTitle, specTitle, connectivityCount, 6),
    });
  }

  // 6. Resolve Organizations from Registry
  const orgItems: IndustryOrg[] = (rel.organizations || []).map((id) => {
    const reg = getOrganizationItem(id);
    return {
      id,
      name: reg?.name || id.replace(/-/g, ' ').toUpperCase(),
      type: reg?.type || 'Professional Engineering Society',
      certifications: 'PE / CEng / Professional Certification Tracks',
      role: reg?.description || `Authoritative body governing codes, certifications, and technical conferences for ${fieldTitle}.`,
    };
  });

  if (orgItems.length === 0) {
    orgItems.push({
      id: 'org-not-yet-linked',
      name: `No specific professional body linked yet for ${fieldTitle}`,
      type: 'Reference Suggestion',
      certifications: 'Look up your national/regional engineering licensing board (e.g. PE, CEng, or local equivalent) for accurate requirements.',
      role: `This platform has not yet linked a verified professional society for ${nodeTitle}. Search for the recognized engineering institution in your country that governs ${fieldTitle}, rather than assuming one from this placeholder.`,
    });
  }

  // 7. Resolve Courses from Registry
  const courseItems: CoursePath[] = (rel.courses || []).map((id) => {
    const reg = getCourseItem(id);
    return {
      id,
      title: reg?.name || id.replace(/-/g, ' ').toUpperCase(),
      provider: reg?.provider || 'EVLab Engineering Academy',
      level: 'Intermediate to Advanced',
      duration: '6 - 10 Weeks (Self-Paced with Practical Labs)',
      url: reg?.url || '',
    };
  });

  if (courseItems.length === 0) {
    courseItems.push({
      id: `${node.id}-mastery-course`,
      title: `Mastering ${nodeTitle}: From Theory to Industrial Practice`,
      provider: 'EVLab Deep Career Mastery Track',
      level: 'Comprehensive (Beginner to Professional)',
      duration: '8 Weeks (40 Hours of Practical Labs)',
    });
  }

  // 8. Resolve Resources from Registry
  const resourceItems: ResourceRef[] = (rel.resources || []).map((id) => {
    const reg = getResourceItem(id);
    return {
      id,
      title: reg?.name || id.replace(/-/g, ' ').toUpperCase(),
      type: reg?.category || 'Technical Reference Manual',
      author: 'Industry Technical Committee',
      description: reg?.description || `Authoritative engineering design guide and handbook for ${nodeTitle}.`,
    };
  });

  if (resourceItems.length === 0) {
    resourceItems.push({
      id: `${node.id}-design-handbook`,
      title: `Recommended: search for a current standard engineering handbook covering ${nodeTitle}`,
      type: 'Reference Suggestion',
      author: 'No specific title linked yet in this platform\'s registry',
      description: `No specific reference is registered for ${nodeTitle} yet. Look up a current edition handbook or textbook for ${branchTitle} from a recognized technical publisher, or your local engineering institution's reading list, rather than relying on this placeholder.`,
    });
  }

  // 9. Domain Equations & Physical Variables
  const domainCalc = getDomainEquations(nodeTitle, fieldTitle, branchTitle, specTitle);

  // 10. Construct Full 27-Section Mastery Record
  const record: Stage05MasteryRecord = {
    focusAreaId: node.id,
    title: nodeTitle,
    fieldTitle,
    branchTitle,
    specializationTitle: specTitle,

    globalRelevance: nodeGlobalRelevance,
    contentDisclaimer: STAGE05_CONTENT_DISCLAIMER,

    // Section 1: Overview
    overview: {
      whatItIs: `${nodeTitle} is a core engineering discipline area within ${specTitle} (${branchTitle}), focusing on the analytical evaluation, mathematical modeling, code-compliant design, and practical execution of specialized engineering systems.`,
      whyItMatters: `Mastery of ${nodeTitle} is essential for ensuring safety, economic efficiency, statutory compliance, and long-term durability of infrastructure, industrial assets, and technological systems. Errors in this domain can lead to severe operational failures, financial penalties, or catastrophic structural collapse.`,
      whereItFits: `It operates at the intersection of ${branchTitle} and multi-disciplinary engineering design, serving as the critical bridge between theoretical physics/mechanics and buildable construction/manufacturing documentation.`,
      relatedDisciplines: [fieldTitle, branchTitle, 'Quality Assurance & Control', 'Project Management', 'Computational Modeling'],
      projectContext: `In real-world project lifecycles, ${nodeTitle} activities occur during the Detailed Engineering Design (DED) and Pre-Construction phases, directly driving the production of calculations, drawings, BIM models, and technical specifications.`,
      professionalImportance: `High industry demand exists for practicing engineers who possess verified competence in ${nodeTitle}, combining hand-calculation fundamentals with advanced computer-aided simulation tools.`,
    },

    // Section 2: Prerequisites
    prerequisites: {
      mathScience: [
        'Multivariable Calculus & Differential Equations (ODE / PDE)',
        'Linear Algebra & Numerical Methods (Matrix Operations, Iterative Solvers)',
        'Engineering Physics (Statics, Dynamics, Thermodynamics, or Electromagnetics)',
      ],
      coreMechanics: [
        'Mechanics of Materials / Continuum Mechanics (Stress-Strain Tensors, Mohr Circle)',
        'Structural / Fluid / Thermal / Electrical Circuit Analysis Fundamentals',
        'Material Science & Degradation Mechanisms (Corrosion, Fatigue, Creep)',
      ],
      codingAndSoftware: [
        'Parametric Spreadsheet Modeling (Advanced Excel / VBA Formulas)',
        'Engineering Scripting Fundamentals (Python / MATLAB for data processing)',
        'Computer-Aided Design (CAD) 2D/3D Interface Navigation',
      ],
      priorTopics: [
        `${fieldTitle} Fundamentals`,
        `${branchTitle} Principles`,
        `${specTitle} Core Methodologies`,
      ],
    },

    // Section 3: Learning Objectives
    learningObjectives: [
      `Formulate and execute rigorous, code-compliant design calculations for ${nodeTitle} without software dependency.`,
      `Construct, parameterize, and run 2D/3D numerical models in industry-standard software tools (${softwareItems.map((s) => s.name).join(', ')}).`,
      `Interpret, apply, and cross-reference governing design standards (${standardItems.map((s) => s.code).join(', ')}) to verify limit states.`,
      `Produce complete engineering deliverable packages comprising calculation sheets, CAD drawings, schedules, and BOQs.`,
      `Perform comprehensive QA/QC design verification, clash detection, and peer-review audits on ${nodeTitle} submittals.`,
      `Communicate technical engineering decisions, safety trade-offs, and cost-optimizations effectively to clients and contractors.`,
    ],

    // Section 4: Knowledge Matrix
    knowledgeMatrix: {
      foundation: [
        'Fundamental laws of physics, conservation of mass, energy, and momentum',
        'Coordinate systems, vector mechanics, and free-body diagram equilibrium',
        'Units of measurement, dimensional consistency, and conversion standards (SI vs Imperial)',
      ],
      coreEngineering: [
        `Core theoretical governing principles of ${nodeTitle}`,
        'Material constitutive models, stress-strain behavior, and elastic-plastic thresholds',
        'Load paths, boundary conditions, support fixities, and constraint definitions',
      ],
      appliedConcepts: [
        'Serviceability Limit States (SLS) vs Ultimate Limit States (ULS) design philosophies',
        'Environmental loading factors (wind, seismic, thermal, hydro, fatigue, dynamic vibration)',
        'Standard detailing rules, minimum reinforcement/clearances, and constructability constraints',
      ],
      advancedConcepts: [
        'Non-linear material and geometric behavior (P-Delta, large displacements, plasticity)',
        'Dynamic modal analysis, response spectrum methods, and transient fluid/electrical surges',
        'Parametric optimization algorithms and automated generative design workflows',
      ],
      calculationsTheory: [
        'Manual closed-form analytical solutions and derivation of governing formulas',
        'Energy methods (Castigliano theorem, virtual work principle) and stiffness matrix formulations',
        'Statistical safety margins, resistance reduction factors, and partial safety factors',
      ],
      designCodes: [
        `Prescriptive vs performance-based design requirements in ${standardItems.map((s) => s.code).join(', ')}`,
        'Mandatory inspection, testing tolerances, and material certification standards',
        'Regional annexes, local building bye-laws, and statutory approval protocols',
      ],
    },

    // Section 5: Skills Matrix
    skillsMatrix: {
      beginner: [
        'Reading and interpreting complex 2D/3D engineering drawings and schematics',
        'Executing basic manual sizing calculations and checking physical units',
        'Navigating CAD/BIM software viewports and querying object properties',
      ],
      intermediate: [
        'Building full analytical models in specialized computational software',
        'Assigning complex multi-combination load cases and interpreting contour plots',
        'Drafting detailed engineering details, schedules, and technical memorandums',
      ],
      advanced: [
        'Conducting non-linear, dynamic, or multi-physics simulations with mesh convergence studies',
        'Authoring bespoke calculation templates in Python, Mathcad, or Excel with VBA automation',
        'Resolving complex multidisciplinary engineering clashes and constructability disputes',
      ],
      professional: [
        'Signing off on high-consequence engineering design packages as Responsible Engineer (PE/CEng)',
        'Leading forensic failure investigations, root-cause analyses, and expert witness reviews',
        'Optimizing project lifecycle capital expenditure (CAPEX) and operational efficiency (OPEX)',
      ],
    },

    // Section 6: Calculation Competencies
    calculationCompetencies: {
      governingEquations: domainCalc.equations,
      inputVariables: domainCalc.variables,
      assumptions: domainCalc.assumptions,
      outputs: domainCalc.outputs,
      validationMethods: domainCalc.validation,
    },

    // Section 7: Software Tools
    software: softwareItems,

    // Section 8: Standards & Codes
    standards: standardItems,

    // Section 9: Professional Workflows
    workflows: workflowItems,

    // Section 10: Practical Work
    practicalWork: [
      {
        task: `Perform initial manual sizing and design verification for a representative ${nodeTitle} system under governing loads.`,
        output: 'Structured, unit-checked calculation spreadsheet (PDF / Excel).',
        tools: ['Mathcad', 'Excel', 'Drafting Sketchpad'],
        difficulty: 'Beginner',
        duration: '4 - 6 Hours',
      },
      {
        task: `Construct a full 3D analytical model in ${softwareItems[0]?.name || 'Specialized Software'}, apply code load combinations, and extract design stresses/deflections.`,
        output: 'Complete simulation file (.model) and 20-page analytical report.',
        tools: [softwareItems[0]?.name || 'Analysis Software', 'Excel'],
        difficulty: 'Intermediate',
        duration: '12 - 16 Hours',
      },
      {
        task: `Draft a full construction drawing sheet (Plan, Elevation, Section, Details, and Schedule) in AutoCAD/Revit adhering to ISO/AIA standards.`,
        output: 'Production-ready DWG drawing set and plotting PDF.',
        tools: ['AutoCAD', 'Revit'],
        difficulty: 'Intermediate',
        duration: '8 - 12 Hours',
      },
      {
        task: `Perform comprehensive multi-disciplinary clash detection, QA/QC audit, and value-engineering optimization on an existing ${nodeTitle} design package.`,
        output: 'Formal QA/QC Review Memorandum and Value Engineering Log.',
        tools: ['Navisworks / BIM 360', 'Bluebeam Revu', 'Excel'],
        difficulty: 'Advanced',
        duration: '10 - 15 Hours',
      },
    ],

    // Section 11: Engineering Deliverables
    deliverables: [
      {
        category: 'Calculations',
        item: 'Design Calculation Package (DCP)',
        format: 'PDF (100+ pages) + Mathcad / Excel source',
        description: 'Comprehensive step-by-step mathematical calculations covering all load cases, limit states, and safety checks.',
      },
      {
        category: 'Drawings',
        item: 'Issue For Construction (IFC) Drawing Set',
        format: 'AutoCAD DWG + Vector PDF (A1 / ANSI D)',
        description: 'Fully dimensioned plans, elevations, cross-sections, connection details, and material schedules.',
      },
      {
        category: 'Digital Models',
        item: 'BIM / Finite Element Analytical Model',
        format: 'Native software file (.etabs, .rvt, .dwg, .inp)',
        description: 'Coordinated 3D digital model with embedded engineering metadata and property attributes.',
      },
      {
        category: 'Specifications',
        item: 'Technical Specifications (CSI Division Format)',
        format: 'MS Word / PDF',
        description: 'Prescriptive material requirements, installation procedures, quality tolerances, and testing protocols.',
      },
      {
        category: 'Procurement',
        item: 'Bill of Quantities (BOQ) & Material Takeoff',
        format: 'Excel / CostX Spreadsheets',
        description: 'Itemized material quantities, unit rates, and cost estimates categorized by trade code.',
      },
      {
        category: 'Reports',
        item: 'Design Basis Memorandum & Executive Summary',
        format: 'PDF',
        description: 'High-level synthesis outlining project criteria, governing codes, assumptions, and key conclusions.',
      },
    ],

    // Section 12: Real Projects / Case Studies
    projects: projectItems,

    // Section 13: Practice Exercises
    practiceExercises: {
      beginner: [
        `Hand-calculate the primary capacity and required dimensions of a standard ${nodeTitle} component using closed-form code formulas.`,
        'Draw an accurate Free Body Diagram (FBD) detailing all applied forces, reaction moments, and boundary constraints.',
        'Extract and interpret material properties (Young modulus, yield strength, allowable stress) from standard code tables.',
      ],
      intermediate: [
        `Build a 2D/3D numerical model of ${nodeTitle}, apply combined dead, live, wind, and seismic loads, and verify equilibrium.`,
        'Generate an automated parametric design sheet in Excel with formula validation, dropdown selectors, and conditional formatting.',
        'Produce an A1-sized construction detail drawing in AutoCAD with proper lineweights, dimensioning styles, and callout leaders.',
      ],
      advanced: [
        `Perform non-linear P-Delta or dynamic response spectrum analysis on an irregular ${nodeTitle} geometry and evaluate drift ratios.`,
        'Design connection details and interface transitions between different materials (e.g., steel-to-concrete, pipe-to-pump, cable-to-busway).',
        'Execute a full interdisciplinary coordination review and resolve geometric clashes using Navisworks.',
      ],
      professional: [
        `Conduct a comprehensive peer-review audit of an external design submittal, identifying code violations and mathematical errors.`,
        'Formulate a Value Engineering (VE) proposal that reduces material usage or cost while still satisfying all safety and performance requirements.',
        'Author an emergency forensic failure mitigation memo proposing urgent structural/operational remediation measures.',
      ],
    },

    // Section 14: Portfolio Projects
    portfolioProjects: [
      {
        title: `Comprehensive Industrial ${nodeTitle} Design & Analysis Package`,
        objective: `Demonstrate end-to-end professional design competence by taking a complex ${nodeTitle} project from architectural concept to stamped construction drawings.`,
        scope: `Complete structural/mechanical/electrical modeling, code compliance analysis under extreme environmental loads, drawing production, and BOQ estimation.`,
        inputs: ['Architectural / Process Flow Drawings', 'Geotechnical / Environmental Site Report', 'Governing Code Parameters'],
        tools: [softwareItems[0]?.name || 'Analysis Software', 'AutoCAD / Revit', 'Excel / Mathcad', 'Bluebeam Revu'],
        deliverables: [
          'Full 80-Page Design Calculation Package with manual hand-checks',
          '3D Coordinated Analytical and BIM Model Repository',
          'Complete 12-Sheet Construction Drawing Set (IFC Quality)',
          'Priced Bill of Quantities (BOQ) and CSI Technical Specifications',
        ],
        validation: 'Benchmarked against independent hand-calculations and 3D finite element equilibrium checks, with all discrepancies investigated and resolved.',
        interviewPitch: `In this project, I took full ownership of the ${nodeTitle} engineering design, optimizing the design for material efficiency while satisfying all ${standardItems[0]?.code || 'code'} limit states under extreme load combinations. (Use your own project's real figures here when presenting this portfolio piece.)`,
      },
      {
        title: `Parametric Automation & Computational Workflow for ${nodeTitle}`,
        objective: `Develop an automated Python/Dynamo script that generates geometries, evaluates design equations, and formats deliverables automatically.`,
        scope: `Algorithm development, API integration with CAD/simulation software, and automated batch generation of design verification reports.`,
        inputs: ['Parametric input tables (dimensions, material grades, load factors)'],
        tools: ['Python', 'OpenPyXL / Pandas', softwareItems[0]?.name || 'CAD API'],
        deliverables: [
          'Clean, open-source Python automation tool with GUI / CLI',
          'Comparative benchmarking study comparing manual vs automated calculation speeds',
          'Automated PDF report generator producing stamped-ready calculation sheets',
        ],
        validation: 'Rigorous unit tests matching official code benchmark problems, with results cross-checked against known solutions.',
        interviewPitch: `To eliminate repetitive manual calculations, I authored a modular automation pipeline that meaningfully cut calculation turnaround time while eliminating transcription errors. (Use your own measured turnaround-time figures here when presenting this portfolio piece.)`,
      },
    ],

    // Section 15: Career Roles
    careerRoles: careerRoleItems,

    // Section 16: Industry Organizations
    organizations: orgItems,

    // Section 17: Courses / Learning Paths
    courses: courseItems,

    // Section 18: Plugins / Tools
    plugins: (rel.plugins || []).map((id) => {
      const reg = getPluginItem(id);
      return {
        id,
        name: reg?.name || id.replace(/-/g, ' ').toUpperCase(),
        hostSoftware: reg?.hostSoftware || [softwareItems[0]?.name || 'CAD Suite'],
        purpose: reg?.description || `Productivity and computational script add-on for ${nodeTitle}.`,
      };
    }),

    // Section 19: Drawings & Templates
    drawingsAndTemplates: [
      {
        name: `Standard ${nodeTitle} Construction Drawing Sheet (Plan, Elevation & Details)`,
        type: 'Drawing',
        format: 'DWG / PDF (A1 Size)',
        description: 'Standardized drawing layout template featuring title block, coordinate grids, dimension styles, and standard notes.',
      },
      {
        name: `${nodeTitle} Design Calculation Spreadsheet (Automated Formula Engine)`,
        type: 'Template',
        format: 'MS Excel (.xlsx) / Mathcad (.mcdx)',
        description: 'Pre-formatted, peer-verified engineering calculation template with automatic code equation checking and unit validation.',
      },
      {
        name: `Master CSI Technical Specification Section for ${nodeTitle}`,
        type: 'Specification',
        format: 'MS Word (.docx)',
        description: 'Three-part CSI MasterFormat specification covering Products, Materials, Execution, and Quality Control.',
      },
    ],

    // Section 20: Resources & References
    resources: resourceItems,

    // Section 21: UELE Connections
    ueleConnection: {
      objectId: node.ueleLink || '',
      objectName: node.ueleLink ? `${nodeTitle} 3D Model` : undefined,
      world: 'Ultimate Engineering Learning Ecosystem (UELE)',
      what: `Interactive 3D digital model showing full spatial geometry, internal components, and material assemblies for ${nodeTitle}.`,
      why: `Allows engineers to explore realistic structural joints, mechanical assemblies, flow paths, and constructability details in a dynamic 3D viewport.`,
      howToInspect: `Launch the UELE 3D Viewer to rotate, explode components, inspect cross-sections, and view real-time engineering telemetry.`,
      isAvailable: Boolean(node.ueleLink),
    },

    // Section 22: Career Mastery Timeline
    timeline: [
      {
        phase: 1,
        name: 'Theoretical Foundations & Physics Principles',
        duration: 'Weeks 1 - 4',
        focus: `Master the mathematical derivations, constitutive equations, and physical governing laws of ${nodeTitle}.`,
        milestone: 'Pass theoretical foundation assessment with 100% derivation accuracy.',
        deliverables: ['Hand-written formula derivation notebook', 'Solved fundamental textbook problem set (25 problems)'],
      },
      {
        phase: 2,
        name: 'Design Codes, Standards & Manual Calculations',
        duration: 'Weeks 5 - 8',
        focus: `Deep-dive into ${standardItems.map((s) => s.code).join(', ')} limit state criteria and author manual calculation templates.`,
        milestone: 'Complete end-to-end manual calculation package for a real-world building/component.',
        deliverables: ['Verified Excel / Mathcad parametric calculation sheet', 'Code comparison matrix'],
      },
      {
        phase: 3,
        name: 'Computational Modeling & Simulation Mastery',
        duration: 'Weeks 9 - 14',
        focus: `Gain expert proficiency in ${softwareItems.map((s) => s.name).join(', ')}, building, analyzing, and optimizing 3D models.`,
        milestone: 'Construct full 3D simulation model and achieve < 3% variance against hand-checks.',
        deliverables: ['Validated 3D model repository', 'Comprehensive finite element / simulation report'],
      },
      {
        phase: 4,
        name: 'Detailed Drawings, Specifications & Deliverables',
        duration: 'Weeks 15 - 18',
        focus: `Translate analytical designs into complete, buildable CAD/BIM drawings, BOQs, and CSI specifications.`,
        milestone: 'Publish complete, stamped-quality 10-sheet drawing package ready for construction.',
        deliverables: ['Full IFC drawing package (DWG & PDF)', 'Priced Bill of Quantities and Technical Specs'],
      },
      {
        phase: 5,
        name: 'Professional Portfolio & Industry Readiness',
        duration: 'Weeks 19 - 24',
        focus: `Complete flagship capstone portfolio project, conduct peer-review audits, and practice technical interview defenses.`,
        milestone: 'Launch public engineering portfolio and achieve career-ready certification.',
        deliverables: ['Polished Capstone Portfolio Dossier', 'Signed QA/QC Verification Audit Record'],
      },
    ],

    // Section 23: Job Market / Industry Relevance
    jobMarket: {
      roles: careerRoleItems.map((r) => r.title),
      targetIndustries: [
        'Civil & Infrastructure Consulting Firms (AECOM, WSP, Jacobs, Arup)',
        'Engineering, Procurement & Construction (EPC) Contractors',
        'Heavy Industrial & Manufacturing Facilities',
        'Government Infrastructure & Public Works Departments',
        'Specialized Engineering Consultancies & Forensic Labs',
      ],
      marketDemand: nodeGlobalRelevance.tier === 'Emerging' ? 'Moderate' : nodeGlobalRelevance.tier,
      seniorityRange: 'Entry-Level Graduate (0-2 yrs) → Senior Lead (5-10 yrs) → Principal Director (10+ yrs)',
      globalRelevance: nodeGlobalRelevance,
      topHiringSectors: [
        'Urban Infrastructure & High-Rise Construction',
        'Energy, Power Grid & Renewable Transition Projects',
        'Transportation Corridors (Bridges, Highways, Rail & Aviation)',
        'Water Resources, Treatment Plants & Environmental Works',
      ],
    },

    // Section 24: Common Mistakes
    commonMistakes: [
      {
        mistake: 'Blind Software Trust without Hand-Calculation Verification',
        consequence: 'Modeling errors, incorrect units, or flawed boundary fixities go unnoticed, leading to catastrophic under-design.',
        prevention: 'Always execute independent 2D hand-calculations to verify total reactions and critical peak moments within ±10% before accepting software outputs.',
      },
      {
        mistake: 'Improper Boundary Condition & Support Fixity Assumptions',
        consequence: 'Assigning rigid fixed supports to flexible foundation soils creates artificially high moments and unrealistic stress distribution.',
        prevention: 'Model realistic spring stiffness values (subgrade modulus) or conservative pin/roller releases matching actual site connection details.',
      },
      {
        mistake: 'Neglecting Secondary Stresses & Non-Linear Effects (P-Delta / Thermal)',
        consequence: 'Slender structural members experience unexpected lateral-torsional or second-order buckling failure during peak design loads.',
        prevention: 'Always activate geometric non-linear (P-Delta / large displacement) options and enforce code slenderness limits (Kl/r).',
      },
      {
        mistake: 'Overlooking Constructability & Rebar / Conduit Congestion',
        consequence: 'Theoretical design cannot physically be poured or assembled on-site, causing massive construction delays, honeycombing, and rework.',
        prevention: 'Review 3D BIM clash models and verify clear spacing between rebar/cables meets code aggregate and clearance minimums.',
      },
      {
        mistake: 'Inadequate Load Combination Factors & Reversal Checks',
        consequence: 'Failure under wind uplift, buoyancy, or seismic reversal because net downward gravity stabilization was overestimated.',
        prevention: 'Enforce all mandatory code load combinations including counteracting minimum dead load cases (e.g., 0.9D + 1.0W or 0.9D + 1.0E).',
      },
    ],

    // Section 25: QA/QC Checklist
    qaQcChecklist: [
      {
        id: 'qa-01',
        category: 'Inputs & Design Basis',
        checkItem: 'Design Basis Memorandum (DBM) is fully approved by client and Lead Engineer, referencing current applicable code editions.',
        standardRef: standardItems[0]?.code || 'ISO 9001',
      },
      {
        id: 'qa-02',
        category: 'Equilibrium & Statics',
        checkItem: 'Global equilibrium check: Sum of vertical applied loads equals total foundation reaction within < 0.5% margin of error.',
        standardRef: 'Fundamental Statics',
      },
      {
        id: 'qa-03',
        category: 'Material Properties',
        checkItem: 'Material yield strengths, concrete compressive strengths, elastic moduli, and unit weights match geotechnical/project specifications exactly.',
        standardRef: 'ASTM / EN Material Standards',
      },
      {
        id: 'qa-04',
        category: 'Serviceability & Deflection',
        checkItem: 'Maximum operational deflections, vibrations, crack widths, and drift ratios satisfy strict serviceability limits (e.g., L/360 or H/500).',
        standardRef: standardItems[0]?.code || 'Code SLS Limits',
      },
      {
        id: 'qa-05',
        category: 'Drawing & Model Coordination',
        checkItem: 'All dimensions, section marks, and rebar/component schedules on 2D drawings match 3D analytical model outputs without discrepancies.',
        standardRef: 'AIA CAD / ISO 19650 BIM',
      },
      {
        id: 'qa-06',
        category: 'Peer Review & Sign-Off',
        checkItem: 'Four-eyes independent peer review completed by qualified Professional Engineer (PE/CEng) with all review comments resolved and logged.',
        standardRef: 'Professional Engineering Board Ethics',
      },
    ],

    // Section 26: Advanced Topics
    advancedTopics: [
      {
        topic: `Generative Design & Automated Algorithmic Optimization in ${nodeTitle}`,
        description: 'Using evolutionary algorithms, Grasshopper, and Python to generate hundreds of topologically optimized design variants based on minimum weight and carbon footprint.',
        industryImpact: 'Reduces raw material consumption by up to 25% while speeding up conceptual design cycles from weeks to hours.',
      },
      {
        topic: `Digital Twins & Real-Time IoT Structural Health Monitoring (SHM)`,
        description: 'Connecting physical sensors (strain gauges, accelerometers, flow meters) on operational infrastructure directly to real-time 3D finite element digital twins.',
        industryImpact: 'Enables predictive maintenance, fatigue life estimation, and immediate post-disaster structural integrity assessments.',
      },
      {
        topic: `Embodied Carbon Accounting & Circular Engineering in ${nodeTitle}`,
        description: 'Integrating Life Cycle Assessment (LCA) tools to calculate total kilograms of CO2-equivalent per unit of engineered system.',
        industryImpact: 'Directly complies with net-zero sustainability mandates and green building certification systems (LEED, BREEAM).',
      },
    ],

    // Section 27: Career-Ready Checklist
    careerReadyChecklist: [
      {
        id: 'cr-01',
        category: 'Calculations & Hand-Checks',
        statement: `I can formulate and solve complete, code-compliant design calculations for ${nodeTitle} from first principles without relying on computer software.`,
      },
      {
        id: 'cr-02',
        category: 'Software & Computational Modeling',
        statement: `I can construct, parameterize, and debug 2D/3D numerical models in ${softwareItems[0]?.name || 'industry software'}, verifying results against manual hand-calculations.`,
      },
      {
        id: 'cr-03',
        category: 'Codes & Regulatory Standards',
        statement: `I can navigate and cross-reference governing engineering codes (${standardItems.map((s) => s.code).join(', ')}) to justify all design assumptions and limit state checks.`,
      },
      {
        id: 'cr-04',
        category: 'Engineering Drawings & Detailing',
        statement: `I can draft, detail, and check production-ready 2D CAD and 3D BIM drawings that meet constructability tolerances and industry drafting standards.`,
      },
      {
        id: 'cr-05',
        category: 'Deliverables & Documentation',
        statement: `I can assemble a professional, client-ready Design Calculation Package, technical specification section, and Bill of Quantities (BOQ).`,
      },
      {
        id: 'cr-06',
        category: 'QA/QC & Peer Review',
        statement: `I can perform a thorough QA/QC peer-review on another engineer's submittal, systematically catching boundary errors, formula slips, and code violations.`,
      },
      {
        id: 'cr-07',
        category: 'Portfolio & Interview Defense',
        statement: `I have a completed capstone portfolio project demonstrating ${nodeTitle} mastery and can defend my design decisions during technical hiring interviews.`,
      },
    ],
  };

  // Cache record
  masteryCache[node.id] = record;
  return record;
}
