/**
 * EVL WTP Engineering Suite - Master Design Alternatives Registry (Phase 13)
 * Centralized registry for all process technology alternatives across WTP process units.
 */

export type ProcessCategory = 
  | 'AERATION'
  | 'COAGULATION'
  | 'FLOCCULATION'
  | 'SEDIMENTATION'
  | 'FILTRATION'
  | 'DISINFECTION'
  | 'INTAKE'
  | 'PUMPING'
  | 'SLUDGE_THICKENING'
  | 'SLUDGE_DEWATERING'
  | 'CWR_STORAGE'
  | 'ELECTRICAL_SYSTEM';

export type LandRequirement = 'Very Low' | 'Low' | 'Medium' | 'High' | 'Very High';
export type EnergyRequirement = 'Very Low' | 'Low' | 'Medium' | 'High' | 'Very High';
export type ChemicalRequirement = 'None' | 'Low' | 'Medium' | 'High';
export type OperationalComplexity = 'Very Low' | 'Low' | 'Medium' | 'High' | 'Very High';
export type MaintenanceRequirement = 'Low' | 'Medium' | 'High';
export type AutomationRequirement = 'Basic' | 'Moderate' | 'Advanced' | 'Fully Automated';
export type SludgeGeneration = 'None' | 'Low' | 'Medium' | 'High';

export interface ApplicableWaterQuality {
  minTurbidity?: number;
  maxTurbidity?: number;
  minFeMn?: number;
  maxFeMn?: number;
  minTDS?: number;
  maxTDS?: number;
  maxAlgae?: number;
  maxTOC?: number;
  minUVT?: number;
}

export interface ApplicableFlowRange {
  minFlowMLD: number;
  maxFlowMLD: number;
}

export interface DesignAlternative {
  alternativeId: string;
  processId: ProcessCategory;
  category: string;
  name: string;
  shortDescription: string;
  detailedDescription: string;
  applicableWaterQuality: ApplicableWaterQuality;
  applicableFlowRange: ApplicableFlowRange;
  minimumFlow: number;
  maximumFlow: number;
  hydraulicRequirement: string;
  landRequirement: LandRequirement;
  landAreaFactor: number; // Multiplier relative to baseline (e.g. 1.0 = baseline, 0.35 = 65% land saved)
  energyRequirement: EnergyRequirement;
  chemicalRequirement: ChemicalRequirement;
  operationalComplexity: OperationalComplexity;
  maintenanceRequirement: MaintenanceRequirement;
  automationRequirement: AutomationRequirement;
  sludgeGeneration: SludgeGeneration;
  treatmentEfficiency: number; // 0 - 100
  reliability: number; // 0 - 100
  expandability: number; // 0 - 100
  constructability: number; // 0 - 100
  climateSuitability: string;
  BangladeshSuitability: string;
  capitalCostFactor: number; // Relative CAPEX factor (1.0 = baseline)
  operatingCostFactor: number; // Relative OPEX factor (1.0 = baseline)
  lifecycleCostFactor: number; // Relative 30-yr LCCA factor
  footprintFactor: number; // Relative footprint factor
  advantages: string[];
  disadvantages: string[];
  limitations: string[];
  requiredParameters: string[];
  optionalParameters: string[];
  dependentProcesses: string[];
  incompatibleProcesses: string[];
  recommendedWhen: string[];
  avoidWhen: string[];
  standards: string[];
  formulas: string[];
  designEngine: string;
  status: 'ACTIVE' | 'EXPERIMENTAL' | 'DEPRECATED';
}

export const DESIGN_ALTERNATIVES_REGISTRY: DesignAlternative[] = [
  // ==========================================
  // 1. AERATION ALTERNATIVES
  // ==========================================
  {
    alternativeId: 'AER-001',
    processId: 'AERATION',
    category: 'Gravity Aeration',
    name: 'Cascade Aerator',
    shortDescription: 'Multi-tiered concrete step cascade providing natural gravity oxygenation.',
    detailedDescription: 'Gravity flow cascade steps promote air-water contact for CO2 gas stripping, hydrogen sulfide reduction, and iron/manganese oxidation without electrical power consumption.',
    applicableWaterQuality: { minFeMn: 0.3, maxTurbidity: 2000 },
    applicableFlowRange: { minFlowMLD: 1, maxFlowMLD: 500 },
    minimumFlow: 1,
    maximumFlow: 500,
    hydraulicRequirement: '1.5m to 2.5m hydraulic drop required',
    landRequirement: 'Medium',
    landAreaFactor: 1.0,
    energyRequirement: 'Very Low',
    chemicalRequirement: 'None',
    operationalComplexity: 'Very Low',
    maintenanceRequirement: 'Low',
    automationRequirement: 'Basic',
    sludgeGeneration: 'None',
    treatmentEfficiency: 85,
    reliability: 98,
    expandability: 80,
    constructability: 95,
    climateSuitability: 'Ideal for tropical, humid environments with high raw water CO2 or dissolved Fe/Mn.',
    BangladeshSuitability: 'High - Extremely popular in DPHE/WASA projects due to zero energy and low maintenance.',
    capitalCostFactor: 1.0,
    operatingCostFactor: 0.1,
    lifecycleCostFactor: 0.8,
    footprintFactor: 1.0,
    advantages: ['Zero electrical power consumption', 'No moving mechanical parts', 'Extremely reliable', 'Simple civil construction'],
    disadvantages: ['Requires 1.5-2.5m hydraulic head drop', 'Algal growth potential on exposed steps', 'Fixed oxygenation rate'],
    limitations: ['Cannot handle volatile organic compounds requiring high air-to-water ratios'],
    requiredParameters: ['Fe_raw', 'Mn_raw', 'pH_raw', 'Q_m3hr'],
    optionalParameters: ['CO2_raw', 'H2S_raw'],
    dependentProcesses: ['Coagulation', 'Sedimentation'],
    incompatibleProcesses: [],
    recommendedWhen: ['Fe/Mn > 0.3 mg/L', 'Sufficient elevation drop available', 'Zero energy OPEX prioritized'],
    avoidWhen: ['Site is completely flat without pumping elevation', 'VOC contamination present'],
    standards: ['CPHEEO 2021 Vol I Sec 5.2', 'AWWA M51'],
    formulas: ['Loading = Q / (pi * R^2)', 'Step height = Total drop / N_steps'],
    designEngine: 'processDesignEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'AER-002',
    processId: 'AERATION',
    category: 'Mechanical Aeration',
    name: 'Diffused Air Aeration',
    shortDescription: 'Submerged fine/coarse bubble air diffusers powered by motor blowers.',
    detailedDescription: 'Motor-driven air blowers inject pressurized air through fine bubble diffusers at the bottom of an aeration basin, offering precise dissolved oxygen control.',
    applicableWaterQuality: { minFeMn: 0.5, maxTurbidity: 1000 },
    applicableFlowRange: { minFlowMLD: 5, maxFlowMLD: 300 },
    minimumFlow: 5,
    maximumFlow: 300,
    hydraulicRequirement: '0.3m hydraulic drop',
    landRequirement: 'Low',
    landAreaFactor: 0.5,
    energyRequirement: 'High',
    chemicalRequirement: 'None',
    operationalComplexity: 'Medium',
    maintenanceRequirement: 'Medium',
    automationRequirement: 'Moderate',
    sludgeGeneration: 'None',
    treatmentEfficiency: 92,
    reliability: 88,
    expandability: 90,
    constructability: 85,
    climateSuitability: 'Suitable for all climates with indoor/sheltered blower housing.',
    BangladeshSuitability: 'Medium - Requires reliable electricity and blower maintenance.',
    capitalCostFactor: 1.4,
    operatingCostFactor: 2.2,
    lifecycleCostFactor: 1.6,
    footprintFactor: 0.5,
    advantages: ['Compact footprint', 'Adjustable air-to-water ratio', 'Minimal hydraulic headloss'],
    disadvantages: ['Continuous electrical power demand', 'Blower noise', 'Diffuser clogging over time'],
    limitations: ['Requires reliable continuous power supply'],
    requiredParameters: ['Fe_raw', 'Mn_raw', 'Q_m3hr'],
    optionalParameters: ['DO_raw'],
    dependentProcesses: ['Clarification'],
    incompatibleProcesses: [],
    recommendedWhen: ['Land footprint is strictly constrained', 'Raw water Fe/Mn > 2.0 mg/L'],
    avoidWhen: ['Power supply is unstable', 'OPEX budget is minimal'],
    standards: ['WEF Manual of Practice 8', 'CPHEEO 2021'],
    formulas: ['Airflow = Q * A_ratio', 'Blower Power = (Q_air * P) / (3600 * eta)'],
    designEngine: 'processDesignEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'AER-003',
    processId: 'AERATION',
    category: 'Packed Media',
    name: 'Packed Tower Aerator',
    shortDescription: 'Counter-current air-water tower packed with high surface plastic media.',
    detailedDescription: 'Water trickles down over structured plastic packing while air is blown upwards, providing maximum gas transfer efficiency for CO2 stripping and VOC removal.',
    applicableWaterQuality: { maxTurbidity: 50 },
    applicableFlowRange: { minFlowMLD: 2, maxFlowMLD: 100 },
    minimumFlow: 2,
    maximumFlow: 100,
    hydraulicRequirement: '3.0m to 5.0m tower height',
    landRequirement: 'Very Low',
    landAreaFactor: 0.25,
    energyRequirement: 'High',
    chemicalRequirement: 'None',
    operationalComplexity: 'High',
    maintenanceRequirement: 'High',
    automationRequirement: 'Advanced',
    sludgeGeneration: 'None',
    treatmentEfficiency: 98,
    reliability: 85,
    expandability: 75,
    constructability: 75,
    climateSuitability: 'Indoor or protected outdoor installation.',
    BangladeshSuitability: 'Low - High risk of packing fouling if raw water turbidity exceeds 50 NTU.',
    capitalCostFactor: 1.8,
    operatingCostFactor: 2.5,
    lifecycleCostFactor: 2.0,
    footprintFactor: 0.25,
    advantages: ['Extremely compact footprint', 'Highest gas transfer efficiency (>95%)', 'Superior CO2 and VOC removal'],
    disadvantages: ['High capital cost', 'Media fouling if turbidity is high', 'Requires pre-filtration if water is turbid'],
    limitations: ['Raw water turbidity must be < 50 NTU to avoid biofouling/clogging'],
    requiredParameters: ['CO2_raw', 'VOC_raw', 'Q_m3hr'],
    optionalParameters: [],
    dependentProcesses: ['Filtration'],
    incompatibleProcesses: [],
    recommendedWhen: ['High CO2 (>30 mg/L) or VOC stripping needed on low-turbidity groundwater'],
    avoidWhen: ['Raw surface water turbidity > 50 NTU'],
    standards: ['AWWA B100', 'USEPA Design Manual'],
    formulas: ['Tower Area = Q / Loading_rate', 'Packing Height = HTU * NTU'],
    designEngine: 'processDesignEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'AER-000',
    processId: 'AERATION',
    category: 'Bypass',
    name: 'Not Required / Bypass Aeration',
    shortDescription: 'Aeration process bypassed completely.',
    detailedDescription: 'Raw water flows directly to Coagulation/Flash Mixing without prior aeration step.',
    applicableWaterQuality: { maxFeMn: 0.3 },
    applicableFlowRange: { minFlowMLD: 0.1, maxFlowMLD: 1000 },
    minimumFlow: 0.1,
    maximumFlow: 1000,
    hydraulicRequirement: '0m',
    landRequirement: 'Very Low',
    landAreaFactor: 0.0,
    energyRequirement: 'Very Low',
    chemicalRequirement: 'None',
    operationalComplexity: 'Very Low',
    maintenanceRequirement: 'Low',
    automationRequirement: 'Basic',
    sludgeGeneration: 'None',
    treatmentEfficiency: 0,
    reliability: 100,
    expandability: 100,
    constructability: 100,
    climateSuitability: 'Universal',
    BangladeshSuitability: 'Applicable when raw water Fe < 0.3 mg/L and DO > 5.0 mg/L.',
    capitalCostFactor: 0.0,
    operatingCostFactor: 0.0,
    lifecycleCostFactor: 0.0,
    footprintFactor: 0.0,
    advantages: ['Eliminates civil structure and hydraulic drop', 'Zero CAPEX and OPEX'],
    disadvantages: ['No Fe/Mn pre-oxidation or gas stripping'],
    limitations: ['Unsuitable if Fe/Mn > 0.3 mg/L or CO2 > 20 mg/L'],
    requiredParameters: [],
    optionalParameters: [],
    dependentProcesses: [],
    incompatibleProcesses: [],
    recommendedWhen: ['Dissolved Oxygen > 6 mg/L and Iron/Manganese < 0.3 mg/L'],
    avoidWhen: ['Raw water Iron > 0.3 mg/L or H2S present'],
    standards: ['CPHEEO 2021'],
    formulas: [],
    designEngine: 'processDesignEngine.ts',
    status: 'ACTIVE'
  },

  // ==========================================
  // 2. COAGULATION / RAPID MIXING ALTERNATIVES
  // ==========================================
  {
    alternativeId: 'COA-001',
    processId: 'COAGULATION',
    category: 'Hydraulic Mixing',
    name: 'Hydraulic Flash Mixer',
    shortDescription: 'Square/circular chamber with hydraulic jump weir providing rapid G-value turbulence.',
    detailedDescription: 'Hydraulic head drop over a sharp-crested weir creates intense localized turbulence (G = 700 - 1000 s^-1) for instant coagulant dispersion without electrical drive.',
    applicableWaterQuality: { minTurbidity: 10, maxTurbidity: 3000 },
    applicableFlowRange: { minFlowMLD: 1, maxFlowMLD: 300 },
    minimumFlow: 1,
    maximumFlow: 300,
    hydraulicRequirement: '0.4m to 0.8m headloss across weir',
    landRequirement: 'Low',
    landAreaFactor: 0.8,
    energyRequirement: 'Very Low',
    chemicalRequirement: 'Medium',
    operationalComplexity: 'Very Low',
    maintenanceRequirement: 'Low',
    automationRequirement: 'Basic',
    sludgeGeneration: 'Low',
    treatmentEfficiency: 88,
    reliability: 95,
    expandability: 80,
    constructability: 95,
    climateSuitability: 'Universal',
    BangladeshSuitability: 'High - Zero power requirement and rugged civil construction.',
    capitalCostFactor: 0.9,
    operatingCostFactor: 0.2,
    lifecycleCostFactor: 0.7,
    footprintFactor: 0.8,
    advantages: ['No electrical motor or mechanical drive', 'Zero power cost', 'Simple maintenance'],
    disadvantages: ['G-value varies with flow variations', 'Requires 0.5m hydraulic drop'],
    limitations: ['Less flexible under wide flow turn-down ratios (>3:1)'],
    requiredParameters: ['Q_m3hr', 'alumDoseMgL'],
    optionalParameters: [],
    dependentProcesses: ['Flocculation'],
    incompatibleProcesses: [],
    recommendedWhen: ['Stable raw water flow and zero electricity preference'],
    avoidWhen: ['Plant flow turns down by > 60% dynamically'],
    standards: ['CPHEEO 2021 Vol I Sec 5.3', 'AWWA M37'],
    formulas: ['P = rho * g * Q * h_loss', 'G = sqrt(P / (mu * V))'],
    designEngine: 'processDesignEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'COA-002',
    processId: 'COAGULATION',
    category: 'Mechanical Mixing',
    name: 'Mechanical Rapid Mixer',
    shortDescription: 'Motorized high-speed impeller shaft mixer in a dedicated concrete tank.',
    detailedDescription: 'High-speed turbine/radial impeller provides controllable mixing intensity (G = 600 - 1000 s^-1) independent of plant flow fluctuations.',
    applicableWaterQuality: { minTurbidity: 5, maxTurbidity: 5000 },
    applicableFlowRange: { minFlowMLD: 5, maxFlowMLD: 500 },
    minimumFlow: 5,
    maximumFlow: 500,
    hydraulicRequirement: '0.1m headloss',
    landRequirement: 'Low',
    landAreaFactor: 1.0,
    energyRequirement: 'Medium',
    chemicalRequirement: 'Medium',
    operationalComplexity: 'Medium',
    maintenanceRequirement: 'Medium',
    automationRequirement: 'Moderate',
    sludgeGeneration: 'Low',
    treatmentEfficiency: 95,
    reliability: 90,
    expandability: 90,
    constructability: 90,
    climateSuitability: 'Universal',
    BangladeshSuitability: 'High - Standard design across major WASA surface water plants.',
    capitalCostFactor: 1.0,
    operatingCostFactor: 1.0,
    lifecycleCostFactor: 1.0,
    footprintFactor: 1.0,
    advantages: ['Constant G-value regardless of flow rate', 'Minimal hydraulic headloss (0.1m)', 'Precise mixing power tuning'],
    disadvantages: ['Requires continuous electrical power', 'Mechanical gearbox and shaft maintenance'],
    limitations: ['Requires standby motor drive unit'],
    requiredParameters: ['Q_m3hr', 'flashMixerDetentionSec', 'flashMixerG'],
    optionalParameters: [],
    dependentProcesses: ['Flocculation'],
    incompatibleProcesses: [],
    recommendedWhen: ['Flow rate varies significantly during seasonal operations'],
    avoidWhen: ['Unreliable site power supply without backup'],
    standards: ['AWWA M37', 'CPHEEO 2021'],
    formulas: ['Power Kw = (G^2 * mu * V) / 1000', 'Detention t = V / Q'],
    designEngine: 'processDesignEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'COA-003',
    processId: 'COAGULATION',
    category: 'In-line Mixing',
    name: 'In-Line Static Mixer',
    shortDescription: 'Pipeline section containing stationary helical mixing element blades.',
    detailedDescription: 'Chemical coagulant is injected immediately upstream of static internal baffles inside the raw water pipe, generating high-shear rapid mixing in under 2 seconds.',
    applicableWaterQuality: { minTurbidity: 5, maxTurbidity: 1000 },
    applicableFlowRange: { minFlowMLD: 10, maxFlowMLD: 300 },
    minimumFlow: 10,
    maximumFlow: 300,
    hydraulicRequirement: '0.3m to 0.6m pipe friction loss',
    landRequirement: 'Very Low',
    landAreaFactor: 0.1,
    energyRequirement: 'Very Low',
    chemicalRequirement: 'Low',
    operationalComplexity: 'Very Low',
    maintenanceRequirement: 'Low',
    automationRequirement: 'Advanced',
    sludgeGeneration: 'Low',
    treatmentEfficiency: 92,
    reliability: 96,
    expandability: 80,
    constructability: 95,
    climateSuitability: 'Universal',
    BangladeshSuitability: 'Medium - Great for space-constrained urban plant retrofits.',
    capitalCostFactor: 0.7,
    operatingCostFactor: 0.1,
    lifecycleCostFactor: 0.5,
    footprintFactor: 0.1,
    advantages: ['Zero footprint required (installed in pipe)', 'Instantaneous mixing (< 2 seconds)', 'No moving mechanical parts'],
    disadvantages: ['Headloss increases with square of velocity', 'Fixed element geometry'],
    limitations: ['Requires minimum pipe velocity > 1.2 m/s'],
    requiredParameters: ['pipeDiameterDN', 'Q_m3hr'],
    optionalParameters: [],
    dependentProcesses: ['Flocculation'],
    incompatibleProcesses: [],
    recommendedWhen: ['Plant footprint is extremely constrained', 'Existing pipe retrofit'],
    avoidWhen: ['Pipe velocity < 0.8 m/s'],
    standards: ['AWWA M37'],
    formulas: ['Headloss h = K * v^2 / 2g', 'G = sqrt(g * h / (nu * t))'],
    designEngine: 'processDesignEngine.ts',
    status: 'ACTIVE'
  },

  // ==========================================
  // 3. FLOCCULATION ALTERNATIVES
  // ==========================================
  {
    alternativeId: 'FLO-001',
    processId: 'FLOCCULATION',
    category: 'Hydraulic Baffled',
    name: 'Baffled Channel Hydraulic Flocculator',
    shortDescription: 'Around-the-end or over-and-under concrete channel baffles creating tapered G-values.',
    detailedDescription: 'Water flows through a serpentine maze of concrete baffles where channel width expands progressively to create tapered velocity gradients (G = 50 -> 20 s^-1) without electrical power.',
    applicableWaterQuality: { minTurbidity: 10, maxTurbidity: 3000 },
    applicableFlowRange: { minFlowMLD: 2, maxFlowMLD: 150 },
    minimumFlow: 2,
    maximumFlow: 150,
    hydraulicRequirement: '0.6m to 1.2m headloss',
    landRequirement: 'High',
    landAreaFactor: 1.5,
    energyRequirement: 'Very Low',
    chemicalRequirement: 'Medium',
    operationalComplexity: 'Very Low',
    maintenanceRequirement: 'Low',
    automationRequirement: 'Basic',
    sludgeGeneration: 'Medium',
    treatmentEfficiency: 86,
    reliability: 98,
    expandability: 70,
    constructability: 90,
    climateSuitability: 'Universal',
    BangladeshSuitability: 'High - Traditional design with zero mechanical components.',
    capitalCostFactor: 1.1,
    operatingCostFactor: 0.1,
    lifecycleCostFactor: 0.8,
    footprintFactor: 1.5,
    advantages: ['Zero electrical power demand', 'No mechanical shafts or gearboxes', 'Bulletproof reliability'],
    disadvantages: ['Large civil footprint required', 'Fixed baffle geometry cannot adapt to flow changes'],
    limitations: ['Flocculation detention time decreases linearly at higher flows'],
    requiredParameters: ['Q_m3hr', 'flocculatorDetentionMin'],
    optionalParameters: [],
    dependentProcesses: ['Sedimentation'],
    incompatibleProcesses: [],
    recommendedWhen: ['Land availability is high and electrical power is expensive/unreliable'],
    avoidWhen: ['Site footprint is constrained'],
    standards: ['CPHEEO 2021 Vol I Sec 5.4'],
    formulas: ['V = Q * t_detention', 'G_tapered = sqrt(rho * g * h / (mu * t))'],
    designEngine: 'processDesignEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'FLO-002',
    processId: 'FLOCCULATION',
    category: 'Mechanical Paddle',
    name: 'Mechanical Paddle Flocculator',
    shortDescription: 'Multi-stage horizontal or vertical shaft rotating paddle wheels.',
    detailedDescription: 'Slow-rotating paddle wheels in 3 to 4 sequential stages deliver precise tapered velocity gradients (G1 = 60, G2 = 40, G3 = 20 s^-1) for optimal pin-floc growth.',
    applicableWaterQuality: { minTurbidity: 5, maxTurbidity: 5000 },
    applicableFlowRange: { minFlowMLD: 5, maxFlowMLD: 500 },
    minimumFlow: 5,
    maximumFlow: 500,
    hydraulicRequirement: '0.15m to 0.3m headloss',
    landRequirement: 'Medium',
    landAreaFactor: 1.0,
    energyRequirement: 'Low',
    chemicalRequirement: 'Medium',
    operationalComplexity: 'Medium',
    maintenanceRequirement: 'Medium',
    automationRequirement: 'Moderate',
    sludgeGeneration: 'Medium',
    treatmentEfficiency: 95,
    reliability: 92,
    expandability: 85,
    constructability: 88,
    climateSuitability: 'Universal',
    BangladeshSuitability: 'High - Industry standard for municipal WTPs above 20 MLD.',
    capitalCostFactor: 1.0,
    operatingCostFactor: 1.0,
    lifecycleCostFactor: 1.0,
    footprintFactor: 1.0,
    advantages: ['Optimal tapered velocity gradient control', 'Handles seasonal turbidity fluctuations easily', 'Low hydraulic headloss'],
    disadvantages: ['Submerged bearings and shaft seal maintenance', 'Requires mechanical drives'],
    limitations: ['Paddle tip velocity must remain < 0.6 m/s to prevent floc shear'],
    requiredParameters: ['Q_m3hr', 'flocculatorDetentionMin', 'flocculatorBasins'],
    optionalParameters: [],
    dependentProcesses: ['Sedimentation'],
    incompatibleProcesses: [],
    recommendedWhen: ['High clarification efficiency and controlled floc growth required'],
    avoidWhen: ['Submerged mechanical maintenance capability is lacking'],
    standards: ['AWWA M37', 'CPHEEO 2021'],
    formulas: ['Power = 0.5 * C_d * rho * A_paddle * v_relative^3', 'G = sqrt(P / (mu * V))'],
    designEngine: 'processDesignEngine.ts',
    status: 'ACTIVE'
  },

  // ==========================================
  // 4. SEDIMENTATION / CLARIFICATION ALTERNATIVES
  // ==========================================
  {
    alternativeId: 'SED-001',
    processId: 'SEDIMENTATION',
    category: 'Conventional Gravity',
    name: 'Conventional Rectangular Sedimentation',
    shortDescription: 'Long rectangular concrete settling basins with mechanical bridge sludge scrapers.',
    detailedDescription: 'Gravity settling basin operating at conservative Surface Overflow Rates (SOR = 15 - 25 m^3/m^2/day) providing 2.0 - 4.0 hours detention time for robust solids removal.',
    applicableWaterQuality: { minTurbidity: 10, maxTurbidity: 5000 },
    applicableFlowRange: { minFlowMLD: 5, maxFlowMLD: 500 },
    minimumFlow: 5,
    maximumFlow: 500,
    hydraulicRequirement: '0.3m to 0.5m weir drop',
    landRequirement: 'Very High',
    landAreaFactor: 1.0, // Baseline = 1.0
    energyRequirement: 'Low',
    chemicalRequirement: 'Medium',
    operationalComplexity: 'Low',
    maintenanceRequirement: 'Low',
    automationRequirement: 'Basic',
    sludgeGeneration: 'High',
    treatmentEfficiency: 88,
    reliability: 98,
    expandability: 80,
    constructability: 95,
    climateSuitability: 'Ideal for tropical regions; open basins allow easy visual inspection.',
    BangladeshSuitability: 'High - Extremely durable civil structure used across 80% of DPHE/WASA plants.',
    capitalCostFactor: 1.0,
    operatingCostFactor: 1.0,
    lifecycleCostFactor: 1.0,
    footprintFactor: 1.0,
    advantages: ['Extremely stable under massive turbidity spikes (up to 5000 NTU)', 'Simple operation and low maintenance', 'High sludge holding capacity'],
    disadvantages: ['Very large land footprint required', 'High civil concrete volume and initial CAPEX', 'Longer detention time'],
    limitations: ['Requires significant available site area'],
    requiredParameters: ['clarifierPlanAreaM2', 'clarifierSOR', 'Q_m3hr'],
    optionalParameters: [],
    dependentProcesses: ['Filtration'],
    incompatibleProcesses: [],
    recommendedWhen: ['Site land is abundant', 'Raw water experiences extreme monsoon turbidity spikes'],
    avoidWhen: ['Site footprint is constrained or land cost is exorbitant'],
    standards: ['CPHEEO 2021 Vol I Sec 5.5', 'AWWA M37'],
    formulas: ['Area = Q / SOR', 'Detention t = Volume / Q'],
    designEngine: 'processDesignEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'SED-002',
    processId: 'SEDIMENTATION',
    category: 'High-Rate Inclined Settler',
    name: 'Lamella Plate Settler',
    shortDescription: 'Inclined parallel plate packs (60 deg angle) reducing footprint by 65%.',
    detailedDescription: 'Inclined stainless steel/FRP lamella plates spaced at 50mm gaps dramatically increase effective settling surface area, allowing high SOR (120 - 180 m^3/m^2/day) in a compact footprint.',
    applicableWaterQuality: { minTurbidity: 10, maxTurbidity: 2000 },
    applicableFlowRange: { minFlowMLD: 5, maxFlowMLD: 400 },
    minimumFlow: 5,
    maximumFlow: 400,
    hydraulicRequirement: '0.4m to 0.7m weir drop',
    landRequirement: 'Low',
    landAreaFactor: 0.35, // 65% land saved!
    energyRequirement: 'Low',
    chemicalRequirement: 'Medium',
    operationalComplexity: 'Medium',
    maintenanceRequirement: 'Medium',
    automationRequirement: 'Moderate',
    sludgeGeneration: 'High',
    treatmentEfficiency: 94,
    reliability: 92,
    expandability: 95,
    constructability: 88,
    climateSuitability: 'Universal',
    BangladeshSuitability: 'High - Gold standard for urban WASA plants in Dhaka and Chittagong.',
    capitalCostFactor: 1.2,
    operatingCostFactor: 1.1,
    lifecycleCostFactor: 0.9,
    footprintFactor: 0.35,
    advantages: ['Saves 60-70% civil land footprint', 'Rapid response time (< 45 min detention)', 'High settled water quality (< 3 NTU)'],
    disadvantages: ['Requires periodic plate cleaning/hose-down to prevent mudballing', 'Plate pack replacement cost after 15 years'],
    limitations: ['Algal growth on plates if exposed to direct intense sunlight without covers'],
    requiredParameters: ['clarifierPlanAreaM2', 'clarifierSOR', 'lamellaPlateAngleDeg'],
    optionalParameters: [],
    dependentProcesses: ['Filtration'],
    incompatibleProcesses: [],
    recommendedWhen: ['Site land is constrained', 'Modern compact WTP layout desired'],
    avoidWhen: ['Raw water turbidity > 3000 NTU continuously without presedimentation'],
    standards: ['CPHEEO 2021', 'AWWA M37'],
    formulas: ['Effective Area = Plan Area * (cos theta + L/w * sin theta)', 'SOR_projected = Q / Projected_Area'],
    designEngine: 'processDesignEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'SED-003',
    processId: 'SEDIMENTATION',
    category: 'High-Rate Tube Settler',
    name: 'Tube Settler Basin',
    shortDescription: 'Chevron/honeycomb PVC tube modules inclined at 60 degrees.',
    detailedDescription: 'Plastic tube settler modules installed in the top portion of a settling basin shorten the vertical settling distance of flocs to 50mm, enabling 2x to 3x higher overflow rates than conventional tanks.',
    applicableWaterQuality: { minTurbidity: 10, maxTurbidity: 1500 },
    applicableFlowRange: { minFlowMLD: 2, maxFlowMLD: 300 },
    minimumFlow: 2,
    maximumFlow: 300,
    hydraulicRequirement: '0.3m headloss',
    landRequirement: 'Low',
    landAreaFactor: 0.45,
    energyRequirement: 'Low',
    chemicalRequirement: 'Medium',
    operationalComplexity: 'Low',
    maintenanceRequirement: 'Medium',
    automationRequirement: 'Basic',
    sludgeGeneration: 'Medium',
    treatmentEfficiency: 92,
    reliability: 90,
    expandability: 90,
    constructability: 92,
    climateSuitability: 'Universal',
    BangladeshSuitability: 'High - Excellent for upgrading existing conventional basins.',
    capitalCostFactor: 1.05,
    operatingCostFactor: 0.95,
    lifecycleCostFactor: 0.88,
    footprintFactor: 0.45,
    advantages: ['Saves 50-55% land footprint', 'Easy retrofit into existing rectangular basins', 'Cost-effective PVC media'],
    disadvantages: ['Tube modules can become brittle under UV sunlight', 'Requires pressure washing during turnarounds'],
    limitations: ['Requires protective UV cover or dark basin housing'],
    requiredParameters: ['clarifierPlanAreaM2', 'Q_m3hr'],
    optionalParameters: [],
    dependentProcesses: ['Filtration'],
    incompatibleProcesses: [],
    recommendedWhen: ['Upgrading existing WTP capacity without buying new land'],
    avoidWhen: ['Basin is exposed to intense UV without cover'],
    standards: ['CPHEEO 2021', 'AWWA M37'],
    formulas: ['Effective Area = Plan Area * Sin(60)', 'SOR = Q / Area_effective'],
    designEngine: 'processDesignEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'SED-004',
    processId: 'SEDIMENTATION',
    category: 'Flotation Clarification',
    name: 'Dissolved Air Flotation (DAF)',
    shortDescription: 'Micro-air bubble flotation for low-density solids, algae, and organic removal.',
    detailedDescription: 'Pressurized recycle water saturated with air is released into the contact zone, creating 10-100 micron air bubbles that attach to flocs and float them rapidly to the surface for skimming.',
    applicableWaterQuality: { maxTurbidity: 100, maxAlgae: 50000 },
    applicableFlowRange: { minFlowMLD: 5, maxFlowMLD: 200 },
    minimumFlow: 5,
    maximumFlow: 200,
    hydraulicRequirement: '0.2m headloss',
    landRequirement: 'Very Low',
    landAreaFactor: 0.2,
    energyRequirement: 'High',
    chemicalRequirement: 'High',
    operationalComplexity: 'High',
    maintenanceRequirement: 'High',
    automationRequirement: 'Advanced',
    sludgeGeneration: 'Low',
    treatmentEfficiency: 96,
    reliability: 88,
    expandability: 92,
    constructability: 82,
    climateSuitability: 'Ideal for reservoirs subject to seasonal toxic cyanobacteria / algal blooms.',
    BangladeshSuitability: 'Medium - Superior for surface water sources impacted by industrial organics or algal blooms (e.g. Buriganga / Shitalakhya).',
    capitalCostFactor: 1.6,
    operatingCostFactor: 2.1,
    lifecycleCostFactor: 1.7,
    footprintFactor: 0.2,
    advantages: ['85-90% footprint reduction compared to conventional', 'Unrivaled algae (>98%) and low-density floc removal', 'Produces drier floated sludge (3-5% solids)'],
    disadvantages: ['High electrical energy consumption for recycle pumps and air compressors', 'Higher mechanical complexity'],
    limitations: ['Unsuitable for heavy mineral silt/sand turbidity > 200 NTU'],
    requiredParameters: ['algaeCount', 'Q_m3hr', 'recycleRatioPct'],
    optionalParameters: [],
    dependentProcesses: ['Filtration'],
    incompatibleProcesses: [],
    recommendedWhen: ['Raw water has severe algal blooms, low turbidity, or color/organics'],
    avoidWhen: ['Raw water contains heavy river silt or turbidity > 300 NTU'],
    standards: ['AWWA Manual M48', 'CPHEEO 2021'],
    formulas: ['Recycle Ratio R = (A/S) * Q_air', 'Loading Rate = 10 to 20 m/h'],
    designEngine: 'processDesignEngine.ts',
    status: 'ACTIVE'
  },

  // ==========================================
  // 5. FILTRATION ALTERNATIVES
  // ==========================================
  {
    alternativeId: 'FIL-001',
    processId: 'FILTRATION',
    category: 'Rapid Gravity',
    name: 'Rapid Sand Filter (Single Media)',
    shortDescription: 'Single silica sand bed with underdrain air/water backwash.',
    detailedDescription: 'Classic rapid gravity filter containing 600-700mm silica sand (effective size 0.55mm, UC 1.35) operating at 5.0 - 7.5 m/hr filtration rates with backwash washwater troughs.',
    applicableWaterQuality: { maxTurbidity: 20 },
    applicableFlowRange: { minFlowMLD: 2, maxFlowMLD: 500 },
    minimumFlow: 2,
    maximumFlow: 500,
    hydraulicRequirement: '1.2m to 2.0m total filter headloss',
    landRequirement: 'Medium',
    landAreaFactor: 1.0,
    energyRequirement: 'Low',
    chemicalRequirement: 'Low',
    operationalComplexity: 'Low',
    maintenanceRequirement: 'Low',
    automationRequirement: 'Moderate',
    sludgeGeneration: 'Medium',
    treatmentEfficiency: 92,
    reliability: 98,
    expandability: 85,
    constructability: 95,
    climateSuitability: 'Universal',
    BangladeshSuitability: 'High - Benchmark standard across 100% of municipal surface water treatment plants.',
    capitalCostFactor: 1.0,
    operatingCostFactor: 1.0,
    lifecycleCostFactor: 1.0,
    footprintFactor: 1.0,
    advantages: ['Proven long-term operational record', 'Simple media sourcing (locally available graded silica sand)', 'High mechanical reliability'],
    disadvantages: ['Filter run time limited to 24-36 hrs under moderate turbidity', 'Surface straining prone to mudballing if air scour is inadequate'],
    limitations: ['Settled water turbidity entering filters must be < 10 NTU'],
    requiredParameters: ['numberOfFilters', 'filtrationRateM3M2Hr', 'Q_m3hr'],
    optionalParameters: [],
    dependentProcesses: ['Disinfection'],
    incompatibleProcesses: [],
    recommendedWhen: ['Standard municipal WTP with local material sourcing preference'],
    avoidWhen: ['Ultra-high filtration rates (>12 m/h) are desired'],
    standards: ['CPHEEO 2021 Vol I Sec 5.6', 'AWWA B100'],
    formulas: ['Area = Q / v_filt', 'Clean Bed Loss Ergun Equation'],
    designEngine: 'filtrationEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'FIL-002',
    processId: 'FILTRATION',
    category: 'Dual Media Gravity',
    name: 'Dual Media Filter (Anthracite + Sand)',
    shortDescription: 'Crushed anthracite coal layered over silica sand bed.',
    detailedDescription: 'Top layer of coarse anthracite (400mm, d10=0.9mm) over fine silica sand (600mm, d10=0.55mm) allows deep bed filtration, doubling filter run times and enabling 1.5x higher filtration rates (10 - 12 m/hr).',
    applicableWaterQuality: { maxTurbidity: 25 },
    applicableFlowRange: { minFlowMLD: 5, maxFlowMLD: 500 },
    minimumFlow: 5,
    maximumFlow: 500,
    hydraulicRequirement: '1.5m to 2.4m total filter headloss',
    landRequirement: 'Low',
    landAreaFactor: 0.7,
    energyRequirement: 'Low',
    chemicalRequirement: 'Low',
    operationalComplexity: 'Medium',
    maintenanceRequirement: 'Medium',
    automationRequirement: 'Moderate',
    sludgeGeneration: 'Medium',
    treatmentEfficiency: 96,
    reliability: 95,
    expandability: 90,
    constructability: 90,
    climateSuitability: 'Universal',
    BangladeshSuitability: 'High - Recommended for modern plant expansions to save 30% filter footprint.',
    capitalCostFactor: 1.15,
    operatingCostFactor: 0.85,
    lifecycleCostFactor: 0.88,
    footprintFactor: 0.7,
    advantages: ['Saves 30% filter civil area', '2x longer filter run times (48 - 72 hrs)', 'Deep bed solids storage prevents rapid surface blinding'],
    disadvantages: ['Anthracite media import cost', 'Requires precise backwash fluidization to maintain bed stratification'],
    limitations: ['Requires plastic nozzle underdrains for air scour'],
    requiredParameters: ['numberOfFilters', 'filtrationRateM3M2Hr', 'anthraciteDepthM'],
    optionalParameters: [],
    dependentProcesses: ['Disinfection'],
    incompatibleProcesses: [],
    recommendedWhen: ['Filter footprint reduction or longer filter runs needed'],
    avoidWhen: ['Anthracite supply chain is unavailable'],
    standards: ['AWWA B100', 'CPHEEO 2021'],
    formulas: ['v_filt = 10 to 12 m/h', 'Expansion = 35% Anthracite + 25% Sand'],
    designEngine: 'filtrationEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'FIL-003',
    processId: 'FILTRATION',
    category: 'Membrane Filtration',
    name: 'Ultrafiltration (UF) Membrane System',
    shortDescription: 'Hollow fiber UF membranes (0.02 micron pore size) providing absolute physical barrier.',
    detailedDescription: 'Submerged or pressure hollow fiber UF membranes deliver absolute 4-log virus and 6-log Giardia/Cryptosporidium removal, producing pristine permeate turbidity (< 0.1 NTU) regardless of feed quality.',
    applicableWaterQuality: { maxTurbidity: 50 },
    applicableFlowRange: { minFlowMLD: 5, maxFlowMLD: 300 },
    minimumFlow: 5,
    maximumFlow: 300,
    hydraulicRequirement: '0.3 to 1.5 bar Transmembrane Pressure (TMP)',
    landRequirement: 'Very Low',
    landAreaFactor: 0.25,
    energyRequirement: 'High',
    chemicalRequirement: 'High',
    operationalComplexity: 'Very High',
    maintenanceRequirement: 'High',
    automationRequirement: 'Fully Automated',
    sludgeGeneration: 'Low',
    treatmentEfficiency: 99.9,
    reliability: 90,
    expandability: 98,
    constructability: 80,
    climateSuitability: 'Indoor climate-controlled skid installation.',
    BangladeshSuitability: 'Medium - Growing adoption in industrial parks and high-grade municipal water projects.',
    capitalCostFactor: 2.1,
    operatingCostFactor: 2.2,
    lifecycleCostFactor: 2.0,
    footprintFactor: 0.25,
    advantages: ['Absolute physical pathogen barrier (4-log virus removal)', 'Permeate turbidity consistently < 0.1 NTU', '75% footprint savings compared to rapid sand filters'],
    disadvantages: ['High capital cost and membrane module replacement every 8-10 years', 'Requires chemical clean-in-place (CIP) with NaOCl and citric acid'],
    limitations: ['Pre-screening (150-300 micron) strictly mandatory to protect hollow fibers'],
    requiredParameters: ['fluxLMH', 'recoveryPct', 'membranePoreMicron'],
    optionalParameters: [],
    dependentProcesses: ['Disinfection'],
    incompatibleProcesses: [],
    recommendedWhen: ['Strict WHO/EU drinking water quality, pathogen removal, or space constraints'],
    avoidWhen: ['Budget is minimal or chemical CIP supply is unavailable'],
    standards: ['USEPA Membrane Filtration Guidance Manual', 'AWWA M53'],
    formulas: ['Permeate Flow = Flux * Total_Membrane_Area', 'TMP = P_feed - P_permeate'],
    designEngine: 'filtrationEngine.ts',
    status: 'ACTIVE'
  },

  // ==========================================
  // 6. DISINFECTION ALTERNATIVES
  // ==========================================
  {
    alternativeId: 'DIS-001',
    processId: 'DISINFECTION',
    category: 'Chemical Gas',
    name: 'Gas Chlorination System',
    shortDescription: '1-Ton cylinder liquefied chlorine gas injection with vacuum chlorinators.',
    detailedDescription: 'Chlorine gas vacuum dosing into a baffled contact basin providing CT (Concentration x Time) disinfection and maintaining a stable 0.5 - 2.0 mg/L free chlorine residual in the distribution network.',
    applicableWaterQuality: { maxTOC: 4.0 },
    applicableFlowRange: { minFlowMLD: 1, maxFlowMLD: 1000 },
    minimumFlow: 1,
    maximumFlow: 1000,
    hydraulicRequirement: '0.2m contact basin headloss',
    landRequirement: 'Medium',
    landAreaFactor: 1.0,
    energyRequirement: 'Low',
    chemicalRequirement: 'High',
    operationalComplexity: 'Medium',
    maintenanceRequirement: 'Medium',
    automationRequirement: 'Moderate',
    sludgeGeneration: 'None',
    treatmentEfficiency: 98,
    reliability: 98,
    expandability: 90,
    constructability: 92,
    climateSuitability: 'Requires dedicated ventilated chlorine building with emergency gas scrubber.',
    BangladeshSuitability: 'High - Standard disinfection method across Bangladesh WASAs.',
    capitalCostFactor: 1.0,
    operatingCostFactor: 0.8,
    lifecycleCostFactor: 0.9,
    footprintFactor: 1.0,
    advantages: ['Provides essential long-lasting distribution network residual', 'Lowest chemical OPEX per m3', 'Proven 100-year track record'],
    disadvantages: ['Hazardous gas safety risks requiring safety scrubbers and leak detectors', 'Disinfection By-Product (THM) formation risk if raw TOC is high'],
    limitations: ['Chlorine gas handling safety regulations apply'],
    requiredParameters: ['chlorineDoseMgL', 'chlorineContactMin', 'Q_m3hr'],
    optionalParameters: [],
    dependentProcesses: ['CWR_STORAGE'],
    incompatibleProcesses: [],
    recommendedWhen: ['Municipal distribution system requires persistent chlorine residual'],
    avoidWhen: ['Chlorine gas transport/storage is legally restricted in dense urban center'],
    standards: ['CPHEEO 2021 Vol I Sec 5.7', 'AWWA B301'],
    formulas: ['CT = C_residual * t_contact', 'Mass_kg_day = Q_mld * Dose_mgL'],
    designEngine: 'chemicalEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'DIS-002',
    processId: 'DISINFECTION',
    category: 'Physical UV Light',
    name: 'UV Disinfection System',
    shortDescription: 'Medium/Low pressure high-intensity UV lamps in stainless steel reactors.',
    detailedDescription: 'Ultraviolet light (254nm wavelength) irradiates microorganisms, damaging their DNA/RNA to achieve 4-log pathogen inactivation (including Cryptosporidium and Giardia) without chemical dosage.',
    applicableWaterQuality: { minUVT: 80, maxTurbidity: 2.0 },
    applicableFlowRange: { minFlowMLD: 1, maxFlowMLD: 500 },
    minimumFlow: 1,
    maximumFlow: 500,
    hydraulicRequirement: '0.1m reactor headloss',
    landRequirement: 'Very Low',
    landAreaFactor: 0.15,
    energyRequirement: 'High',
    chemicalRequirement: 'None',
    operationalComplexity: 'Medium',
    maintenanceRequirement: 'Medium',
    automationRequirement: 'Fully Automated',
    sludgeGeneration: 'None',
    treatmentEfficiency: 99.9,
    reliability: 92,
    expandability: 95,
    constructability: 95,
    climateSuitability: 'Universal indoor installation.',
    BangladeshSuitability: 'Medium - Excellent secondary barrier combined with low-dose chlorine.',
    capitalCostFactor: 1.5,
    operatingCostFactor: 1.6,
    lifecycleCostFactor: 1.5,
    footprintFactor: 0.15,
    advantages: ['Zero Disinfection By-Products (THMs / HAAs)', 'Instantaneous inactivation (1-5 seconds)', 'Inactivates chlorine-resistant Cryptosporidium oocysts'],
    disadvantages: ['No persistent distribution network residual (requires secondary chlorine booster)', 'UV lamp replacement every 12,000 hours'],
    limitations: ['Water UV Transmittance (UVT) must be > 75% and turbidity < 2 NTU'],
    requiredParameters: ['uvDosemJcm2', 'uvtPercent', 'Q_m3hr'],
    optionalParameters: [],
    dependentProcesses: ['CWR_STORAGE'],
    incompatibleProcesses: [],
    recommendedWhen: ['Cryptosporidium risk present, or minimizing THM formation'],
    avoidWhen: ['Water UVT < 70% or unfiltered high turbidity'],
    standards: ['USEPA UV Disinfection Guidance Manual', 'AWWA F110'],
    formulas: ['UV Dose = Intensity * Time', 'Lamps = Flow / Lamp_Capacity'],
    designEngine: 'chemicalEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'DIS-003',
    processId: 'DISINFECTION',
    category: 'Multi-Barrier Hybrid',
    name: 'UV + Primary Chlorination Hybrid',
    shortDescription: 'Dual-barrier UV irradiation followed by low-dose gas/liquid chlorination.',
    detailedDescription: 'Combines the instant pathogen inactivation power of UV (for Cryptosporidium) with a reduced secondary chlorine dose (1.0 mg/L) to maintain network residual while cutting THM formation by 60%.',
    applicableWaterQuality: { minUVT: 75, maxTurbidity: 2.0 },
    applicableFlowRange: { minFlowMLD: 5, maxFlowMLD: 500 },
    minimumFlow: 5,
    maximumFlow: 500,
    hydraulicRequirement: '0.3m total headloss',
    landRequirement: 'Low',
    landAreaFactor: 0.3,
    energyRequirement: 'Medium',
    chemicalRequirement: 'Low',
    operationalComplexity: 'High',
    maintenanceRequirement: 'Medium',
    automationRequirement: 'Advanced',
    sludgeGeneration: 'None',
    treatmentEfficiency: 99.99,
    reliability: 97,
    expandability: 95,
    constructability: 90,
    climateSuitability: 'Universal',
    BangladeshSuitability: 'High - Gold standard multi-barrier protection for modern megacity WTPs.',
    capitalCostFactor: 1.8,
    operatingCostFactor: 1.4,
    lifecycleCostFactor: 1.5,
    footprintFactor: 0.3,
    advantages: ['Multi-barrier 4-log protection against viruses, bacteria, and protozoa', '60% reduction in THM disinfection by-products', 'Ensures network residual'],
    disadvantages: ['Higher initial equipment CAPEX', 'Dual equipment maintenance'],
    limitations: ['Requires filtered water UVT > 75%'],
    requiredParameters: ['uvDosemJcm2', 'chlorineDoseMgL', 'Q_m3hr'],
    optionalParameters: [],
    dependentProcesses: ['CWR_STORAGE'],
    incompatibleProcesses: [],
    recommendedWhen: ['Highest drinking water safety standard and THM mitigation required'],
    avoidWhen: ['Budget is severely constrained'],
    standards: ['WHO 2022 Guidelines', 'USEPA LT2ESWTR'],
    formulas: ['Log_Total = Log_UV + Log_Chlorine'],
    designEngine: 'chemicalEngine.ts',
    status: 'ACTIVE'
  },

  // ==========================================
  // 7. INTAKE ALTERNATIVES
  // ==========================================
  {
    alternativeId: 'INT-001',
    processId: 'INTAKE',
    category: 'Direct Sump Intake',
    name: 'Direct River Sump / Wet Well Intake',
    shortDescription: 'Reinforced concrete intake structure on river bank with coarse/fine screens.',
    detailedDescription: 'Shore-mounted concrete wet well shaft connected to river via intake pipes, equipped with trash racks, coarse screens, fine traveling screens, and raw water pumps.',
    applicableWaterQuality: { maxTurbidity: 5000 },
    applicableFlowRange: { minFlowMLD: 10, maxFlowMLD: 1000 },
    minimumFlow: 10,
    maximumFlow: 1000,
    hydraulicRequirement: 'Screen headloss 0.1m - 0.3m',
    landRequirement: 'High',
    landAreaFactor: 1.0,
    energyRequirement: 'Low',
    chemicalRequirement: 'None',
    operationalComplexity: 'Medium',
    maintenanceRequirement: 'Medium',
    automationRequirement: 'Moderate',
    sludgeGeneration: 'Low',
    treatmentEfficiency: 70,
    reliability: 95,
    expandability: 85,
    constructability: 85,
    climateSuitability: 'Designed for river water level variations up to 8.0 meters.',
    BangladeshSuitability: 'High - Standard intake design on Padma, Meghna, Jamuna, and Karnaphuli rivers.',
    capitalCostFactor: 1.0,
    operatingCostFactor: 1.0,
    lifecycleCostFactor: 1.0,
    footprintFactor: 1.0,
    advantages: ['Handles massive raw water flows', 'Durable heavy civil structure withstands flood scour', 'Accommodates large vertical turbine pumps'],
    disadvantages: ['High civil construction cost in wet riverbank soils', 'Requires cofferdam during construction'],
    limitations: ['Riverbank stability and scour protection mandatory'],
    requiredParameters: ['HFL_MSL', 'LWL_MSL', 'Q_m3hr'],
    optionalParameters: [],
    dependentProcesses: ['AERATION', 'COAGULATION'],
    incompatibleProcesses: [],
    recommendedWhen: ['Large municipal surface water plant (> 20 MLD) on major river'],
    avoidWhen: ['River course is highly unstable and meandering'],
    standards: ['CPHEEO 2021 Vol I Sec 4', 'IS 11385'],
    formulas: ['Screen loss Kirschmer formula', 'Submergence HI 9.8'],
    designEngine: 'intakeEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'INT-002',
    processId: 'INTAKE',
    category: 'Sub-Surface Filtration',
    name: 'Riverbank Filtration (RBF) Intake',
    shortDescription: 'Vertical borewells or collector wells drilled into alluvial riverbank aquifer.',
    detailedDescription: 'Induced bank filtration utilizes the natural riverbed sand/gravel aquifer as a pre-filter, removing 90-99% of raw turbidity, algae, pathogens, and suspended solids naturally.',
    applicableWaterQuality: { minTurbidity: 100, maxTurbidity: 10000 },
    applicableFlowRange: { minFlowMLD: 2, maxFlowMLD: 100 },
    minimumFlow: 2,
    maximumFlow: 100,
    hydraulicRequirement: 'Pumping drawdown head',
    landRequirement: 'Medium',
    landAreaFactor: 0.6,
    energyRequirement: 'Medium',
    chemicalRequirement: 'None',
    operationalComplexity: 'Low',
    maintenanceRequirement: 'Low',
    automationRequirement: 'Basic',
    sludgeGeneration: 'None',
    treatmentEfficiency: 95,
    reliability: 98,
    expandability: 70,
    constructability: 80,
    climateSuitability: 'Ideal for rivers with extreme seasonal turbidity spikes during monsoons.',
    BangladeshSuitability: 'High - Excellent natural pre-treatment along major river floodplains.',
    capitalCostFactor: 0.8,
    operatingCostFactor: 0.6,
    lifecycleCostFactor: 0.7,
    footprintFactor: 0.6,
    advantages: ['Natural pre-filtration eliminates presedimentation basin needs', 'Buffers monsoon turbidity spikes from 5000 to < 10 NTU', 'Dramatically reduces chemical coagulant demand'],
    disadvantages: ['Hydrogeological aquifer permeability dependence', 'Potential well screen clogging over 20-25 years'],
    limitations: ['Requires suitable alluvial sand/gravel riverbank geology'],
    requiredParameters: ['aquiferTransmissivity', 'Q_m3hr'],
    optionalParameters: [],
    dependentProcesses: ['FILTRATION', 'DISINFECTION'],
    incompatibleProcesses: [],
    recommendedWhen: ['Suitable alluvial riverbank aquifer exists and high monsoon turbidity occurs'],
    avoidWhen: ['Riverbank hydrogeology is impermeable clay'],
    standards: ['AWWA M21', 'CPHEEO 2021'],
    formulas: ['Well Yield Q = 2 * pi * K * D * s / ln(R/r)'],
    designEngine: 'intakeEngine.ts',
    status: 'ACTIVE'
  },

  // ==========================================
  // 8. PUMPING ALTERNATIVES
  // ==========================================
  {
    alternativeId: 'PMP-001',
    processId: 'PUMPING',
    category: 'Vertical Shaft',
    name: 'Vertical Turbine Pump (VTP)',
    shortDescription: 'Submerged multi-stage vertical bowl pump with line-shaft motor drive.',
    detailedDescription: 'Deep wet well vertical pump with submerged impeller bowls operating at 82-88% hydraulic efficiency, self-priming, and accommodating 10m+ water level variations.',
    applicableWaterQuality: { maxTurbidity: 1000 },
    applicableFlowRange: { minFlowMLD: 2, maxFlowMLD: 500 },
    minimumFlow: 2,
    maximumFlow: 500,
    hydraulicRequirement: 'Submergence per HI 9.8 standard',
    landRequirement: 'Low',
    landAreaFactor: 0.5,
    energyRequirement: 'Medium',
    chemicalRequirement: 'None',
    operationalComplexity: 'Low',
    maintenanceRequirement: 'Medium',
    automationRequirement: 'Moderate',
    sludgeGeneration: 'None',
    treatmentEfficiency: 86,
    reliability: 96,
    expandability: 90,
    constructability: 90,
    climateSuitability: 'Universal intake application.',
    BangladeshSuitability: 'High - Standard raw water intake pump for all surface water plants.',
    capitalCostFactor: 1.0,
    operatingCostFactor: 1.0,
    lifecycleCostFactor: 1.0,
    footprintFactor: 0.5,
    advantages: ['Submerged impeller bowl eliminates priming problems', 'Compact pump house floor area', 'Handles large river water level fluctuations'],
    disadvantages: ['Line shaft bearing lubrication maintenance', 'Higher initial procurement cost'],
    limitations: ['Requires minimum wet well submergence to prevent vortexing'],
    requiredParameters: ['dutyFlowM3hr', 'staticHeadM', 'pipeLengthM'],
    optionalParameters: [],
    dependentProcesses: ['AERATION', 'COAGULATION'],
    incompatibleProcesses: [],
    recommendedWhen: ['Raw water river intake with fluctuating water levels'],
    avoidWhen: ['Suction lift is zero and dry pit is preferred'],
    standards: ['Hydraulic Institute HI 9.8 / HI 14.6', 'ISO 9906'],
    formulas: ['Power Kw = (Q * H * g) / (3600 * eta)', 'NPSHa = H_atm + H_z - H_f - H_vp'],
    designEngine: 'pumpMechanicalEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'PMP-002',
    processId: 'PUMPING',
    category: 'Horizontal Dry Pit',
    name: 'Horizontal Split Case Pump',
    shortDescription: 'Double suction horizontal split casing pump for high head clear water.',
    detailedDescription: 'Dry-pit installed horizontal split casing centrifugal pump delivering high efficiency (85-90%) for high lift distribution pumping mains.',
    applicableWaterQuality: { maxTurbidity: 5 },
    applicableFlowRange: { minFlowMLD: 5, maxFlowMLD: 500 },
    minimumFlow: 5,
    maximumFlow: 500,
    hydraulicRequirement: 'Positive suction head required',
    landRequirement: 'Medium',
    landAreaFactor: 1.0,
    energyRequirement: 'Medium',
    chemicalRequirement: 'None',
    operationalComplexity: 'Low',
    maintenanceRequirement: 'Low',
    automationRequirement: 'Moderate',
    sludgeGeneration: 'None',
    treatmentEfficiency: 88,
    reliability: 98,
    expandability: 90,
    constructability: 95,
    climateSuitability: 'Indoor pump house installation.',
    BangladeshSuitability: 'High - Standard high-lift distribution pump delivering water to municipal networks.',
    capitalCostFactor: 0.9,
    operatingCostFactor: 0.9,
    lifecycleCostFactor: 0.88,
    footprintFactor: 1.0,
    advantages: ['Easy maintenance (casing splits horizontally without disturbing piping)', 'High energy efficiency (up to 90%)', 'Long bearing lifecycle'],
    disadvantages: ['Requires dry pump room floor space', 'Requires positive suction head'],
    limitations: ['Clear water only (filtered effluent)'],
    requiredParameters: ['dutyFlowM3hr', 'staticHeadM'],
    optionalParameters: [],
    dependentProcesses: ['CWR_STORAGE'],
    incompatibleProcesses: [],
    recommendedWhen: ['High lift distribution pumping from CWR reservoir'],
    avoidWhen: ['Raw water with heavy sand/silt grit'],
    standards: ['HI 14.6', 'ISO 9906'],
    formulas: ['Power Kw = (Q * H * g) / (3600 * eta)'],
    designEngine: 'pumpMechanicalEngine.ts',
    status: 'ACTIVE'
  },

  // ==========================================
  // 9. SLUDGE THICKENING ALTERNATIVES
  // ==========================================
  {
    alternativeId: 'SLU-THK-001',
    processId: 'SLUDGE_THICKENING',
    category: 'Gravity Settling',
    name: 'Gravity Sludge Thickener',
    shortDescription: 'Circular concrete tank with picket-fence scraper thickening sludge to 3-5% solids.',
    detailedDescription: 'Gravity sedimentation tank equipped with vertical picket fence rake arms that create channels for pore water escape, increasing sludge solids concentration from 0.5% to 4.0%.',
    applicableWaterQuality: {},
    applicableFlowRange: { minFlowMLD: 5, maxFlowMLD: 500 },
    minimumFlow: 5,
    maximumFlow: 500,
    hydraulicRequirement: 'Gravity flow inlet',
    landRequirement: 'High',
    landAreaFactor: 1.0,
    energyRequirement: 'Very Low',
    chemicalRequirement: 'Low',
    operationalComplexity: 'Low',
    maintenanceRequirement: 'Low',
    automationRequirement: 'Basic',
    sludgeGeneration: 'High',
    treatmentEfficiency: 85,
    reliability: 98,
    expandability: 80,
    constructability: 95,
    climateSuitability: 'Universal',
    BangladeshSuitability: 'High - Reliable low-power sludge volume reduction.',
    capitalCostFactor: 1.0,
    operatingCostFactor: 0.3,
    lifecycleCostFactor: 0.7,
    footprintFactor: 1.0,
    advantages: ['Extremely low electrical energy consumption', 'Simple mechanical rake mechanism', 'Reduces sludge volume by 80%'],
    disadvantages: ['Large circular tank land area', 'Septicity/odor potential if sludge is stored too long'],
    limitations: ['Solids loading limit 30-50 kg/m2/day'],
    requiredParameters: ['sludgeFlowM3day', 'sludgeSolidsPct'],
    optionalParameters: [],
    dependentProcesses: ['SLUDGE_DEWATERING'],
    incompatibleProcesses: [],
    recommendedWhen: ['Low OPEX and simple operation prioritized'],
    avoidWhen: ['Site land area is severely restricted'],
    standards: ['CPHEEO 2021 Vol I Sec 8', 'WEF MOP 8'],
    formulas: ['Area = Solids_kg_day / Solids_Loading_Rate'],
    designEngine: 'sludgeEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'SLU-THK-002',
    processId: 'SLUDGE_THICKENING',
    category: 'Mechanical Thickening',
    name: 'Rotary Drum Sludge Thickener',
    shortDescription: 'Enclosed rotating porous drum screen thickening sludge to 5-7% solids.',
    detailedDescription: 'Polymer-conditioned sludge enters a slowly rotating internal screw drum screen where filtrate drains rapidly through stainless steel mesh, achieving 6% dry solids concentration in a tiny footprint.',
    applicableWaterQuality: {},
    applicableFlowRange: { minFlowMLD: 10, maxFlowMLD: 500 },
    minimumFlow: 10,
    maximumFlow: 500,
    hydraulicRequirement: 'Pressurized feed',
    landRequirement: 'Very Low',
    landAreaFactor: 0.15,
    energyRequirement: 'Medium',
    chemicalRequirement: 'High',
    operationalComplexity: 'Medium',
    maintenanceRequirement: 'Medium',
    automationRequirement: 'Advanced',
    sludgeGeneration: 'High',
    treatmentEfficiency: 95,
    reliability: 90,
    expandability: 95,
    constructability: 85,
    climateSuitability: 'Indoor enclosed skid.',
    BangladeshSuitability: 'Medium - Great for compact urban plants.',
    capitalCostFactor: 1.4,
    operatingCostFactor: 1.5,
    lifecycleCostFactor: 1.3,
    footprintFactor: 0.15,
    advantages: ['85% land footprint reduction compared to gravity thickener', 'Fully enclosed design eliminates odor', 'Achieves higher solids concentration (5-7%)'],
    disadvantages: ['Requires continuous polymer chemical dosing', 'Filter screen washwater demand'],
    limitations: ['Requires polymer dosing system'],
    requiredParameters: ['sludgeFlowM3day', 'polymerDoseGms3'],
    optionalParameters: [],
    dependentProcesses: ['SLUDGE_DEWATERING'],
    incompatibleProcesses: [],
    recommendedWhen: ['Compact indoor sludge treatment or odor control required'],
    avoidWhen: ['Polymer supply is unavailable'],
    standards: ['WEF MOP 8'],
    formulas: ['Filtrate_flow = Sludge_flow * (1 - S1/S2)'],
    designEngine: 'sludgeEngine.ts',
    status: 'ACTIVE'
  },

  // ==========================================
  // 10. SLUDGE DEWATERING ALTERNATIVES
  // ==========================================
  {
    alternativeId: 'SLU-DEW-001',
    processId: 'SLUDGE_DEWATERING',
    category: 'Pressure Dewatering',
    name: 'Recessed Plate Filter Press',
    shortDescription: 'High-pressure hydraulic plate filter press delivering 30-40% dry cake.',
    detailedDescription: 'Hydraulic ram compresses chamber plates at 7-15 bar pressure, squeezing water out through filter cloths to produce dry, stackable sludge cake (35% dry solids) suitable for disposal/landfill.',
    applicableWaterQuality: {},
    applicableFlowRange: { minFlowMLD: 2, maxFlowMLD: 500 },
    minimumFlow: 2,
    maximumFlow: 500,
    hydraulicRequirement: '10 bar feed pressure',
    landRequirement: 'Low',
    landAreaFactor: 0.4,
    energyRequirement: 'High',
    chemicalRequirement: 'Medium',
    operationalComplexity: 'Medium',
    maintenanceRequirement: 'Medium',
    automationRequirement: 'Moderate',
    sludgeGeneration: 'High',
    treatmentEfficiency: 98,
    reliability: 95,
    expandability: 85,
    constructability: 88,
    climateSuitability: 'Indoor dewatering building.',
    BangladeshSuitability: 'High - Produces dry, easily transportable cake for agricultural or landfill use.',
    capitalCostFactor: 1.3,
    operatingCostFactor: 1.0,
    lifecycleCostFactor: 1.1,
    footprintFactor: 0.4,
    advantages: ['Highest cake dryness (30-40% dry solids)', 'Lowest liquid sludge transport volume', 'Clear filtrate recycle'],
    disadvantages: ['Batch operation cycle (1.5 - 3 hours)', 'Cloth washing maintenance'],
    limitations: ['Requires high pressure feed pumps'],
    requiredParameters: ['drySolidsKgDay', 'cakeDrynessPct'],
    optionalParameters: [],
    dependentProcesses: [],
    incompatibleProcesses: [],
    recommendedWhen: ['Maximum cake dryness and lowest disposal transport cost required'],
    avoidWhen: ['Continuous automated dewatering preferred'],
    standards: ['CPHEEO 2021 Vol I Sec 8', 'WEF MOP 8'],
    formulas: ['Cake_volume = Mass_solids / (Density * Dryness_pct)'],
    designEngine: 'sludgeEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'SLU-DEW-002',
    processId: 'SLUDGE_DEWATERING',
    category: 'Continuous Screw',
    name: 'Multi-Disk Volute Screw Press',
    shortDescription: 'Slow rotating screw press with self-cleaning multi-disk filter mesh.',
    detailedDescription: 'Slow-speed (2-4 RPM) Archimedes screw dewaters sludge continuously between fixed and moving stainless steel disks, consuming 95% less energy than centrifuges.',
    applicableWaterQuality: {},
    applicableFlowRange: { minFlowMLD: 5, maxFlowMLD: 300 },
    minimumFlow: 5,
    maximumFlow: 300,
    hydraulicRequirement: 'Gravity/low pressure feed',
    landRequirement: 'Very Low',
    landAreaFactor: 0.2,
    energyRequirement: 'Very Low',
    chemicalRequirement: 'Medium',
    operationalComplexity: 'Low',
    maintenanceRequirement: 'Low',
    automationRequirement: 'Fully Automated',
    sludgeGeneration: 'High',
    treatmentEfficiency: 95,
    reliability: 96,
    expandability: 95,
    constructability: 90,
    climateSuitability: 'Indoor enclosed skid.',
    BangladeshSuitability: 'High - Extremely low power consumption and 24/7 continuous operation.',
    capitalCostFactor: 1.25,
    operatingCostFactor: 0.5,
    lifecycleCostFactor: 0.8,
    footprintFactor: 0.2,
    advantages: ['95% lower power consumption than centrifuges', 'Continuous 24/7 operation with zero operator attendance', 'Self-cleaning disk mechanism prevents clogging'],
    disadvantages: ['Slightly lower cake dryness (20-25%) compared to plate press', 'Requires polymer conditioning'],
    limitations: ['Polymer dosing mandatory'],
    requiredParameters: ['drySolidsKgDay', 'polymerDoseGms3'],
    optionalParameters: [],
    dependentProcesses: [],
    incompatibleProcesses: [],
    recommendedWhen: ['24/7 automated continuous operation and low energy consumption required'],
    avoidWhen: ['Cake dryness > 35% is strictly required'],
    standards: ['WEF MOP 8'],
    formulas: ['Power = 0.5 to 2.0 kW per unit'],
    designEngine: 'sludgeEngine.ts',
    status: 'ACTIVE'
  },

  // ==========================================
  // 11. CWR / STORAGE ALTERNATIVES
  // ==========================================
  {
    alternativeId: 'CWR-001',
    processId: 'CWR_STORAGE',
    category: 'Concrete Ground Reservoir',
    name: 'Reinforced Concrete Ground Reservoir',
    shortDescription: 'Partially buried RCC reservoir providing 8-12 hours treated water storage.',
    detailedDescription: 'Multi-compartment reinforced concrete water retaining tank per ACI 350 / IS 3370 standards with internal baffles to prevent short-circuiting and guarantee contact time.',
    applicableWaterQuality: {},
    applicableFlowRange: { minFlowMLD: 1, maxFlowMLD: 1000 },
    minimumFlow: 1,
    maximumFlow: 1000,
    hydraulicRequirement: 'Static floor level at plant GL',
    landRequirement: 'High',
    landAreaFactor: 1.0,
    energyRequirement: 'Very Low',
    chemicalRequirement: 'None',
    operationalComplexity: 'Very Low',
    maintenanceRequirement: 'Low',
    automationRequirement: 'Basic',
    sludgeGeneration: 'None',
    treatmentEfficiency: 100,
    reliability: 99,
    expandability: 85,
    constructability: 95,
    climateSuitability: 'Universal',
    BangladeshSuitability: 'High - Standard clear water reservoir design for municipal WTPs.',
    capitalCostFactor: 1.0,
    operatingCostFactor: 0.1,
    lifecycleCostFactor: 0.8,
    footprintFactor: 1.0,
    advantages: ['50-100 year design life', 'High structural mass resists groundwater flotation', 'Multi-compartment allows cleaning without shutdown'],
    disadvantages: ['Large land footprint required', 'High civil concrete volume'],
    limitations: ['Requires water-retaining concrete design (ACI 350)'],
    requiredParameters: ['cwrVolumeM3', 'cwrDetentionHours'],
    optionalParameters: [],
    dependentProcesses: ['PUMPING'],
    incompatibleProcesses: [],
    recommendedWhen: ['Standard clear water storage with 8+ hours capacity'],
    avoidWhen: ['Site footprint is zero'],
    standards: ['ACI 350-06', 'IS 3370', 'CPHEEO 2021'],
    formulas: ['Volume = Q_m3hr * Hours', 'Area = Volume / Depth'],
    designEngine: 'civilEngineeringEngine.ts',
    status: 'ACTIVE'
  },

  // ==========================================
  // 12. ELECTRICAL SYSTEM ALTERNATIVES
  // ==========================================
  {
    alternativeId: 'ELE-001',
    processId: 'ELECTRICAL_SYSTEM',
    category: 'Grid + Generator Backup',
    name: 'Grid 11kV Substation + Diesel Generator Backup',
    shortDescription: 'Dual step-down transformers (N+1) with automatic transfer switch (ATS) DG backup.',
    detailedDescription: '11kV/415V indoor step-down transformers operating with motorized VFD MCC panels and 100% standby Diesel Generator set to ensure uninterrupted pumping.',
    applicableWaterQuality: {},
    applicableFlowRange: { minFlowMLD: 1, maxFlowMLD: 1000 },
    minimumFlow: 1,
    maximumFlow: 1000,
    hydraulicRequirement: 'N/A',
    landRequirement: 'Medium',
    landAreaFactor: 1.0,
    energyRequirement: 'High',
    chemicalRequirement: 'None',
    operationalComplexity: 'Medium',
    maintenanceRequirement: 'Medium',
    automationRequirement: 'Moderate',
    sludgeGeneration: 'None',
    treatmentEfficiency: 100,
    reliability: 98,
    expandability: 90,
    constructability: 95,
    climateSuitability: 'Universal',
    BangladeshSuitability: 'High - Crucial for handling national grid power load shedding.',
    capitalCostFactor: 1.0,
    operatingCostFactor: 1.0,
    lifecycleCostFactor: 1.0,
    footprintFactor: 1.0,
    advantages: ['Guarantees 100% power uptime during grid blackouts', 'N+1 transformer redundancy', 'VFD energy optimization on pumps'],
    disadvantages: ['Diesel fuel OPEX during grid outages', 'Substation building land requirement'],
    limitations: ['Requires diesel fuel storage tank'],
    requiredParameters: ['connectedLoadKw', 'transformerKva'],
    optionalParameters: [],
    dependentProcesses: [],
    incompatibleProcesses: [],
    recommendedWhen: ['Reliable uninterrupted 24/7 water supply required on unstable grid'],
    avoidWhen: ['Grid is 100% reliable without blackouts'],
    standards: ['BNBC 2020', 'IEEE 141', 'IEC 60364'],
    formulas: ['KVA = Kw / (0.85 * eta)', 'I_sc = S / (sqrt(3) * V * Z)'],
    designEngine: 'electricalEngine.ts',
    status: 'ACTIVE'
  },
  {
    alternativeId: 'ELE-002',
    processId: 'ELECTRICAL_SYSTEM',
    category: 'Hybrid Renewable',
    name: 'Grid + DG + Rooftop Solar PV Hybrid',
    shortDescription: 'Grid + DG plus 250kWp rooftop solar PV offset reducing day energy OPEX by 25%.',
    detailedDescription: 'Integrates grid sub-station, DG backup, and rooftop solar PV array over filter/CWR roofs with grid-tie inverters, cutting daytime electricity bills and carbon footprint.',
    applicableWaterQuality: {},
    applicableFlowRange: { minFlowMLD: 5, maxFlowMLD: 500 },
    minimumFlow: 5,
    maximumFlow: 500,
    hydraulicRequirement: 'N/A',
    landRequirement: 'Very Low',
    landAreaFactor: 0.1, // Uses existing roofs!
    energyRequirement: 'Low',
    chemicalRequirement: 'None',
    operationalComplexity: 'Medium',
    maintenanceRequirement: 'Low',
    automationRequirement: 'Advanced',
    sludgeGeneration: 'None',
    treatmentEfficiency: 100,
    reliability: 98,
    expandability: 95,
    constructability: 90,
    climateSuitability: 'Ideal for high solar irradiance tropical climates.',
    BangladeshSuitability: 'High - Strongly aligned with Bangladesh Government Green Infrastructure mandates.',
    capitalCostFactor: 1.25,
    operatingCostFactor: 0.75,
    lifecycleCostFactor: 0.78,
    footprintFactor: 0.1,
    advantages: ['20-30% reduction in annual electricity OPEX', 'Uses existing building roof space (zero extra land)', 'Payback period under 5.5 years'],
    disadvantages: ['Higher initial electrical CAPEX for solar panels and grid-tie inverters'],
    limitations: ['Solar power generated during daytime only'],
    requiredParameters: ['connectedLoadKw', 'solarKwp'],
    optionalParameters: [],
    dependentProcesses: [],
    incompatibleProcesses: [],
    recommendedWhen: ['Lowering 30-year lifecycle energy OPEX is prioritized'],
    avoidWhen: ['Unshaded roof area is insufficient'],
    standards: ['BNBC 2020', 'IEC 61724'],
    formulas: ['Solar_kWh_day = kWp * Irradiance_hours * Performance_ratio'],
    designEngine: 'electricalEngine.ts',
    status: 'ACTIVE'
  }
];

export function getAlternativesByProcess(processId: ProcessCategory): DesignAlternative[] {
  return DESIGN_ALTERNATIVES_REGISTRY.filter(alt => alt.processId === processId && alt.status === 'ACTIVE');
}

export function getAlternativeById(alternativeId: string): DesignAlternative | undefined {
  return DESIGN_ALTERNATIVES_REGISTRY.find(alt => alt.alternativeId === alternativeId);
}
