import { ParameterDefinition } from '../types/wtp';

/**
 * EVL WTP Engineering Suite - Master Parameter Registry
 * Comprehensive registry covering 500+ Engineering Parameters
 */

export const MASTER_PARAMETER_REGISTRY: ParameterDefinition[] = [
  // ==========================================
  // 1. DESIGN BASIS & DEMANDS (PROJECT LEVEL)
  // ==========================================
  {
    id: 'DES-CAP-001',
    name: 'Plant Design Capacity (MLD)',
    symbol: 'Q_mld',
    category: 'Design Basis',
    subcategory: 'Flow',
    description: 'Target nominal daily production capacity of the Water Treatment Plant in Megaliters per day.',
    unit: 'MLD',
    type: 'input',
    defaultValue: 50,
    min: 0.1,
    max: 2000,
    recommendedMin: 1,
    recommendedMax: 500,
    designCriteria: 'Based on Future Max Day Demand projection.',
    standard: 'AWWA M51 / CPHEEO 2021',
    standardClause: 'Vol I, Sec 2.3',
    source: 'Water Master Plan',
    dependencies: [],
    calculationSequence: 1,
    required: true,
    applicablePlantType: 'Conventional / Advanced WTP',
    revision: 'REV-00',
    engineeringNotes: 'Master driver for all hydraulic, process, chemical, and equipment calculations.'
  },
  {
    id: 'DES-CAP-002',
    name: 'Plant Design Capacity (m3/hr)',
    symbol: 'Q_m3hr',
    category: 'Design Basis',
    subcategory: 'Flow',
    description: 'Hourly design flow rate operating at 24 hours per day.',
    unit: 'm³/hr',
    type: 'derived',
    formula: '(Q_mld * 1000) / 24',
    formulaVariables: ['DES-CAP-001'],
    defaultValue: 2083.33,
    min: 4.16,
    max: 83333.33,
    designCriteria: 'Flow rate for hourly process unit design.',
    standard: 'CPHEEO 2021',
    dependencies: ['DES-CAP-001'],
    calculationSequence: 2,
    required: true,
    revision: 'REV-00'
  },
  {
    id: 'DES-CAP-003',
    name: 'Plant Design Capacity (L/s)',
    symbol: 'Q_ls',
    category: 'Design Basis',
    subcategory: 'Flow',
    description: 'Instantaneous design flow rate in Liters per second.',
    unit: 'L/s',
    type: 'derived',
    formula: '(Q_mld * 1000000) / 86400',
    formulaVariables: ['DES-CAP-001'],
    defaultValue: 578.7,
    min: 1.15,
    max: 23148,
    designCriteria: 'Used for pipe sizing, rapid mix, and pumping calculations.',
    standard: 'CPHEEO 2021',
    dependencies: ['DES-CAP-001'],
    calculationSequence: 3,
    required: true,
    revision: 'REV-00'
  },
  {
    id: 'DES-POP-001',
    name: 'Base Population',
    symbol: 'P_0',
    category: 'Design Basis',
    subcategory: 'Population',
    description: 'Current population served by the water supply system.',
    unit: 'Capita',
    type: 'input',
    defaultValue: 250000,
    min: 500,
    max: 10000000,
    required: true,
    revision: 'REV-00'
  },
  {
    id: 'DES-POP-002',
    name: 'Annual Population Growth Rate',
    symbol: 'r',
    category: 'Design Basis',
    subcategory: 'Population',
    description: 'Compound annual demographic growth rate percentage.',
    unit: '%',
    type: 'input',
    defaultValue: 2.2,
    min: 0,
    max: 8,
    recommendedMin: 1.0,
    recommendedMax: 3.5,
    required: true,
    revision: 'REV-00'
  },
  {
    id: 'DES-POP-003',
    name: 'Design Period',
    symbol: 'n_years',
    category: 'Design Basis',
    subcategory: 'Population',
    description: 'Number of projection years from base year to design horizon year.',
    unit: 'Years',
    type: 'input',
    defaultValue: 30,
    min: 10,
    max: 50,
    recommendedMin: 20,
    recommendedMax: 30,
    designCriteria: '30 years standard for major municipal civil infrastructure.',
    standard: 'CPHEEO 2021',
    required: true,
    revision: 'REV-00'
  },
  {
    id: 'DES-DEM-001',
    name: 'Per Capita Consumption',
    symbol: 'q_lpcd',
    category: 'Design Basis',
    subcategory: 'Demand',
    description: 'Average per capita daily water consumption.',
    unit: 'Lpcd',
    type: 'input',
    defaultValue: 150,
    min: 50,
    max: 400,
    recommendedMin: 120,
    recommendedMax: 220,
    designCriteria: 'Includes domestic, commercial, and institutional allowances.',
    standard: 'WHO / CPHEEO',
    required: true,
    revision: 'REV-00'
  },
  {
    id: 'DES-DEM-002',
    name: 'Unaccounted For Water / NRW Allowance',
    symbol: 'NRW_%',
    category: 'Design Basis',
    subcategory: 'Demand',
    description: 'Non-Revenue Water allowance for distribution losses and backwash losses.',
    unit: '%',
    type: 'input',
    defaultValue: 15,
    min: 5,
    max: 40,
    recommendedMin: 10,
    recommendedMax: 20,
    required: true,
    revision: 'REV-00'
  },
  {
    id: 'DES-DEM-003',
    name: 'Maximum Day Demand Factor',
    symbol: 'K_day',
    category: 'Design Basis',
    subcategory: 'Demand',
    description: 'Ratio of maximum day water demand to average day water demand.',
    unit: 'ratio',
    type: 'input',
    defaultValue: 1.5,
    min: 1.1,
    max: 2.5,
    recommendedMin: 1.3,
    recommendedMax: 1.8,
    designCriteria: 'Typically 1.5 for urban WTP design.',
    standard: 'AWWA M51',
    required: true,
    revision: 'REV-00'
  },
  {
    id: 'DES-DEM-004',
    name: 'Peak Hour Demand Factor',
    symbol: 'K_peak',
    category: 'Design Basis',
    subcategory: 'Demand',
    description: 'Ratio of peak hourly demand to average day demand.',
    unit: 'ratio',
    type: 'input',
    defaultValue: 2.25,
    min: 1.5,
    max: 4.0,
    recommendedMin: 2.0,
    recommendedMax: 2.5,
    required: true,
    revision: 'REV-00'
  },

  // ==========================================
  // 2. RAW WATER SOURCE & HYDROLOGY
  // ==========================================
  {
    id: 'SRC-LVL-001',
    name: 'High Flood Level (HFL)',
    symbol: 'HFL',
    category: 'Raw Water Source',
    subcategory: 'Water Levels',
    description: 'Highest recorded water level at raw water intake site.',
    unit: 'm RL',
    type: 'input',
    defaultValue: 18.5,
    min: -50,
    max: 2000,
    required: true,
    engineeringNotes: 'Used to check structural buoyancy and top of intake wall elevation.'
  },
  {
    id: 'SRC-LVL-002',
    name: 'Lowest Water Level (LWL)',
    symbol: 'LWL',
    category: 'Raw Water Source',
    subcategory: 'Water Levels',
    description: 'Lowest operational water level in intake source during dry drought season.',
    unit: 'm RL',
    type: 'input',
    defaultValue: 12.0,
    min: -50,
    max: 2000,
    required: true,
    engineeringNotes: 'Determines pump suction head, minimum intake port elevation, and NPSHa.'
  },
  {
    id: 'SRC-LVL-003',
    name: 'Raw Water Temperature',
    symbol: 'T_water',
    category: 'Raw Water Source',
    subcategory: 'Physical',
    description: 'Design minimum/average raw water temperature.',
    unit: '°C',
    type: 'input',
    defaultValue: 25,
    min: 1,
    max: 45,
    recommendedMin: 15,
    recommendedMax: 32,
    required: true,
    engineeringNotes: 'Governs dynamic viscosity, kinematic viscosity, settling velocity, and G value calculations.'
  },

  // ==========================================
  // 3. RAW WATER QUALITY DATABASE (KEY DRIVERS)
  // ==========================================
  {
    id: 'WQ-PHY-001',
    name: 'Raw Water Turbidity',
    symbol: 'Tur_raw',
    category: 'Raw Water Quality',
    subcategory: 'Physical',
    description: 'Raw water nephelometric turbidity units during design conditions.',
    unit: 'NTU',
    type: 'input',
    defaultValue: 120,
    min: 0.1,
    max: 10000,
    recommendedMin: 5,
    recommendedMax: 500,
    designCriteria: 'Primary trigger for coagulation dose and clarifier type selection.',
    required: true,
    revision: 'REV-00'
  },
  {
    id: 'WQ-PHY-002',
    name: 'Raw Water pH',
    symbol: 'pH_raw',
    category: 'Raw Water Quality',
    subcategory: 'Chemical',
    description: 'Raw water pH value.',
    unit: 'pH',
    type: 'input',
    defaultValue: 7.2,
    min: 3.0,
    max: 11.0,
    recommendedMin: 6.5,
    recommendedMax: 8.5,
    required: true,
    revision: 'REV-00'
  },
  {
    id: 'WQ-CHM-001',
    name: 'Total Alkalinity',
    symbol: 'Alk_raw',
    category: 'Raw Water Quality',
    subcategory: 'Chemical',
    description: 'Total alkalinity as CaCO3.',
    unit: 'mg/L as CaCO3',
    type: 'input',
    defaultValue: 110,
    min: 5,
    max: 1000,
    recommendedMin: 30,
    recommendedMax: 250,
    required: true,
    engineeringNotes: 'Required to react with alum/ferric coagulants without depressing pH below 6.0.'
  },
  {
    id: 'WQ-CHM-002',
    name: 'Total Hardness',
    symbol: 'TH_raw',
    category: 'Raw Water Quality',
    subcategory: 'Chemical',
    description: 'Total hardness as CaCO3.',
    unit: 'mg/L as CaCO3',
    type: 'input',
    defaultValue: 180,
    min: 10,
    max: 1500,
    required: true
  },
  {
    id: 'WQ-CHM-003',
    name: 'Dissolved Iron (Fe)',
    symbol: 'Fe_raw',
    category: 'Raw Water Quality',
    subcategory: 'Metals',
    description: 'Dissolved iron concentration.',
    unit: 'mg/L',
    type: 'input',
    defaultValue: 1.8,
    min: 0.0,
    max: 50.0,
    recommendedMax: 0.3,
    designCriteria: 'Target < 0.3 mg/L (WHO/EPA). Triggers aeration or KMnO4 oxidation.',
    required: true
  },
  {
    id: 'WQ-CHM-004',
    name: 'Dissolved Manganese (Mn)',
    symbol: 'Mn_raw',
    category: 'Raw Water Quality',
    subcategory: 'Metals',
    description: 'Dissolved manganese concentration.',
    unit: 'mg/L',
    type: 'input',
    defaultValue: 0.25,
    min: 0.0,
    max: 10.0,
    recommendedMax: 0.1,
    designCriteria: 'Target < 0.1 mg/L (WHO/EPA). Requires green sand filter or KMnO4.',
    required: true
  },
  {
    id: 'WQ-CHM-005',
    name: 'Arsenic (As)',
    symbol: 'As_raw',
    category: 'Raw Water Quality',
    subcategory: 'Metals',
    description: 'Total arsenic concentration.',
    unit: 'mg/L',
    type: 'input',
    defaultValue: 0.04,
    min: 0.0,
    max: 2.0,
    designCriteria: 'WHO limit = 0.01 mg/L. BD ECR limit = 0.05 mg/L.',
    required: true
  },
  {
    id: 'WQ-MIC-001',
    name: 'E. coli Count',
    symbol: 'Ecoli_raw',
    category: 'Raw Water Quality',
    subcategory: 'Microbiology',
    description: 'E. coli bacterial concentration per 100 mL.',
    unit: 'CFU/100mL',
    type: 'input',
    defaultValue: 450,
    min: 0,
    max: 100000,
    designCriteria: 'Target 0 CFU/100mL in final water. Dictates log removal & CT requirement.',
    required: true
  },

  // ==========================================
  // 4. INTAKE & SCREENING
  // ==========================================
  {
    id: 'INT-SCR-001',
    name: 'Coarse Screen Bar Spacing',
    symbol: 'b_cs',
    category: 'Intake Design',
    subcategory: 'Screening',
    description: 'Clear opening between coarse bar screen elements.',
    unit: 'mm',
    type: 'input',
    defaultValue: 50,
    min: 25,
    max: 100,
    recommendedMin: 50,
    recommendedMax: 75,
    designCriteria: '50-75 mm for coarse trash rack.',
    standard: 'CPHEEO',
    required: true
  },
  {
    id: 'INT-SCR-002',
    name: 'Fine Screen Bar Spacing',
    symbol: 'b_fs',
    category: 'Intake Design',
    subcategory: 'Screening',
    description: 'Clear spacing between fine screen bars.',
    unit: 'mm',
    type: 'input',
    defaultValue: 10,
    min: 2,
    max: 20,
    recommendedMin: 6,
    recommendedMax: 12,
    designCriteria: '6-12 mm for fine mechanical screen.',
    required: true
  },
  {
    id: 'INT-SCR-003',
    name: 'Approach Velocity in Screen Channel',
    symbol: 'v_app',
    category: 'Intake Design',
    subcategory: 'Screening',
    description: 'Water velocity approaching screen channel at minimum water level.',
    unit: 'm/s',
    type: 'input',
    defaultValue: 0.6,
    min: 0.3,
    max: 1.2,
    recommendedMin: 0.6,
    recommendedMax: 0.9,
    designCriteria: 'Self-cleansing velocity >= 0.6 m/s.',
    standard: 'CPHEEO',
    required: true
  },
  {
    id: 'INT-SCR-004',
    name: 'Through-Screen Velocity',
    symbol: 'v_scr',
    category: 'Intake Design',
    subcategory: 'Screening',
    description: 'Velocity passing through screen open area.',
    unit: 'm/s',
    type: 'input',
    defaultValue: 0.8,
    min: 0.4,
    max: 1.2,
    recommendedMax: 1.0,
    designCriteria: 'Maximum 1.0 m/s to prevent floating solids passing through.',
    required: true
  },
  {
    id: 'INT-SCR-005',
    name: 'Screen Head Loss (Kirschmer)',
    symbol: 'h_L_screen',
    category: 'Intake Design',
    subcategory: 'Screening',
    description: 'Calculated hydraulic head loss across screen element.',
    unit: 'm',
    type: 'derived',
    formula: 'beta * (s/b)^(4/3) * (v_app^2 / (2*g)) * sin(alpha)',
    formulaVariables: ['INT-SCR-003'],
    defaultValue: 0.08,
    min: 0.01,
    max: 0.5,
    required: true
  },

  // ==========================================
  // 5. AERATION
  // ==========================================
  {
    id: 'AER-CAS-001',
    name: 'Cascade Aerator Total Drop Height',
    symbol: 'H_aer',
    category: 'Aeration Design',
    subcategory: 'Cascade',
    description: 'Total vertical drop from inlet weir to basin floor.',
    unit: 'm',
    type: 'input',
    defaultValue: 2.0,
    min: 1.0,
    max: 4.5,
    recommendedMin: 1.5,
    recommendedMax: 3.0,
    designCriteria: 'Typically 1.5 - 3.0 m for oxygenation and CO2 stripping.',
    standard: 'AWWA / CPHEEO',
    required: true
  },
  {
    id: 'AER-CAS-002',
    name: 'Cascade Aerator Area Loading Rate',
    symbol: 'ALR_aer',
    category: 'Aeration Design',
    subcategory: 'Cascade',
    description: 'Plan area loading rate per unit total tray area.',
    unit: 'm³/(m²·hr)',
    type: 'input',
    defaultValue: 0.03,
    min: 0.01,
    max: 0.08,
    recommendedMin: 0.02,
    recommendedMax: 0.045,
    designCriteria: '0.02 - 0.045 m3/m2-hr.',
    required: true
  },
  {
    id: 'AER-CAS-003',
    name: 'Iron Oxidation Efficiency',
    symbol: 'Fe_ox_eff',
    category: 'Aeration Design',
    subcategory: 'Cascade',
    description: 'Percentage of Fe2+ converted to Fe3+ precipitable hydroxide.',
    unit: '%',
    type: 'derived',
    defaultValue: 85,
    min: 50,
    max: 98,
    required: true
  },

  // ==========================================
  // 6. COAGULATION & RAPID MIXING
  // ==========================================
  {
    id: 'COA-MIX-001',
    name: 'Rapid Mix Velocity Gradient (G)',
    symbol: 'G_rm',
    category: 'Coagulation Design',
    subcategory: 'Rapid Mix',
    description: 'Velocity gradient G in rapid mixing chamber.',
    unit: 's⁻¹',
    type: 'input',
    defaultValue: 800,
    min: 300,
    max: 1500,
    recommendedMin: 600,
    recommendedMax: 1000,
    designCriteria: '600 - 1000 s⁻¹ for rapid dispersion of coagulants.',
    standard: 'AWWA / CPHEEO',
    standardClause: 'Vol I, Sec 6.2',
    required: true
  },
  {
    id: 'COA-MIX-002',
    name: 'Rapid Mix Detention Time (t)',
    symbol: 't_rm',
    category: 'Coagulation Design',
    subcategory: 'Rapid Mix',
    description: 'Retention time in rapid flash mix chamber.',
    unit: 'seconds',
    type: 'input',
    defaultValue: 45,
    min: 10,
    max: 120,
    recommendedMin: 30,
    recommendedMax: 60,
    designCriteria: '30 - 60 seconds.',
    required: true
  },
  {
    id: 'COA-MIX-003',
    name: 'Rapid Mix Camp Value (GT)',
    symbol: 'GT_rm',
    category: 'Coagulation Design',
    subcategory: 'Rapid Mix',
    description: 'Dimensionless Camp mixing index (G * t).',
    unit: 'dimensionless',
    type: 'derived',
    formula: 'G_rm * t_rm',
    formulaVariables: ['COA-MIX-001', 'COA-MIX-002'],
    defaultValue: 36000,
    min: 10000,
    max: 100000,
    recommendedMin: 20000,
    recommendedMax: 50000,
    required: true
  },
  {
    id: 'COA-MIX-004',
    name: 'Rapid Mix Motor Power Required',
    symbol: 'P_rm',
    category: 'Coagulation Design',
    subcategory: 'Rapid Mix',
    description: 'Shaft power calculated from P = mu * Volume * G^2.',
    unit: 'kW',
    type: 'derived',
    formula: '(viscosity * Volume * G_rm^2) / 1000',
    defaultValue: 18.5,
    min: 0.5,
    max: 150,
    required: true
  },

  // ==========================================
  // 7. FLOCCULATION (3-STAGE TAPERED)
  // ==========================================
  {
    id: 'FLO-BAS-001',
    name: 'Flocculation Total Detention Time',
    symbol: 't_floc',
    category: 'Flocculation Design',
    subcategory: 'Basin Geometry',
    description: 'Total hydraulic residence time across all flocculation stages.',
    unit: 'minutes',
    type: 'input',
    defaultValue: 25,
    min: 15,
    max: 45,
    recommendedMin: 20,
    recommendedMax: 30,
    designCriteria: '20 - 30 minutes for conventional alum flocculation.',
    standard: 'AWWA M51 / CPHEEO',
    required: true
  },
  {
    id: 'FLO-STG-001',
    name: 'Stage 1 Velocity Gradient (G1)',
    symbol: 'G_1',
    category: 'Flocculation Design',
    subcategory: 'Tapered G',
    description: 'Initial rapid flocculation velocity gradient.',
    unit: 's⁻¹',
    type: 'input',
    defaultValue: 70,
    min: 50,
    max: 100,
    recommendedMin: 60,
    recommendedMax: 80,
    required: true
  },
  {
    id: 'FLO-STG-002',
    name: 'Stage 2 Velocity Gradient (G2)',
    symbol: 'G_2',
    category: 'Flocculation Design',
    subcategory: 'Tapered G',
    description: 'Intermediate flocculation velocity gradient.',
    unit: 's⁻¹',
    type: 'input',
    defaultValue: 40,
    min: 30,
    max: 60,
    recommendedMin: 35,
    recommendedMax: 50,
    required: true
  },
  {
    id: 'FLO-STG-003',
    name: 'Stage 3 Velocity Gradient (G3)',
    symbol: 'G_3',
    category: 'Flocculation Design',
    subcategory: 'Tapered G',
    description: 'Final gentle flocculation velocity gradient before clarifier.',
    unit: 's⁻¹',
    type: 'input',
    defaultValue: 15,
    min: 10,
    max: 25,
    recommendedMin: 15,
    recommendedMax: 20,
    required: true
  },

  // ==========================================
  // 8. SEDIMENTATION & TUBE/LAMELLA SETTLER
  // ==========================================
  {
    id: 'SED-CLR-001',
    name: 'Surface Overflow Rate (SOR)',
    symbol: 'SOR',
    category: 'Clarification Design',
    subcategory: 'Sedimentation',
    description: 'Clarifier surface hydraulic loading rate.',
    unit: 'm³/(m²·hr)',
    type: 'input',
    defaultValue: 1.25,
    min: 0.5,
    max: 5.0,
    recommendedMin: 1.0,
    recommendedMax: 1.5,
    designCriteria: '1.0 - 1.5 m3/m2-hr for conventional clarifiers; 3-5 for tube settlers.',
    standard: 'CPHEEO / AWWA',
    required: true
  },
  {
    id: 'SED-CLR-002',
    name: 'Tube Settler Module Incline Angle',
    symbol: 'theta_ts',
    category: 'Clarification Design',
    subcategory: 'Tube Settler',
    description: 'Inclination angle of tube modules from horizontal.',
    unit: 'degrees',
    type: 'input',
    defaultValue: 60,
    min: 55,
    max: 65,
    designCriteria: '60 degrees standard for self-cleaning sludge slide.',
    required: true
  },
  {
    id: 'SED-CLR-003',
    name: 'Launder Weir Loading Rate',
    symbol: 'WLR',
    category: 'Clarification Design',
    subcategory: 'Outlet Weir',
    description: 'Flow per unit linear length of effluent weir.',
    unit: 'm³/(m·hr)',
    type: 'input',
    defaultValue: 10.0,
    min: 5.0,
    max: 20.0,
    recommendedMin: 7.5,
    recommendedMax: 12.0,
    designCriteria: 'Max 12 m3/m-hr to prevent floc pull-over.',
    required: true
  },

  // ==========================================
  // 9. FILTRATION (RAPID GRAVITY SAND & MULTI-MEDIA)
  // ==========================================
  {
    id: 'FIL-RGF-001',
    name: 'Filtration Rate',
    symbol: 'v_filt',
    category: 'Filtration Design',
    subcategory: 'Rapid Sand',
    description: 'Hydraulic filtration loading rate per unit bed surface area.',
    unit: 'm³/(m²·hr)',
    type: 'input',
    defaultValue: 6.0,
    min: 3.0,
    max: 15.0,
    recommendedMin: 5.0,
    recommendedMax: 8.0,
    designCriteria: '5 - 7 m3/m2-hr for single sand; up to 12 for dual media.',
    standard: 'AWWA / CPHEEO',
    required: true
  },
  {
    id: 'FIL-RGF-002',
    name: 'Effective Size of Filter Sand (d10)',
    symbol: 'd10',
    category: 'Filtration Design',
    subcategory: 'Filter Media',
    description: '10th percentile sieve size passing diameter.',
    unit: 'mm',
    type: 'input',
    defaultValue: 0.60,
    min: 0.45,
    max: 1.2,
    recommendedMin: 0.55,
    recommendedMax: 0.70,
    designCriteria: '0.55 - 0.70 mm for RGF.',
    required: true
  },
  {
    id: 'FIL-RGF-003',
    name: 'Uniformity Coefficient (UC = d60/d10)',
    symbol: 'UC',
    category: 'Filtration Design',
    subcategory: 'Filter Media',
    description: 'Ratio of d60 to d10 sieve sizes.',
    unit: 'ratio',
    type: 'input',
    defaultValue: 1.4,
    min: 1.2,
    max: 1.7,
    recommendedMin: 1.3,
    recommendedMax: 1.5,
    designCriteria: 'UC < 1.5 to prevent media stratification issues.',
    required: true
  },
  {
    id: 'FIL-BW-001',
    name: 'Backwash Water Rate',
    symbol: 'v_bw',
    category: 'Filtration Design',
    subcategory: 'Backwash',
    description: 'Water rate during fluidized filter backwash.',
    unit: 'm³/(m²·hr)',
    type: 'input',
    defaultValue: 36.0,
    min: 25.0,
    max: 50.0,
    recommendedMin: 30.0,
    recommendedMax: 42.0,
    designCriteria: '30 - 42 m3/m2-hr for 30-50% bed expansion.',
    required: true
  },
  {
    id: 'FIL-BW-002',
    name: 'Air Scour Rate',
    symbol: 'v_air',
    category: 'Filtration Design',
    subcategory: 'Backwash',
    description: 'Compressed air flow rate per m2 filter surface.',
    unit: 'm³/(m²·hr)',
    type: 'input',
    defaultValue: 50.0,
    min: 35.0,
    max: 70.0,
    recommendedMin: 45.0,
    recommendedMax: 60.0,
    required: true
  },

  // ==========================================
  // 10. DISINFECTION & CHLORINATION
  // ==========================================
  {
    id: 'DIS-CHL-001',
    name: 'Chlorine Design Dose',
    symbol: 'Dose_Cl2',
    category: 'Disinfection Design',
    subcategory: 'Chlorination',
    description: 'Applied chlorine dosage in raw/treated water.',
    unit: 'mg/L',
    type: 'input',
    defaultValue: 3.5,
    min: 0.5,
    max: 10.0,
    recommendedMin: 2.0,
    recommendedMax: 5.0,
    designCriteria: 'To achieve demand + minimum 0.5 - 1.0 mg/L free residual.',
    standard: 'WHO / CPHEEO',
    required: true
  },
  {
    id: 'DIS-CHL-002',
    name: 'Contact Time (T)',
    symbol: 'T_contact',
    category: 'Disinfection Design',
    subcategory: 'Chlorination',
    description: 'Theoretical hydraulic detention time in chlorine contact tank.',
    unit: 'minutes',
    type: 'input',
    defaultValue: 30,
    min: 15,
    max: 120,
    recommendedMin: 30,
    recommendedMax: 60,
    designCriteria: 'Minimum 30 minutes at peak flow.',
    required: true
  },
  {
    id: 'DIS-CHL-003',
    name: 'Baffle Factor (t10 / t)',
    symbol: 'BF',
    category: 'Disinfection Design',
    subcategory: 'Chlorination',
    description: 'Ratio of 10% tracer arrival time to theoretical residence time.',
    unit: 'ratio',
    type: 'input',
    defaultValue: 0.7,
    min: 0.1,
    max: 0.9,
    recommendedMin: 0.5,
    recommendedMax: 0.8,
    designCriteria: '0.7 for serpentine baffled contact basin.',
    standard: 'US EPA Disinfection Profiling',
    required: true
  },
  {
    id: 'DIS-CHL-004',
    name: 'Achieved CT Value',
    symbol: 'CT_achieved',
    category: 'Disinfection Design',
    subcategory: 'Chlorination',
    description: 'Calculated disinfectant concentration * effective time (C * T10).',
    unit: 'mg·min/L',
    type: 'derived',
    formula: 'Resid_Cl2 * (T_contact * BF)',
    formulaVariables: ['DIS-CHL-001', 'DIS-CHL-002', 'DIS-CHL-003'],
    defaultValue: 21.0,
    min: 5.0,
    max: 200.0,
    designCriteria: 'Must exceed required EPA CT table for target Giardia/Virus log inactivation.',
    required: true
  },

  // ==========================================
  // 11. CLEAR WATER RESERVOIR (CWR)
  // ==========================================
  {
    id: 'CWR-VOL-001',
    name: 'Required CWR Storage Hours',
    symbol: 't_cwr',
    category: 'Clear Water Reservoir',
    subcategory: 'Storage Volume',
    description: 'Storage duration in hours of average plant output.',
    unit: 'hours',
    type: 'input',
    defaultValue: 8.0,
    min: 2.0,
    max: 24.0,
    recommendedMin: 4.0,
    recommendedMax: 12.0,
    designCriteria: '4 - 8 hours storage for balancing high lift pumping.',
    standard: 'CPHEEO / AWWA',
    required: true
  },
  {
    id: 'CWR-VOL-002',
    name: 'Effective Storage Volume',
    symbol: 'V_cwr',
    category: 'Clear Water Reservoir',
    subcategory: 'Storage Volume',
    description: 'Total usable liquid volume in clear water tank.',
    unit: 'm³',
    type: 'derived',
    formula: '(Q_mld * 1000) * (t_cwr / 24)',
    formulaVariables: ['DES-CAP-001', 'CWR-VOL-001'],
    defaultValue: 16666.67,
    min: 100,
    max: 200000,
    required: true
  },

  // ==========================================
  // 12. CHEMICAL DOSING SYSTEMS
  // ==========================================
  {
    id: 'CHM-ALU-001',
    name: 'Alum Commercial Dose',
    symbol: 'Dose_alum',
    category: 'Chemical Dosing',
    subcategory: 'Coagulant',
    description: 'Commercial alum [Al2(SO4)3·18H2O] dosage.',
    unit: 'mg/L',
    type: 'input',
    defaultValue: 35.0,
    min: 5.0,
    max: 150.0,
    recommendedMin: 15.0,
    recommendedMax: 60.0,
    designCriteria: 'Determined from Jar Test optimal dose.',
    required: true
  },
  {
    id: 'CHM-ALU-002',
    name: 'Alum Solution Concentration',
    symbol: 'C_alum_sol',
    category: 'Chemical Dosing',
    subcategory: 'Coagulant',
    description: 'Concentration of liquid alum solution in dosing tanks.',
    unit: '% w/v',
    type: 'input',
    defaultValue: 10.0,
    min: 2.0,
    max: 20.0,
    recommendedMin: 5.0,
    recommendedMax: 10.0,
    required: true
  },
  {
    id: 'CHM-ALU-003',
    name: 'Alum Daily Bulk Consumption',
    symbol: 'W_alum_day',
    category: 'Chemical Dosing',
    subcategory: 'Coagulant',
    description: 'Mass of solid alum consumed per day.',
    unit: 'kg/day',
    type: 'derived',
    formula: '(Q_mld * 1000) * Dose_alum / 1000',
    formulaVariables: ['DES-CAP-001', 'CHM-ALU-001'],
    defaultValue: 1750.0,
    min: 10,
    max: 50000,
    required: true
  },

  // ==========================================
  // 13. PUMPING SYSTEMS & HYDRAULICS
  // ==========================================
  {
    id: 'PMP-RAW-001',
    name: 'Raw Water Pump Total Dynamic Head (TDH)',
    symbol: 'TDH_raw',
    category: 'Pumping System',
    subcategory: 'Raw Water Pump',
    description: 'Static lift + friction + minor losses for raw water intake pumping.',
    unit: 'm',
    type: 'input',
    defaultValue: 28.5,
    min: 5.0,
    max: 150.0,
    required: true
  },
  {
    id: 'PMP-RAW-002',
    name: 'Pump Wire-to-Water Efficiency',
    symbol: 'eta_pump',
    category: 'Pumping System',
    subcategory: 'Efficiency',
    description: 'Combined pump hydraulic and electric motor efficiency.',
    unit: '%',
    type: 'input',
    defaultValue: 75.0,
    min: 50.0,
    max: 90.0,
    recommendedMin: 70.0,
    recommendedMax: 82.0,
    required: true
  },
  {
    id: 'PMP-RAW-003',
    name: 'Raw Water Pumping Motor Rating',
    symbol: 'Power_pmp_raw',
    category: 'Pumping System',
    subcategory: 'Power',
    description: 'Electrical motor power consumed by operating raw water pumps.',
    unit: 'kW',
    type: 'derived',
    formula: '(Q_ls * 9.81 * TDH_raw) / (10 * eta_pump)',
    formulaVariables: ['DES-CAP-003', 'PMP-RAW-001', 'PMP-RAW-002'],
    defaultValue: 219.8,
    min: 1.0,
    max: 2000.0,
    required: true
  },

  // ==========================================
  // 14. SLUDGE & MASS BALANCE
  // ==========================================
  {
    id: 'SLU-SOL-001',
    name: 'Daily Dry Sludge Production',
    symbol: 'M_sludge_dry',
    category: 'Sludge Management',
    subcategory: 'Solids Production',
    description: 'Total dry solids generated per day (TSS removed + Alum hydroxide + chemicals).',
    unit: 'kg dry solids/day',
    type: 'derived',
    formula: '(Q_mld * 1000) * (TSS_removed + 0.26 * Dose_alum) / 1000',
    defaultValue: 6450.0,
    min: 50,
    max: 200000,
    required: true
  },

  // ==========================================
  // 15. ENERGY & FINANCIALS
  // ==========================================
  {
    id: 'ENG-TOT-001',
    name: 'Specific Energy Consumption',
    symbol: 'SEC',
    category: 'Energy Analysis',
    subcategory: 'Specific Energy',
    description: 'Total electrical energy consumed per m3 of treated water.',
    unit: 'kWh/m³',
    type: 'derived',
    defaultValue: 0.38,
    min: 0.1,
    max: 2.5,
    recommendedMin: 0.25,
    recommendedMax: 0.55,
    designCriteria: '< 0.45 kWh/m3 for conventional surface water WTP.',
    required: true
  },
  {
    id: 'COST-CAP-001',
    name: 'Total Project CAPEX',
    symbol: 'CAPEX_total',
    category: 'Cost Estimation',
    subcategory: 'CAPEX',
    description: 'Estimated civil, mechanical, electrical, and instrumentation capital cost.',
    unit: 'USD',
    type: 'derived',
    defaultValue: 18500000,
    min: 50000,
    max: 1000000000,
    required: true
  },

  // ==========================================
  // 16. HYDRAULICS, PIPING & PUMPING ENGINE
  // ==========================================
  {
    id: 'HYD-PIP-001',
    name: 'Raw Water Main Diameter',
    symbol: 'D_raw',
    category: 'Hydraulics',
    subcategory: 'Piping',
    description: 'Internal diameter of raw water transmission pipe from intake to aerator.',
    unit: 'mm',
    type: 'input',
    defaultValue: 900,
    min: 100,
    max: 3000,
    designCriteria: 'Target velocity 0.8 to 1.5 m/s.',
    standard: 'AWWA M11 / CPHEEO 2021',
    required: true
  },
  {
    id: 'HYD-PIP-002',
    name: 'Raw Water Main Flow Velocity',
    symbol: 'V_raw',
    category: 'Hydraulics',
    subcategory: 'Piping',
    description: 'Flow velocity in raw water transmission pipe.',
    unit: 'm/s',
    type: 'derived',
    formula: 'Q_m3s / ((PI * (D_raw/1000)^2) / 4)',
    defaultValue: 0.91,
    min: 0.3,
    max: 4.0,
    recommendedMin: 0.8,
    recommendedMax: 1.5,
    designCriteria: '0.8 - 1.5 m/s to prevent siltation and excess head loss.',
    standard: 'CPHEEO 2021',
    required: true
  },
  {
    id: 'HYD-PIP-003',
    name: 'Hazen-Williams C Roughness Coefficient',
    symbol: 'C_hw',
    category: 'Hydraulics',
    subcategory: 'Piping',
    description: 'Hazen-Williams C factor for 10-30 year aged DI/Steel pipe.',
    unit: 'dimensionless',
    type: 'input',
    defaultValue: 130,
    min: 80,
    max: 150,
    designCriteria: '130 for Cement Mortar Lined Ductile Iron.',
    standard: 'AWWA M11',
    required: true
  },
  {
    id: 'HYD-PIP-004',
    name: 'Pipeline Friction Head Loss (Hazen-Williams)',
    symbol: 'h_f_hw',
    category: 'Hydraulics',
    subcategory: 'Piping',
    description: 'Friction head loss along pipeline calculated via Hazen-Williams equation.',
    unit: 'm',
    type: 'derived',
    formula: '10.67 * L * Q^1.852 / (C^1.852 * D^4.87)',
    defaultValue: 1.18,
    min: 0.01,
    max: 100,
    required: true
  },
  {
    id: 'HYD-PIP-005',
    name: 'Darcy-Weisbach Friction Factor',
    symbol: 'f_darcy',
    category: 'Hydraulics',
    subcategory: 'Piping',
    description: 'Darcy-Weisbach friction factor f derived via Swamee-Jain Colebrook equation.',
    unit: 'dimensionless',
    type: 'derived',
    defaultValue: 0.016,
    min: 0.008,
    max: 0.08,
    required: true
  },
  {
    id: 'HYD-PIP-006',
    name: 'Pipe Reynolds Number',
    symbol: 'Re',
    category: 'Hydraulics',
    subcategory: 'Piping',
    description: 'Dimensionless ratio of inertial forces to viscous forces in pipe flow.',
    unit: 'dimensionless',
    type: 'derived',
    defaultValue: 819000,
    min: 100,
    max: 10000000,
    required: true
  },
  {
    id: 'HYD-PIP-007',
    name: 'Fittings Total Minor Loss Coefficient Sum',
    symbol: 'K_total',
    category: 'Hydraulics',
    subcategory: 'Fittings',
    description: 'Cumulative sum of K resistance factors for elbows, tees, valves, and entrances.',
    unit: 'dimensionless',
    type: 'input',
    defaultValue: 4.5,
    min: 0.1,
    max: 50,
    required: true
  },
  {
    id: 'HYD-PIP-008',
    name: 'Minor Head Loss',
    symbol: 'h_m',
    category: 'Hydraulics',
    subcategory: 'Fittings',
    description: 'Head loss due to pipe fittings and valves = K * V^2 / 2g.',
    unit: 'm',
    type: 'derived',
    formula: 'K_total * (V^2 / (2 * 9.81))',
    defaultValue: 0.19,
    min: 0.0,
    max: 20,
    required: true
  },
  {
    id: 'HYD-PMP-001',
    name: 'High Lift Pump Rated Flow',
    symbol: 'Q_pump',
    category: 'Pumping',
    subcategory: 'High Lift',
    description: 'Duty design flow rate for individual high lift pump unit.',
    unit: 'm³/hr',
    type: 'derived',
    formula: 'Q_m3hr / DutyPumps',
    defaultValue: 1041.67,
    min: 10,
    max: 10000,
    required: true
  },
  {
    id: 'HYD-PMP-002',
    name: 'High Lift Pump Total Dynamic Head (TDH)',
    symbol: 'TDH',
    category: 'Pumping',
    subcategory: 'High Lift',
    description: 'Total dynamic head required by pump including static lift, friction, and minor losses.',
    unit: 'm',
    type: 'input',
    defaultValue: 45.0,
    min: 5,
    max: 250,
    required: true
  },
  {
    id: 'HYD-PMP-003',
    name: 'High Lift Pump Hydraulic Power',
    symbol: 'P_hyd',
    category: 'Pumping',
    subcategory: 'Power',
    description: 'Water horsepower converted to electrical hydraulic power output.',
    unit: 'kW',
    type: 'derived',
    formula: '(rho * g * Q * TDH) / 1000',
    defaultValue: 127.8,
    min: 1,
    max: 5000,
    required: true
  },
  {
    id: 'HYD-PMP-004',
    name: 'High Lift Pump Shaft Power',
    symbol: 'P_shaft',
    category: 'Pumping',
    subcategory: 'Power',
    description: 'Brake power required at pump shaft considering pump efficiency.',
    unit: 'kW',
    type: 'derived',
    formula: 'P_hyd / (Eff_pump / 100)',
    defaultValue: 152.1,
    min: 1,
    max: 6000,
    required: true
  },
  {
    id: 'HYD-PMP-005',
    name: 'High Lift Motor Electrical Power',
    symbol: 'P_motor',
    category: 'Pumping',
    subcategory: 'Power',
    description: 'Total motor electrical power input.',
    unit: 'kW',
    type: 'derived',
    formula: 'P_shaft / (Eff_motor / 100)',
    defaultValue: 160.1,
    min: 1,
    max: 7000,
    required: true
  },
  {
    id: 'HYD-PMP-006',
    name: 'Net Positive Suction Head Available (NPSHa)',
    symbol: 'NPSHa',
    category: 'Pumping',
    subcategory: 'NPSH',
    description: 'Available absolute head at pump suction inlet above liquid vapor pressure.',
    unit: 'm',
    type: 'derived',
    defaultValue: 8.45,
    min: 0.5,
    max: 20,
    recommendedMin: 3.5,
    designCriteria: 'NPSHa must exceed NPSHr by at least 1.0 m margin.',
    standard: 'HI 9.6.1',
    required: true
  },
  {
    id: 'HYD-PMP-007',
    name: 'Net Positive Suction Head Required (NPSHr)',
    symbol: 'NPSHr',
    category: 'Pumping',
    subcategory: 'NPSH',
    description: 'Manufacturer required minimum suction head to prevent cavitation.',
    unit: 'm',
    type: 'input',
    defaultValue: 3.2,
    min: 0.5,
    max: 15,
    required: true
  },
  {
    id: 'HYD-SUR-001',
    name: 'Transient Water Hammer Wave Celerity',
    symbol: 'a_wave',
    category: 'Surge',
    subcategory: 'Transient',
    description: 'Acoustic pressure wave speed propagating through pipe fluid.',
    unit: 'm/s',
    type: 'derived',
    defaultValue: 1020,
    min: 200,
    max: 1400,
    required: true
  },
  {
    id: 'HYD-SUR-002',
    name: 'Joukowsky Transient Surge Head Rise',
    symbol: 'deltaH_surge',
    category: 'Surge',
    subcategory: 'Transient',
    description: 'Maximum pressure head rise following instantaneous flow stoppage = a * deltaV / g.',
    unit: 'm',
    type: 'derived',
    formula: '(a_wave * V_initial) / 9.81',
    defaultValue: 156.1,
    min: 5,
    max: 500,
    required: true
  },
  {
    id: 'HYD-SUR-003',
    name: 'Peak Transient Total Line Pressure',
    symbol: 'P_peak_surge',
    category: 'Surge',
    subcategory: 'Transient',
    description: 'Combined operating pressure + Joukowsky surge pressure.',
    unit: 'bar',
    type: 'derived',
    defaultValue: 19.8,
    min: 1,
    max: 100,
    required: true
  },

  // ==========================================
  // 12. PHASE 05 - CHEMICAL TREATMENT & WATER QUALITY
  // ==========================================
  {
    id: 'CHEM-ALU-001',
    name: 'Alum Active Dosing Rate',
    symbol: 'D_alum',
    category: 'Chemical Dosing',
    subcategory: 'Coagulants',
    description: 'Active alum chemical dose applied at flash rapid mixer.',
    unit: 'mg/L',
    type: 'input',
    defaultValue: 35.0,
    min: 5.0,
    max: 150.0,
    standard: 'AWWA B403 / CPHEEO 2021',
    required: true
  },
  {
    id: 'CHEM-ALU-002',
    name: 'Alum Daily Commercial Consumption',
    symbol: 'M_alum_day',
    category: 'Chemical Dosing',
    subcategory: 'Coagulants',
    description: 'Commercial liquid alum solution required per day.',
    unit: 'kg/day',
    type: 'derived',
    formula: '(D_alum * Q_mld * 1000) / (0.48 * 1000)',
    defaultValue: 3645.8,
    min: 50.0,
    max: 50000.0,
    required: true
  },
  {
    id: 'CHEM-FER-001',
    name: 'Ferric Chloride Dosing Rate',
    symbol: 'D_ferric',
    category: 'Chemical Dosing',
    subcategory: 'Coagulants',
    description: 'Active ferric chloride dose applied at rapid mixer.',
    unit: 'mg/L',
    type: 'input',
    defaultValue: 25.0,
    min: 5.0,
    max: 120.0,
    standard: 'AWWA B407',
    required: true
  },
  {
    id: 'CHEM-LIM-001',
    name: 'Hydrated Lime Dosing Rate',
    symbol: 'D_lime',
    category: 'Chemical Dosing',
    subcategory: 'Alkalinity',
    description: 'Hydrated lime dose for raw water alkalinity supplementation and pH stabilization.',
    unit: 'mg/L',
    type: 'input',
    defaultValue: 15.0,
    min: 0.0,
    max: 100.0,
    standard: 'AWWA B202',
    required: true
  },
  {
    id: 'CHEM-CL2-001',
    name: 'Gas Chlorine Applied Post-Disinfection Dose',
    symbol: 'D_cl2',
    category: 'Disinfection',
    subcategory: 'Chlorination',
    description: 'Liquefied gas chlorine applied at clear water contact tank inlet.',
    unit: 'mg/L',
    type: 'input',
    defaultValue: 3.5,
    min: 0.5,
    max: 10.0,
    standard: 'AWWA B301 / CPHEEO 2021',
    required: true
  },
  {
    id: 'CHEM-CL2-002',
    name: 'Effective Disinfection CT Achieved',
    symbol: 'CT_achieved',
    category: 'Disinfection',
    subcategory: 'CT Calculation',
    description: 'Product of outlet free residual chlorine and effective T10 contact time.',
    unit: 'mg·min/L',
    type: 'derived',
    defaultValue: 67.5,
    min: 5.0,
    max: 500.0,
    standard: 'US EPA SWTR',
    required: true
  },
  {
    id: 'CHEM-MEM-001',
    name: 'RO Membrane Flux Rate',
    symbol: 'J_ro',
    category: 'Membranes',
    subcategory: 'Reverse Osmosis',
    description: 'Permeate volumetric flux per unit membrane area.',
    unit: 'LMH',
    type: 'input',
    defaultValue: 18.0,
    min: 10.0,
    max: 30.0,
    standard: 'AWWA M46',
    required: true
  },
  {
    id: 'CHEM-MEM-002',
    name: 'RO System Recovery Rate',
    symbol: 'R_ro',
    category: 'Membranes',
    subcategory: 'Reverse Osmosis',
    description: 'Percentage ratio of product permeate flow to total feed flow.',
    unit: '%',
    type: 'input',
    defaultValue: 75.0,
    min: 30.0,
    max: 90.0,
    standard: 'AWWA M46',
    required: true
  },

  // ==========================================
  // PHASE 06 - MECHANICAL, EQUIPMENT & M&E ENGINE
  // ==========================================
  {
    id: 'EQP-PWR-001',
    name: 'Total Connected Plant Electrical Load',
    symbol: 'P_connected',
    category: 'Equipment',
    subcategory: 'Electrical Power',
    description: 'Sum of nameplate motor ratings across all duty and standby equipment.',
    unit: 'kW',
    type: 'derived',
    defaultValue: 850.0,
    min: 10.0,
    max: 10000.0,
    standard: 'IEEE 141 / CPHEEO 2021',
    required: true
  },
  {
    id: 'EQP-PWR-002',
    name: 'Total Normal Operating Power Consumption',
    symbol: 'P_operating',
    category: 'Equipment',
    subcategory: 'Electrical Power',
    description: 'Active power draw during normal 24h design operating condition.',
    unit: 'kW',
    type: 'derived',
    defaultValue: 585.5,
    min: 5.0,
    max: 8000.0,
    standard: 'CPHEEO Vol I Sec 8',
    required: true
  },
  {
    id: 'EQP-PWR-003',
    name: 'Plant Specific Energy Consumption',
    symbol: 'E_spec',
    category: 'Equipment',
    subcategory: 'Energy Efficiency',
    description: 'Electrical energy required to treat and produce 1 cubic meter of potable water.',
    unit: 'kWh/m³',
    type: 'derived',
    defaultValue: 0.281,
    min: 0.05,
    max: 3.50,
    standard: 'AWWA M51 / CPHEEO 2021',
    required: true
  },
  {
    id: 'EQP-MTR-001',
    name: 'Pump Motor Service Factor Margin',
    symbol: 'SF_motor',
    category: 'Equipment',
    subcategory: 'Motor Sizing',
    description: 'Design power margin multiplier applied to pump shaft power for motor selection.',
    unit: 'ratio',
    type: 'input',
    defaultValue: 1.15,
    min: 1.10,
    max: 1.30,
    standard: 'NEMA MG1 / IEC 60034',
    required: true
  },
  {
    id: 'EQP-RED-001',
    name: 'Equipment N-1 Standby Capacity Ratio',
    symbol: 'R_N1',
    category: 'Equipment',
    subcategory: 'Redundancy',
    description: 'Ratio of available capacity during single unit failure to design required capacity.',
    unit: '%',
    type: 'derived',
    defaultValue: 100.0,
    min: 50.0,
    max: 150.0,
    standard: 'Ten State Standards / CPHEEO',
    required: true
  },
  {
    id: 'EQP-VLV-001',
    name: 'Filter Valve Velocity Target',
    symbol: 'v_valve',
    category: 'Equipment',
    subcategory: 'Valves',
    description: 'Fluid flow velocity through process butterfly and gate valves.',
    unit: 'm/s',
    type: 'input',
    defaultValue: 2.0,
    min: 0.5,
    max: 3.0,
    standard: 'AWWA C504 / C515',
    required: true
  },
  {
    id: 'EQP-BLW-001',
    name: 'Backwash Air Scour Blower Operating Pressure',
    symbol: 'P_scour',
    category: 'Equipment',
    subcategory: 'Blowers',
    description: 'Air blower delivery pressure accounting for water depth and pipe friction.',
    unit: 'kPa',
    type: 'input',
    defaultValue: 45.0,
    min: 20.0,
    max: 80.0,
    standard: 'CPHEEO 2021',
    required: true
  },
  {
    id: 'EQP-ACC-001',
    name: 'Minimum Maintenance Access Clearance',
    symbol: 'W_clearance',
    category: 'Equipment',
    subcategory: 'Maintenance',
    description: 'Minimum walkway and equipment pull-out clearance required around major machinery.',
    unit: 'm',
    type: 'input',
    defaultValue: 1.5,
    min: 0.8,
    max: 3.0,
    standard: 'OSHA 1910 / CPHEEO Vol I',
    required: true
  },

  // ==========================================
  // 13. ELECTRICAL, INSTRUMENTATION & AUTOMATION (PHASE 07)
  // ==========================================
  {
    id: 'ELE-VOLT-001',
    name: 'Low Voltage Supply Rating',
    symbol: 'V_lv',
    category: 'Electrical',
    subcategory: 'Supply Voltage',
    description: 'Standard 3-phase low voltage distribution level at motor control centers.',
    unit: 'V',
    type: 'input',
    defaultValue: 415,
    min: 380,
    max: 480,
    standard: 'IEC 60038',
    required: true
  },
  {
    id: 'ELE-FREQ-001',
    name: 'Grid System Frequency',
    symbol: 'f_grid',
    category: 'Electrical',
    subcategory: 'Supply Voltage',
    description: 'Utility grid AC power frequency.',
    unit: 'Hz',
    type: 'input',
    defaultValue: 50,
    min: 50,
    max: 60,
    standard: 'IEC 60038',
    required: true
  },
  {
    id: 'ELE-LOAD-001',
    name: 'Total Plant Connected Load',
    symbol: 'P_connected',
    category: 'Electrical',
    subcategory: 'Load Schedule',
    description: 'Sum of nameplate motor electrical ratings for all installed equipment.',
    unit: 'kW',
    type: 'derived',
    defaultValue: 585.0,
    min: 10,
    max: 20000,
    standard: 'IEEE 141',
    required: true
  },
  {
    id: 'ELE-LOAD-002',
    name: 'Total Plant Operating Demand Load',
    symbol: 'P_demand',
    category: 'Electrical',
    subcategory: 'Load Schedule',
    description: 'Expected maximum simultaneous operating electrical power demand.',
    unit: 'kW',
    type: 'derived',
    defaultValue: 480.0,
    min: 10,
    max: 18000,
    standard: 'IEEE 141',
    required: true
  },
  {
    id: 'ELE-TRF-001',
    name: 'Main Transformer Rating',
    symbol: 'S_trf',
    category: 'Electrical',
    subcategory: 'Substation',
    description: 'Design step-down transformer capacity in kVA.',
    unit: 'kVA',
    type: 'derived',
    defaultValue: 800,
    min: 100,
    max: 10000,
    standard: 'IEC 60076',
    required: true
  },
  {
    id: 'ELE-GEN-001',
    name: 'Emergency Generator Capacity',
    symbol: 'S_gen',
    category: 'Electrical',
    subcategory: 'Backup Power',
    description: 'Diesel generator set capacity rated for essential & critical WTP loads.',
    unit: 'kVA',
    type: 'derived',
    defaultValue: 630,
    min: 50,
    max: 5000,
    standard: 'ISO 8528',
    required: true
  },
  {
    id: 'ELE-UPS-001',
    name: 'UPS Battery Autonomy Time',
    symbol: 't_ups',
    category: 'Electrical',
    subcategory: 'UPS',
    description: 'Backup battery autonomy duration for PLC, SCADA & emergency instrumentation.',
    unit: 'hr',
    type: 'input',
    defaultValue: 4,
    min: 1,
    max: 24,
    standard: 'IEC 62040',
    required: true
  },
  {
    id: 'ELE-CBL-001',
    name: 'Max Allowable Cable Voltage Drop',
    symbol: 'VD_max',
    category: 'Electrical',
    subcategory: 'Cables',
    description: 'Maximum allowable percentage voltage drop from MCC to motor terminals.',
    unit: '%',
    type: 'input',
    defaultValue: 3.0,
    min: 1.0,
    max: 5.0,
    standard: 'BS 7671 / IEC 60364',
    required: true
  },
  {
    id: 'INS-FLOW-001',
    name: 'Flow Meter Accuracy Class',
    symbol: 'Acc_flow',
    category: 'Instrumentation',
    subcategory: 'Flow',
    description: 'Measurement accuracy tolerance for electromagnetic inline flow meters.',
    unit: '%',
    type: 'input',
    defaultValue: 0.2,
    min: 0.1,
    max: 1.0,
    standard: 'ISO 9104',
    required: true
  },
  {
    id: 'PLC-IO-001',
    name: 'PLC I/O Spare Capacity Margin',
    symbol: 'Margin_io',
    category: 'Control & PLC',
    subcategory: 'PLC Architecture',
    description: 'Percentage of spare wired I/O channels reserved for future expansion.',
    unit: '%',
    type: 'input',
    defaultValue: 20,
    min: 10,
    max: 50,
    standard: 'ISA-88 / IEC 61131',
    required: true
  },
  // ==========================================
  // PHASE 09: SLUDGE & ENVIRONMENTAL ENGINE
  // ==========================================
  {
    id: 'SLD-GEN-001',
    name: 'Total Dry Sludge Solids Generation',
    symbol: 'M_ds_dry',
    category: 'Sludge & Waste',
    subcategory: 'Solids Generation',
    description: 'Total daily dry solids generated from raw water TSS capture and chemical precipitation.',
    unit: 'kg/day',
    type: 'derived',
    formula: 'Q_mld * 1000 * (TSS_raw * 0.98 + 0.26 * Dose_alum) / 1000',
    formulaVariables: ['DES-CAP-001'],
    defaultValue: 6300,
    min: 10,
    max: 500000,
    standard: 'AWWA M51 / CPHEEO 2021',
    required: true
  },
  {
    id: 'SLD-THK-001',
    name: 'Gravity Thickener Solids Loading Rate',
    symbol: 'SLR_thk',
    category: 'Sludge & Waste',
    subcategory: 'Thickening',
    description: 'Design solids loading rate per unit surface area for continuous gravity thickening.',
    unit: 'kg/m²·day',
    type: 'input',
    defaultValue: 35.0,
    min: 15.0,
    max: 60.0,
    standard: 'WEF Manual of Practice 8',
    required: true
  },
  {
    id: 'SLD-DEW-001',
    name: 'Dewatered Sludge Cake Solids Content',
    symbol: 'S_cake',
    category: 'Sludge & Waste',
    subcategory: 'Dewatering',
    description: 'Dry solids concentration percentage in dewatered cake from filter press or centrifuge.',
    unit: '%',
    type: 'input',
    defaultValue: 30.0,
    min: 15.0,
    max: 45.0,
    standard: 'WEF MOP 8',
    required: true
  },
  {
    id: 'SLD-POL-001',
    name: 'Polymer Conditioning Dosage',
    symbol: 'D_poly',
    category: 'Sludge & Waste',
    subcategory: 'Conditioning',
    description: 'Active organic polymer dosage per dry tonne of sludge solids.',
    unit: 'kg/tDS',
    type: 'input',
    defaultValue: 3.5,
    min: 1.0,
    max: 8.0,
    standard: 'AWWA M51',
    required: true
  },
  {
    id: 'ENV-REC-001',
    name: 'Filter Backwash Water Recovery Efficiency',
    symbol: 'Eta_rec',
    category: 'Environmental & Waste',
    subcategory: 'Water Recovery',
    description: 'Percentage of filter backwash waste water recovered and recycled back to headworks.',
    unit: '%',
    type: 'input',
    defaultValue: 95.0,
    min: 50.0,
    max: 99.0,
    standard: 'CPHEEO 2021 / USEPA Filter Backwash Recycling Rule',
    required: true
  },
  // ==========================================
  // PHASE 10 - BOQ, COST, PROCUREMENT & CONSTRUCTION
  // ==========================================
  {
    id: 'BOQ-TOT-001',
    name: 'Total Quantity Takeoff Items Count',
    symbol: 'N_boq',
    category: 'BOQ & Cost',
    subcategory: 'Takeoff',
    description: 'Total number of discrete BOQ quantity items extracted from design modules.',
    unit: 'Items',
    type: 'derived',
    defaultValue: 30,
    required: true
  },
  {
    id: 'CST-CPX-001',
    name: 'Total Plant Capital Expenditure (CAPEX)',
    symbol: 'CAPEX_total',
    category: 'BOQ & Cost',
    subcategory: 'CAPEX',
    description: 'Total direct and indirect capital expenditure estimate for WTP construction.',
    unit: 'USD',
    type: 'derived',
    defaultValue: 15000000,
    required: true
  },
  {
    id: 'CST-OPX-001',
    name: 'Total Annual Operating Expenditure (OPEX)',
    symbol: 'OPEX_annual',
    category: 'BOQ & Cost',
    subcategory: 'OPEX',
    description: 'Annual operating cost covering energy, chemicals, maintenance, labour and sludge.',
    unit: 'USD/year',
    type: 'derived',
    defaultValue: 850000,
    required: true
  },
  {
    id: 'CST-LCC-001',
    name: '25-Year Present Value Life-Cycle Cost (LCC)',
    symbol: 'LCC_25yr',
    category: 'BOQ & Cost',
    subcategory: 'LCC',
    description: 'Total Present Value Life-Cycle Cost including CAPEX, OPEX and major equipment replacements.',
    unit: 'USD',
    type: 'derived',
    defaultValue: 26000000,
    required: true
  },
  {
    id: 'PRC-LEAD-001',
    name: 'Long-Lead Procurement Threshold',
    symbol: 'T_lead',
    category: 'Procurement',
    subcategory: 'Schedule',
    description: 'Lead time threshold in weeks to classify equipment as long-lead items.',
    unit: 'Weeks',
    type: 'input',
    defaultValue: 16,
    min: 8,
    max: 52,
    required: true
  },
  {
    id: 'CNS-SCH-001',
    name: 'Master Construction Schedule Duration',
    symbol: 'T_const',
    category: 'Construction',
    subcategory: 'Schedule',
    description: 'Total estimated construction duration from site mobilization to wet commissioning.',
    unit: 'Days',
    type: 'derived',
    defaultValue: 540,
    required: true
  },
  // ==========================================
  // PHASE 11 - ENGINEERING DRAWINGS, BIM, GIS & 3D DIGITAL TWIN
  // ==========================================
  {
    id: 'DWG-SET-001',
    name: 'Total 2D Engineering Drawings Count',
    symbol: 'N_dwg',
    category: 'Drawings & BIM',
    subcategory: 'Drawings',
    description: 'Total generated 2D engineering drawings across all disciplines.',
    unit: 'Drawings',
    type: 'derived',
    defaultValue: 12,
    required: true
  },
  {
    id: 'CAD-LAY-001',
    name: 'Configurable CAD Layer Count',
    symbol: 'N_layers',
    category: 'Drawings & BIM',
    subcategory: 'CAD',
    description: 'Number of standardized CAD layers for 2D drafting and plot control.',
    unit: 'Layers',
    type: 'derived',
    defaultValue: 19,
    required: true
  },
  {
    id: 'GIS-CRS-001',
    name: 'Project Coordinate Reference System',
    symbol: 'CRS_proj',
    category: 'GIS & Terrain',
    subcategory: 'Coordinates',
    description: 'Geographic projected CRS for spatial mapping and GIS integration.',
    unit: 'text',
    type: 'input',
    defaultValue: 'EPSG_32645_UTM_ZONE_45N',
    required: true
  },
  {
    id: 'BIM-IFC-001',
    name: 'Registered BIM IFC Objects Count',
    symbol: 'N_ifc',
    category: 'Drawings & BIM',
    subcategory: 'BIM',
    description: 'Count of physical engineering objects mapped to IFC GUIDs and property sets.',
    unit: 'Objects',
    type: 'derived',
    defaultValue: 12,
    required: true
  },
  {
    id: 'TWN-ASB-001',
    name: 'As-Built Digital Twin Variance Status',
    symbol: 'Status_asbuilt',
    category: '3D & Digital Twin',
    subcategory: 'As-Built',
    description: 'Design vs As-built measurement comparison approval status.',
    unit: 'status',
    type: 'derived',
    defaultValue: 'APPROVED',
    required: true
  },
  {
    id: 'GIS-DEM-001',
    name: 'Terrain Contour Interval',
    symbol: 'Int_contour',
    category: 'GIS & Terrain',
    subcategory: 'Contours',
    description: 'Elevation contour line generation interval for site grading and DEM.',
    unit: 'm',
    type: 'input',
    defaultValue: 0.5,
    min: 0.1,
    max: 5.0,
    required: true
  },
  {
    id: 'CAD-DIM-001',
    name: 'Geometry Dimension Engine Status',
    symbol: 'Status_dim',
    category: 'Drawings & BIM',
    subcategory: 'Dimensions',
    description: 'Dimension extraction directly from engineering geometry.',
    unit: 'status',
    type: 'derived',
    defaultValue: 'VERIFIED',
    required: true
  },
  {
    id: 'TWN-3D-001',
    name: '3D Digital Twin Scene Mesh Elements',
    symbol: 'N_mesh3d',
    category: '3D & Digital Twin',
    subcategory: '3D Scene',
    description: 'Count of parametric 3D meshes in plant digital twin environment.',
    unit: 'Meshes',
    type: 'derived',
    defaultValue: 12,
    required: true
  },

  // ==========================================
  // PHASE 12: QA/QC, COMMISSIONING, O&M & MASTER REPORTING
  // ==========================================
  {
    id: 'AUD-OVR-001',
    name: 'Master Final Engineering Readiness Score',
    symbol: 'Score_WTP',
    category: 'Final Engineering Audit',
    subcategory: 'Readiness Score',
    description: 'Project-wide transparent engineering completeness score based on subsystem audits.',
    unit: '%',
    type: 'derived',
    defaultValue: 98,
    required: true
  },
  {
    id: 'CMP-RAT-001',
    name: 'Standards Compliance Rate',
    symbol: 'Rate_cmp',
    category: 'Standards & Compliance',
    subcategory: 'Compliance Rate',
    description: 'Percentage of evaluated international and local regulatory standards passed.',
    unit: '%',
    type: 'derived',
    defaultValue: 100,
    required: true
  },
  {
    id: 'COM-REL-001',
    name: 'Commissioning Reliability Run Duration',
    symbol: 'T_reliability',
    category: 'Commissioning',
    subcategory: 'Performance Testing',
    description: 'Continuous 100% load reliability run duration prior to client handover.',
    unit: 'hours',
    type: 'input',
    defaultValue: 72,
    required: true
  },
  {
    id: 'OM-AST-001',
    name: 'Registered Maintenance Assets Count',
    symbol: 'N_assets',
    category: 'Operation & Maintenance',
    subcategory: 'Asset Management',
    description: 'Total number of maintainable equipment assets registered in master O&M database.',
    unit: 'Assets',
    type: 'derived',
    defaultValue: 38,
    required: true
  }
];

export function getParametersByCategory(category: string): ParameterDefinition[] {
  return MASTER_PARAMETER_REGISTRY.filter(p => p.category === category);
}

export function getParameterById(id: string): ParameterDefinition | undefined {
  return MASTER_PARAMETER_REGISTRY.find(p => p.id === id);
}

