/**
 * EV Software Core - Initial Seed Data
 * Pre-populates the EVLab ecosystem with registered sibling applications,
 * realistic engineering projects, datasets, revisions, and audit logs.
 */

import { ApplicationManifest } from '../../types/application';
import { Organization, Project, User } from '../../types/core';
import { Dataset, DatasetRevision, GISDatasetPayload, CADDatasetPayload } from '../../types/dataset';
import { Transfer } from '../../types/transfer';
import { AuditLogEntry } from '../../types/audit';
import { FileReference } from '../../types/storage';

export const INITIAL_ORGANIZATION: Organization = {
  organizationId: 'org-evlab-global',
  name: 'Engineering Visual Lab (EVLab)',
  slug: 'evlab-global',
  createdAt: '2026-01-10T08:00:00Z',
  plan: 'enterprise',
  seatCount: 25,
};

export const INITIAL_USERS: User[] = [
  {
    userId: 'usr-marcus',
    name: 'Ayatullah',
    email: 'ayatullah.lead@evlab.engineering',
    avatarUrl: '',
    organizationId: 'org-evlab-global',
    title: 'Lead Infrastructure Architect',
    defaultRole: 'lead_engineer',
  },
  {
    userId: 'usr-sarah',
    name: 'Ayatullah',
    email: 'ayatullah.designer@evlab.engineering',
    avatarUrl: '',
    organizationId: 'org-evlab-global',
    title: 'Senior CAD & Piping Specialist',
    defaultRole: 'designer',
  },
  {
    userId: 'usr-elena',
    name: 'Ayatullah',
    email: 'ayatullah.reviewer@evlab.engineering',
    avatarUrl: '',
    organizationId: 'org-evlab-global',
    title: 'Hydraulic & QA Auditor',
    defaultRole: 'reviewer',
  },
];

export const REGISTERED_APPLICATIONS: ApplicationManifest[] = [
  {
    appId: 'app-ev-gis',
    name: 'EV GIS',
    slug: 'ev-gis',
    version: '1.0.0',
    coreApiVersion: 'v1',
    description: 'Spatial asset modeling, georeferenced pipeline networks, CRS transformations, and terrain topology.',
    category: 'geospatial',
    entryRoute: 'gis',
    iconName: 'Map',
    capabilities: ['spatial_data', 'export_geojson', 'reporting'],
    supportedProjectTypes: ['water_supply', 'wastewater', 'urban_drainage', 'civil_infrastructure'],
    requiredServices: ['data_exchange', 'validation_engine', 'revision_history', 'audit_logger', 'storage_service'],
    permissions: ['dataset:create', 'dataset:edit', 'transfer:create', 'transfer:commit'],
    releaseStatus: 'ga',
    author: 'EVLab Geospatial Core Team',
    documentationUrl: 'https://docs.evlab.engineering/apps/ev-gis',
    registeredAt: '2026-02-01T10:00:00Z',
    lastHealthCheck: '2026-08-15T21:40:00Z',
    isSiblingApp: true,
  },
  {
    appId: 'app-ev-mini-cad',
    name: 'EV Mini CAD',
    slug: 'ev-mini-cad',
    version: '1.0.0',
    coreApiVersion: 'v1',
    description: '2D precision drafting, pipeline alignment, dimensional snapping, entity attributes, and DXF interchange.',
    category: 'drafting_cad',
    entryRoute: 'minicad',
    iconName: 'PenTool',
    capabilities: ['cad_drafting', 'export_dxf', 'reporting'],
    supportedProjectTypes: ['water_supply', 'wastewater', 'urban_drainage', 'civil_infrastructure', 'industrial_plant'],
    requiredServices: ['data_exchange', 'validation_engine', 'revision_history', 'audit_logger', 'storage_service'],
    permissions: ['dataset:create', 'dataset:edit', 'transfer:create', 'transfer:commit'],
    releaseStatus: 'ga',
    author: 'EVLab Drafting Systems',
    documentationUrl: 'https://docs.evlab.engineering/apps/ev-mini-cad',
    registeredAt: '2026-02-05T10:00:00Z',
    lastHealthCheck: '2026-08-15T21:42:00Z',
    isSiblingApp: true,
  },
  {
    appId: 'app-ev-wtp',
    name: 'EV WTP',
    slug: 'ev-wtp',
    version: '0.9.0-beta',
    coreApiVersion: 'v1',
    description: 'Water Treatment Plant process train sizing, coagulation, flocculation, filtration kinetics, and hydraulic profile.',
    category: 'process_engineering',
    entryRoute: 'wtp',
    iconName: 'Droplets',
    capabilities: ['wtp_process', 'hydraulic_modeling', 'reporting', 'export_pdf'],
    supportedProjectTypes: ['water_supply', 'industrial_plant'],
    requiredServices: ['data_exchange', 'validation_engine', 'revision_history', 'audit_logger'],
    permissions: ['dataset:create', 'dataset:edit', 'transfer:create'],
    releaseStatus: 'ga',
    author: 'EVLab Process Group',
    documentationUrl: 'https://docs.evlab.engineering/apps/ev-wtp',
    registeredAt: '2026-03-12T11:00:00Z',
    lastHealthCheck: '2026-08-15T21:30:00Z',
    isSiblingApp: true,
  },
  {
    appId: 'app-ev-stp',
    name: 'EV STP',
    slug: 'ev-stp',
    version: '0.9.0-beta',
    coreApiVersion: 'v1',
    description: 'Sewage Treatment Plant bioreactor modeling, activated sludge kinetics, clarifiers, and disinfection calculations.',
    category: 'process_engineering',
    entryRoute: 'stp',
    iconName: 'Waves',
    capabilities: ['stp_process', 'hydraulic_modeling', 'reporting'],
    supportedProjectTypes: ['wastewater', 'industrial_plant'],
    requiredServices: ['data_exchange', 'validation_engine', 'revision_history', 'audit_logger'],
    permissions: ['dataset:create', 'dataset:edit', 'transfer:create'],
    releaseStatus: 'ga',
    author: 'EVLab Process Group',
    documentationUrl: 'https://docs.evlab.engineering/apps/ev-stp',
    registeredAt: '2026-03-15T11:00:00Z',
    lastHealthCheck: '2026-08-15T21:31:00Z',
    isSiblingApp: true,
  },
  {
    appId: 'app-ev-boq',
    name: 'EV BoQ',
    slug: 'ev-boq',
    version: '1.0.0',
    coreApiVersion: 'v1',
    description: 'Automated Bill of Quantities extraction from pipeline/plant datasets, rate analysis, and cost schedules.',
    category: 'cost_estimation',
    entryRoute: 'boq',
    iconName: 'Calculator',
    capabilities: ['boq_estimation', 'reporting', 'export_pdf'],
    supportedProjectTypes: ['water_supply', 'wastewater', 'urban_drainage', 'civil_infrastructure'],
    requiredServices: ['data_exchange', 'validation_engine', 'revision_history', 'audit_logger'],
    permissions: ['dataset:read', 'transfer:review', 'transfer:validate'],
    releaseStatus: 'ga',
    author: 'EVLab Estimation Labs',
    documentationUrl: 'https://docs.evlab.engineering/apps/ev-boq',
    registeredAt: '2026-04-01T09:00:00Z',
    lastHealthCheck: '2026-08-15T21:38:00Z',
    isSiblingApp: true,
  },
  {
    appId: 'app-ev-waterflow',
    name: 'EV WaterFlow',
    slug: 'ev-waterflow',
    version: '0.8.0-alpha',
    coreApiVersion: 'v1',
    description: 'Pressurized water network distribution analysis, headloss computations, and transient water hammer simulation.',
    category: 'hydraulics',
    entryRoute: 'waterflow',
    iconName: 'Droplets',
    capabilities: ['hydraulic_modeling', 'reporting'],
    supportedProjectTypes: ['water_supply', 'urban_drainage'],
    requiredServices: ['data_exchange', 'validation_engine', 'revision_history'],
    permissions: ['dataset:read', 'dataset:create'],
    releaseStatus: 'ga',
    author: 'EVLab Hydrodynamics',
    documentationUrl: 'https://docs.evlab.engineering/apps/ev-waterflow',
    registeredAt: '2026-05-10T14:00:00Z',
    lastHealthCheck: '2026-08-15T21:20:00Z',
    isSiblingApp: true,
  },
  {
    appId: 'app-ev-sheet',
    name: 'EV Sheet',
    slug: 'ev-sheet',
    version: '1.0.0',
    coreApiVersion: 'v1',
    description: 'Interactive parametric engineering notebooks with live formula parsing, unit checks, and tabular computations.',
    category: 'data_calculation',
    entryRoute: 'sheet',
    iconName: 'Table2',
    capabilities: ['sheet_calculation', 'reporting'],
    supportedProjectTypes: ['water_supply', 'wastewater', 'urban_drainage', 'civil_infrastructure', 'industrial_plant', 'general'],
    requiredServices: ['data_exchange', 'revision_history', 'storage_service'],
    permissions: ['dataset:create', 'dataset:edit'],
    releaseStatus: 'ga',
    author: 'EVLab Computational Engineering',
    documentationUrl: 'https://docs.evlab.engineering/apps/ev-sheet',
    registeredAt: '2026-05-18T10:00:00Z',
    lastHealthCheck: '2026-08-15T21:40:00Z',
    isSiblingApp: true,
  },
  {
    appId: 'app-ev-ai',
    name: 'EV Engineering AI',
    slug: 'ev-ai',
    version: '1.0.0',
    coreApiVersion: 'v1',
    description: 'AI-assisted standard clause retrieval, design specification compliance checks, and cross-application validation assistance.',
    category: 'ai_assistant',
    entryRoute: 'ev-ai',
    iconName: 'Sparkles',
    capabilities: ['reporting'],
    supportedProjectTypes: ['water_supply', 'wastewater', 'urban_drainage', 'civil_infrastructure', 'industrial_plant', 'general'],
    requiredServices: ['data_exchange', 'validation_engine', 'audit_logger'],
    permissions: ['dataset:read', 'transfer:review'],
    releaseStatus: 'preview',
    author: 'EVLab AI Research Lab',
    documentationUrl: 'https://docs.evlab.engineering/apps/ev-ai',
    registeredAt: '2026-06-01T08:00:00Z',
    lastHealthCheck: '2026-08-15T21:45:00Z',
    isSiblingApp: true,
  },
  {
    appId: 'app-ev-bim',
    name: 'EV BIM Viewer',
    slug: 'ev-bim',
    version: '1.0.0',
    coreApiVersion: 'v1',
    description: 'Unified 3D workspace connecting every EVLab tool\'s model — WTP process layouts, Mini CAD drawings, and future tools viewed together as one connected building information model.',
    category: 'utilities',
    entryRoute: 'bim',
    iconName: 'Box',
    capabilities: ['reporting'],
    supportedProjectTypes: ['water_supply', 'wastewater', 'urban_drainage', 'civil_infrastructure', 'industrial_plant', 'general'],
    requiredServices: ['data_exchange', 'revision_history', 'storage_service'],
    permissions: ['dataset:read', 'transfer:review'],
    releaseStatus: 'ga',
    author: 'EVLab Cross-Discipline Team',
    documentationUrl: 'https://docs.evlab.engineering/apps/ev-bim',
    registeredAt: '2026-06-10T08:00:00Z',
    lastHealthCheck: '2026-08-15T21:46:00Z',
    isSiblingApp: true,
  },
  {
    appId: 'app-ev-planner',
    name: 'EV Project Planner',
    slug: 'ev-planner',
    version: '1.0.0',
    coreApiVersion: 'v1',
    description: 'Project scheduling, task sequencing, and progress tracking across EVLab engineering projects.',
    category: 'utilities',
    entryRoute: 'planner',
    iconName: 'GanttChartSquare',
    capabilities: ['reporting'],
    supportedProjectTypes: ['water_supply', 'wastewater', 'urban_drainage', 'civil_infrastructure', 'industrial_plant', 'general'],
    requiredServices: ['data_exchange', 'audit_logger'],
    permissions: ['dataset:read', 'dataset:create'],
    releaseStatus: 'ga',
    author: 'EVLab Project Systems',
    documentationUrl: 'https://docs.evlab.engineering/apps/ev-planner',
    registeredAt: '2026-06-15T08:00:00Z',
    lastHealthCheck: '2026-08-15T21:47:00Z',
    isSiblingApp: true,
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    projectId: 'proj-metro-water-phase2',
    name: 'Metropolitan Trunk Water Supply & Pumping Station (Phase II)',
    code: 'EV-WSP-2026-004',
    description: 'Cross-district 1200mm/600mm DI trunk water pipeline alignment, booster station integration, and pressure zone regulation.',
    organizationId: 'org-evlab-global',
    projectType: 'water_supply',
    status: 'active',
    location: 'Metropolitan North Corridor, Sector 4-8',
    coordinateSystem: 'EPSG:3857 (WGS 84 / Pseudo-Mercator)',
    createdBy: 'usr-marcus',
    createdAt: '2026-07-01T08:30:00Z',
    updatedAt: '2026-08-15T20:15:00Z',
    members: [
      {
        projectMemberId: 'pm-1',
        projectId: 'proj-metro-water-phase2',
        userId: 'usr-marcus',
        user: INITIAL_USERS[0],
        role: 'lead_engineer',
        permissions: ['project:manage', 'dataset:create', 'dataset:edit', 'transfer:create', 'transfer:review', 'transfer:validate', 'transfer:commit', 'revision:create', 'audit:read'],
        joinedAt: '2026-07-01T08:30:00Z',
      },
      {
        projectMemberId: 'pm-2',
        projectId: 'proj-metro-water-phase2',
        userId: 'usr-sarah',
        user: INITIAL_USERS[1],
        role: 'designer',
        permissions: ['project:read', 'dataset:read', 'dataset:edit', 'transfer:create', 'transfer:review'],
        joinedAt: '2026-07-02T09:00:00Z',
      },
      {
        projectMemberId: 'pm-3',
        projectId: 'proj-metro-water-phase2',
        userId: 'usr-elena',
        user: INITIAL_USERS[2],
        role: 'reviewer',
        permissions: ['project:read', 'dataset:read', 'transfer:review', 'transfer:validate', 'transfer:commit'],
        joinedAt: '2026-07-05T10:00:00Z',
      },
    ],
    datasetCount: 3,
    transferCount: 4,
    revisionCount: 8,
  },
  {
    projectId: 'proj-city-stp-upgrade',
    name: 'City Central STP 150 MLD Bioreactor & Tertiary Filtration',
    code: 'EV-STP-2026-012',
    description: 'Process redesign to biological nutrient removal (BNR) with anaerobic digestion and UV disinfection.',
    organizationId: 'org-evlab-global',
    projectType: 'wastewater',
    status: 'in_review',
    location: 'Coastal Water Authority, Basin 12',
    coordinateSystem: 'EPSG:3857',
    createdBy: 'usr-marcus',
    createdAt: '2026-06-15T09:00:00Z',
    updatedAt: '2026-08-14T16:20:00Z',
    members: [
      {
        projectMemberId: 'pm-4',
        projectId: 'proj-city-stp-upgrade',
        userId: 'usr-marcus',
        user: INITIAL_USERS[0],
        role: 'lead_engineer',
        permissions: ['project:manage', 'dataset:create', 'transfer:commit'],
        joinedAt: '2026-06-15T09:00:00Z',
      },
      {
        projectMemberId: 'pm-5',
        projectId: 'proj-city-stp-upgrade',
        userId: 'usr-elena',
        user: INITIAL_USERS[2],
        role: 'reviewer',
        permissions: ['project:read', 'transfer:review', 'transfer:validate'],
        joinedAt: '2026-06-16T11:00:00Z',
      },
    ],
    datasetCount: 2,
    transferCount: 2,
    revisionCount: 4,
  },
  {
    projectId: 'proj-east-drainage-basin',
    name: 'East District Stormwater Basin & Culvert Channel',
    code: 'EV-DRN-2026-008',
    description: '100-year storm flood routing, box culvert discharge channel, and retention pond design.',
    organizationId: 'org-evlab-global',
    projectType: 'urban_drainage',
    status: 'planning',
    location: 'East Valley Catchment Zone',
    coordinateSystem: 'EPSG:3857',
    createdBy: 'usr-marcus',
    createdAt: '2026-07-20T14:00:00Z',
    updatedAt: '2026-08-10T12:00:00Z',
    members: [
      {
        projectMemberId: 'pm-6',
        projectId: 'proj-east-drainage-basin',
        userId: 'usr-marcus',
        user: INITIAL_USERS[0],
        role: 'owner',
        permissions: ['project:manage'],
        joinedAt: '2026-07-20T14:00:00Z',
      },
    ],
    datasetCount: 1,
    transferCount: 1,
    revisionCount: 2,
  },
];

// Initial GIS Trunk Water Mains Payload (EPSG:3857 local coordinates mapped for visualization)
export const INITIAL_GIS_PAYLOAD: GISDatasetPayload = {
  crs: {
    code: 'EPSG:3857',
    name: 'WGS 84 / Pseudo-Mercator',
    unit: 'meters',
  },
  layerName: 'Trunk_Water_Mains_Sector_4',
  elements: [
    {
      id: 'pipe-001',
      name: 'North Booster Outlet Feeder',
      type: 'pipeline',
      diameterMm: 600,
      material: 'Ductile Iron',
      lengthM: 420.5,
      nominalPressureBar: 16,
      startCoords: [120, 240],
      endCoords: [280, 240],
      invertElevationM: 42.5,
      status: 'approved',
    },
    {
      id: 'pipe-002',
      name: 'Main Highway Crossing Alignment',
      type: 'pipeline',
      diameterMm: 600,
      material: 'Ductile Iron',
      lengthM: 310.0,
      nominalPressureBar: 16,
      startCoords: [280, 240],
      endCoords: [440, 360],
      invertElevationM: 41.8,
      status: 'approved',
    },
    {
      id: 'pipe-003',
      name: 'Sector 5 Branch Offtake',
      type: 'pipeline',
      diameterMm: 300,
      material: 'HDPE',
      lengthM: 265.8,
      nominalPressureBar: 10,
      startCoords: [440, 360],
      endCoords: [600, 360],
      invertElevationM: 40.2,
      status: 'proposed',
    },
    {
      id: 'pipe-004',
      name: 'Reservoir Inflow Header',
      type: 'pipeline',
      diameterMm: 450,
      material: 'Ductile Iron',
      lengthM: 380.2,
      nominalPressureBar: 16,
      startCoords: [440, 360],
      endCoords: [560, 180],
      invertElevationM: 45.0,
      status: 'proposed',
    },
    {
      id: 'node-junc-1',
      name: 'Offtake Chamber Junction J-04',
      type: 'junction',
      diameterMm: 600,
      material: 'Ductile Iron',
      lengthM: 0,
      nominalPressureBar: 16,
      startCoords: [440, 360],
      endCoords: [440, 360],
      invertElevationM: 41.8,
      status: 'approved',
    },
  ],
  metadata: {
    totalLengthKm: 1.376,
    elementCount: 5,
    lastEditorApp: 'app-ev-gis',
  },
};

export const INITIAL_CAD_PAYLOAD: CADDatasetPayload = {
  drawingUnit: 'mm',
  layers: ['C-PIPE-MAIN', 'C-PIPE-BRANCH', 'C-VALV-CHMB', 'C-ANNO-TEXT', 'C-GRID-DIMS'],
  entities: [
    {
      id: 'cad-ent-1',
      layer: 'C-PIPE-MAIN',
      type: 'LINE',
      points: [[120, 240], [280, 240]],
      properties: {
        strokeColor: '#3b82f6',
        strokeWidth: 3,
        diameterMm: 600,
        material: 'Ductile Iron',
        tag: 'FEEDER-01',
      },
    },
    {
      id: 'cad-ent-2',
      layer: 'C-PIPE-MAIN',
      type: 'LINE',
      points: [[280, 240], [440, 360]],
      properties: {
        strokeColor: '#3b82f6',
        strokeWidth: 3,
        diameterMm: 600,
        material: 'Ductile Iron',
        tag: 'CROSSING-02',
      },
    },
    {
      id: 'cad-ent-3',
      layer: 'C-PIPE-BRANCH',
      type: 'LINE',
      points: [[440, 360], [600, 360]],
      properties: {
        strokeColor: '#10b981',
        strokeWidth: 2,
        diameterMm: 300,
        material: 'HDPE',
        tag: 'BRANCH-03',
      },
    },
  ],
  origin: [0, 0],
  metadata: {
    drawingTitle: 'Trunk Feeder Piping Alignment Sheet 01',
    scale: '1:1000',
    entityCount: 3,
  },
};

export const INITIAL_DATASET_REVISIONS: DatasetRevision[] = [
  {
    revisionId: 'rev-gis-001',
    datasetId: 'ds-gis-trunk-mains',
    revisionNumber: 1,
    parentRevisionId: null,
    sourceApplicationId: 'app-ev-gis',
    schemaVersion: '1.2.0',
    createdBy: 'usr-marcus',
    createdAt: '2026-07-02T10:00:00Z',
    changeSummary: 'Initial baseline import of Sector 4 & 5 Trunk Mains from municipal survey model.',
    validationState: 'validated',
    payloadChecksum: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    payload: INITIAL_GIS_PAYLOAD,
  },
  {
    revisionId: 'rev-cad-001',
    datasetId: 'ds-cad-alignment-dwg',
    revisionNumber: 1,
    parentRevisionId: null,
    sourceApplicationId: 'app-ev-mini-cad',
    schemaVersion: '1.1.0',
    createdBy: 'usr-sarah',
    createdAt: '2026-07-03T14:30:00Z',
    changeSummary: 'Initial civil drawing setup with baseline pipe centerlines and layer hierarchy.',
    validationState: 'validated',
    payloadChecksum: 'ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb',
    payload: INITIAL_CAD_PAYLOAD,
  },
];

export const INITIAL_DATASETS: Dataset[] = [
  {
    datasetId: 'ds-gis-trunk-mains',
    projectId: 'proj-metro-water-phase2',
    ownerApplicationId: 'app-ev-gis',
    name: 'Sector 4 Trunk Water Mains Geodataset',
    description: 'Master spatial network dataset for the North Feeder, Sector 5 off-take, and booster manifold connections.',
    datasetType: 'gis_network',
    schemaVersion: '1.2.0',
    currentRevisionId: 'rev-gis-001',
    currentRevisionNumber: 1,
    createdAt: '2026-07-02T10:00:00Z',
    updatedAt: '2026-07-02T10:00:00Z',
    createdBy: 'usr-marcus',
    revisions: [INITIAL_DATASET_REVISIONS[0]],
  },
  {
    datasetId: 'ds-cad-alignment-dwg',
    projectId: 'proj-metro-water-phase2',
    ownerApplicationId: 'app-ev-mini-cad',
    name: 'Trunk Water Main Alignment Sheet DWG-WSP-0201',
    description: 'Detailed 2D engineering drawing containing road crossing profiles, valve vaults, and station offsets.',
    datasetType: 'cad_drawing',
    schemaVersion: '1.1.0',
    currentRevisionId: 'rev-cad-001',
    currentRevisionNumber: 1,
    createdAt: '2026-07-03T14:30:00Z',
    updatedAt: '2026-07-03T14:30:00Z',
    createdBy: 'usr-sarah',
    revisions: [INITIAL_DATASET_REVISIONS[1]],
  },
  {
    datasetId: 'ds-wtp-sizing-model',
    projectId: 'proj-metro-water-phase2',
    ownerApplicationId: 'app-ev-wtp',
    name: 'North Clarifier & Rapid Sand Filter Process Matrix',
    description: 'Kinetic design parameters, hydraulic retention times, and surface overflow rates for Phase II expansion.',
    datasetType: 'wtp_process_model',
    schemaVersion: '1.0.0',
    currentRevisionId: 'rev-wtp-001',
    currentRevisionNumber: 1,
    createdAt: '2026-07-10T11:00:00Z',
    updatedAt: '2026-07-10T11:00:00Z',
    createdBy: 'usr-elena',
  },
];

export const INITIAL_TRANSFERS: Transfer[] = [
  {
    transferId: 'trf-gis-to-cad-001',
    projectId: 'proj-metro-water-phase2',
    sourceApplicationId: 'app-ev-gis',
    destinationApplicationId: 'app-ev-mini-cad',
    sourceDatasetId: 'ds-gis-trunk-mains',
    sourceRevisionId: 'rev-gis-001',
    state: 'committed',
    package: {
      transferId: 'trf-gis-to-cad-001',
      sourceApplicationId: 'app-ev-gis',
      sourceApplicationVersion: '1.0.0',
      destinationApplicationId: 'app-ev-mini-cad',
      destinationApplicationVersion: '1.0.0',
      projectId: 'proj-metro-water-phase2',
      sourceDatasetId: 'ds-gis-trunk-mains',
      sourceRevisionId: 'rev-gis-001',
      schemaVersion: '1.2.0',
      coreApiVersion: 'v1',
      units: 'meters',
      crs: 'EPSG:3857',
      changeSummary: 'Exported GIS pipeline centerline vectors for CAD precision road crossing alignment.',
      payload: INITIAL_GIS_PAYLOAD,
      timestamp: '2026-07-03T12:00:00Z',
      createdBy: 'usr-marcus',
    },
    diff: {
      totalChanges: 4,
      addedCount: 4,
      modifiedCount: 0,
      deletedCount: 0,
      hasConflicts: false,
      items: [
        {
          entityId: 'pipe-001',
          entityName: 'North Booster Outlet Feeder',
          changeType: 'added',
          fieldChanges: [],
        },
      ],
    },
    validationResult: {
      validationId: 'val-001',
      category: 'technical',
      status: 'passed',
      entityType: 'transfer',
      entityId: 'trf-gis-to-cad-001',
      validatedBy: 'core_technical_validator_v1',
      validatedAt: '2026-07-03T12:05:00Z',
      executionTimeMs: 42,
      errors: [],
      warnings: [],
      passedRuleCount: 8,
      totalRuleCount: 8,
      summary: 'All 8 technical validation rules passed. Spatial CRS, schema compatibility, and unit definitions verified.',
    },
    reviewedBy: 'usr-sarah',
    reviewedAt: '2026-07-03T13:10:00Z',
    committedBy: 'usr-sarah',
    committedAt: '2026-07-03T14:30:00Z',
    targetRevisionId: 'rev-cad-001',
    createdAt: '2026-07-03T12:00:00Z',
    updatedAt: '2026-07-03T14:30:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    auditId: 'aud-001',
    projectId: 'proj-metro-water-phase2',
    projectName: 'Metropolitan Trunk Water Supply & Pumping Station (Phase II)',
    userId: 'usr-marcus',
    userName: 'Ayatullah',
    userRole: 'lead_engineer',
    applicationId: 'app-ev-gis',
    applicationName: 'EV GIS',
    applicationVersion: '1.0.0',
    action: 'DATASET_CREATED',
    entityType: 'dataset',
    entityId: 'ds-gis-trunk-mains',
    entityName: 'Sector 4 Trunk Water Mains Geodataset',
    timestamp: '2026-07-02T10:00:00Z',
    clientIp: '192.168.1.45',
    description: 'Created new master GIS dataset with EPSG:3857 coordinate reference system and 5 hydraulic elements.',
  },
  {
    auditId: 'aud-002',
    projectId: 'proj-metro-water-phase2',
    projectName: 'Metropolitan Trunk Water Supply & Pumping Station (Phase II)',
    userId: 'usr-marcus',
    userName: 'Ayatullah',
    userRole: 'lead_engineer',
    applicationId: 'app-ev-gis',
    applicationName: 'EV GIS',
    applicationVersion: '1.0.0',
    action: 'TRANSFER_PREPARED',
    entityType: 'transfer',
    entityId: 'trf-gis-to-cad-001',
    entityName: 'GIS to CAD Baseline Package',
    timestamp: '2026-07-03T12:00:00Z',
    clientIp: '192.168.1.45',
    description: 'Prepared and dispatched transfer package from EV GIS to EV Mini CAD with schema version 1.2.0.',
  },
  {
    auditId: 'aud-003',
    projectId: 'proj-metro-water-phase2',
    projectName: 'Metropolitan Trunk Water Supply & Pumping Station (Phase II)',
    userId: 'usr-sarah',
    userName: 'Ayatullah',
    userRole: 'designer',
    applicationId: 'app-ev-mini-cad',
    applicationName: 'EV Mini CAD',
    applicationVersion: '1.0.0',
    action: 'TRANSFER_COMMITTED',
    entityType: 'transfer',
    entityId: 'trf-gis-to-cad-001',
    entityName: 'GIS to CAD Baseline Package',
    timestamp: '2026-07-03T14:30:00Z',
    clientIp: '192.168.1.52',
    description: 'Committed transfer into EV Mini CAD drawing, establishing initial revision rev-cad-001.',
  },
];

export const INITIAL_FILES: FileReference[] = [
  {
    fileId: 'file-wsp-geopackage-01',
    projectId: 'proj-metro-water-phase2',
    name: 'Sector4_TrunkMains_Survey_2026.gpkg',
    mimeType: 'application/geopackage+sqlite3',
    sizeBytes: 14857600,
    checksumSha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    storageProvider: 's3_compatible',
    storageKey: 'projects/proj-metro-water-phase2/gis/Sector4_TrunkMains_Survey_2026.gpkg',
    uploadedBy: 'usr-marcus',
    uploadedAt: '2026-07-02T09:45:00Z',
    tags: ['survey', 'gis', 'master'],
  },
  {
    fileId: 'file-dwg-sheet-01',
    projectId: 'proj-metro-water-phase2',
    name: 'DWG-WSP-0201-Alignment-RevA.dxf',
    mimeType: 'application/dxf',
    sizeBytes: 4325120,
    checksumSha256: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
    storageProvider: 's3_compatible',
    storageKey: 'projects/proj-metro-water-phase2/cad/DWG-WSP-0201-Alignment-RevA.dxf',
    uploadedBy: 'usr-sarah',
    uploadedAt: '2026-07-03T14:35:00Z',
    tags: ['cad', 'dxf', 'drawings'],
  },
  {
    fileId: 'file-wtp-spec-pdf',
    projectId: 'proj-metro-water-phase2',
    name: 'Process_Design_Basis_Report_WTP_P2.pdf',
    mimeType: 'application/pdf',
    sizeBytes: 8945200,
    checksumSha256: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
    storageProvider: 's3_compatible',
    storageKey: 'projects/proj-metro-water-phase2/docs/Process_Design_Basis_Report_WTP_P2.pdf',
    uploadedBy: 'usr-elena',
    uploadedAt: '2026-07-10T11:15:00Z',
    tags: ['report', 'wtp', 'specification'],
  },
];
