import React, { useState } from 'react';
import {
  Check,
  Copy,
  Download,
  FileText,
  Printer,
  Sparkles,
  X,
} from 'lucide-react';
import { TopicDefinition } from '../types/mechanics';

interface LabReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  topic: TopicDefinition;
  parameters: Record<string, number>;
  computedData: Record<string, any>;
  steps: any[];
  validations: any[];
  interpretation: string;
  isDark: boolean;
}

export const LabReportModal: React.FC<LabReportModalProps> = ({
  isOpen,
  onClose,
  topic,
  parameters,
  computedData,
  steps,
  validations,
  interpretation,
  isDark,
}) => {
  const [copied, setCopied] = useState(false);
  const [isAiLoading, setIsAiLoading] = useState(false);
  const [aiReportMarkdown, setAiReportMarkdown] = useState<string | null>(null);

  if (!isOpen) return null;

  const defaultMarkdownReport = `# EVLab Engineering Mechanics Virtual Laboratory
## Formal Laboratory Experiment Report

**Topic:** ${topic.title} (${topic.category.toUpperCase()})  
**Date:** ${new Date().toLocaleDateString()}  
**Station ID:** EVLAB-VIRTUAL-SIM-${topic.id.toUpperCase()}  

---

### 1. Executive Summary & Objective
This laboratory experiment investigates the fundamental principles of **${topic.title}**. Using deterministic numerical computational physics and vector kinematics/statics solvers, the system behavior is analyzed under varying load and kinematic conditions.

**Core Governing Principle:**  
${topic.summary}

---

### 2. Input Parameters & System Configuration
| Parameter | Symbol | Value | Unit |
| :--- | :--- | :--- | :--- |
${topic.parameterConfigs
  .map(
    (cfg) =>
      `| ${cfg.name} | ${cfg.symbol} | ${parameters[cfg.id] ?? cfg.defaultValue} | ${cfg.unit} |`
  )
  .join('\n')}

---

### 3. Step-by-Step Mathematical Solution Trace
${steps
  .map(
    (s) => `#### Step ${s.stepNumber}: ${s.description}
- **Governing Formula:** \`${s.formula}\`
- **Substitution:** \`${s.substitution}\`
- **Result:** **${s.result} ${s.unit || ''}**
${s.note ? `*Note:* ${s.note}` : ''}`
  )
  .join('\n\n')}

---

### 4. Computed Physical State & Reaction Quantities
\`\`\`json
${JSON.stringify(computedData, null, 2)}
\`\`\`

---

### 5. Verification & Stability Check
${validations
  .map(
    (v) =>
      `- [${v.type.toUpperCase()}] ${v.message} ${v.recommendation ? `(Recommendation: ${v.recommendation})` : ''}`
  )
  .join('\n')}

---

### 6. Engineering Interpretation & Conclusion
${interpretation}

---
*Generated by EVLab Virtual Engineering Mechanics Laboratory.*
`;

  const activeContent = aiReportMarkdown || defaultMarkdownReport;

  const handleCopy = () => {
    navigator.clipboard.writeText(activeContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleGenerateAiReport = async () => {
    setIsAiLoading(true);
    try {
      const res = await fetch('/api/ai/report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: topic.title,
          topic: topic.title,
          parameters,
          calculationResults: computedData,
          observations: interpretation,
        }),
      });
      const data = await res.json();
      if (data.reportMarkdown) {
        setAiReportMarkdown(data.reportMarkdown);
      }
    } catch (e) {
      console.error('Failed to generate AI report:', e);
    } finally {
      setIsAiLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/75 backdrop-blur-sm animate-in fade-in duration-200">
      <div
        id="lab-report-modal"
        className={`w-full max-w-4xl max-h-[90vh] flex flex-col rounded-2xl border shadow-2xl overflow-hidden ${
          isDark ? 'bg-slate-900 border-slate-800 text-slate-100' : 'bg-white border-slate-200 text-slate-900'
        }`}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-slate-800 print:hidden">
          <div className="flex items-center space-x-3">
            <div className="w-8 h-8 rounded-lg bg-blue-500/10 text-blue-500 border border-blue-500/20 flex items-center justify-center">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-base font-bold">Formal Engineering Mechanics Lab Report</h2>
              <p className="text-xs text-slate-400">
                ABET/ISO Compliant Experimental Documentation & Mathematical Trace
              </p>
            </div>
          </div>
          <div className="flex items-center space-x-2">
            <button
              onClick={handleGenerateAiReport}
              disabled={isAiLoading}
              className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-purple-600 hover:bg-purple-500 disabled:opacity-50 text-white transition-colors cursor-pointer shadow-sm"
            >
              <Sparkles className="w-3.5 h-3.5" />
              <span>{isAiLoading ? 'Synthesizing...' : 'AI Executive Polish'}</span>
            </button>
            <button
              onClick={handleCopy}
              className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold border border-slate-300 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors cursor-pointer"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy MD'}</span>
            </button>
            <button
              onClick={handlePrint}
              className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-blue-600 hover:bg-blue-500 text-white transition-colors cursor-pointer shadow-sm"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-400 hover:text-slate-200 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content Viewer */}
        <div className="flex-1 overflow-y-auto p-8 font-sans space-y-6 text-sm leading-relaxed">
          <div className="border-b pb-6 border-slate-200 dark:border-slate-800">
            <div className="flex justify-between items-start">
              <div>
                <span className="text-[10px] font-mono uppercase tracking-widest text-blue-500 font-bold">
                  EVLab Engineering Mechanics Series
                </span>
                <h1 className="text-xl font-bold mt-1 text-slate-900 dark:text-slate-100">
                  {topic.title} Experimentation Report
                </h1>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
                  Module: {topic.category.toUpperCase()} &bull; Subcategory: {topic.subcategory}
                </p>
              </div>
              <div className="text-right text-xs font-mono text-slate-400">
                <div>Date: {new Date().toLocaleDateString()}</div>
                <div>Status: VERIFIED</div>
              </div>
            </div>
          </div>

          {/* Parameters Table */}
          <div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-3">
              1. Laboratory Input Variables
            </h3>
            <div className="overflow-x-auto">
              <table className="w-full text-xs text-left border-collapse border border-slate-200 dark:border-slate-800 rounded-lg overflow-hidden">
                <thead className="bg-slate-100 dark:bg-slate-800/80 font-bold">
                  <tr>
                    <th className="p-2.5 border-b border-slate-200 dark:border-slate-800">Parameter</th>
                    <th className="p-2.5 border-b border-slate-200 dark:border-slate-800">Symbol</th>
                    <th className="p-2.5 border-b border-slate-200 dark:border-slate-800">Assigned Value</th>
                    <th className="p-2.5 border-b border-slate-200 dark:border-slate-800">SI Unit</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-200 dark:divide-slate-800">
                  {topic.parameterConfigs.map((cfg) => (
                    <tr key={cfg.id}>
                      <td className="p-2.5 font-medium">{cfg.name}</td>
                      <td className="p-2.5 font-mono text-blue-500 font-bold">{cfg.symbol}</td>
                      <td className="p-2.5 font-mono font-bold">{parameters[cfg.id] ?? cfg.defaultValue}</td>
                      <td className="p-2.5 font-mono text-slate-400">{cfg.unit || 'dimensionless'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Mathematical Solution Trace */}
          <div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-3">
              2. Analytical Solution & Step Derivations
            </h3>
            <div className="space-y-3">
              {steps.map((s) => (
                <div
                  key={s.stepNumber}
                  className={`p-4 rounded-xl border ${
                    isDark ? 'bg-slate-800/40 border-slate-800' : 'bg-slate-50 border-slate-200'
                  }`}
                >
                  <div className="flex items-center justify-between text-xs font-bold">
                    <span className="text-slate-800 dark:text-slate-200">
                      Step {s.stepNumber}: {s.description}
                    </span>
                    <span className="font-mono text-blue-500 bg-blue-500/10 px-2 py-0.5 rounded">
                      {s.result} {s.unit}
                    </span>
                  </div>
                  <div className="mt-2 text-xs font-mono text-slate-600 dark:text-slate-400 bg-black/10 dark:bg-black/30 p-2.5 rounded-lg">
                    <div>{s.formula}</div>
                    <div className="text-slate-500 dark:text-slate-400 mt-1">{s.substitution}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Interpretation & Conclusions */}
          <div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-2">
              3. Engineering Interpretation & Observations
            </h3>
            <div
              className={`p-4 rounded-xl border text-xs leading-relaxed ${
                isDark ? 'bg-slate-800/30 border-slate-800 text-slate-300' : 'bg-slate-50 border-slate-200 text-slate-700'
              }`}
            >
              {interpretation}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
