import { Material } from '../types';

export const STANDARD_MATERIALS: Material[] = [
  {
    id: 'structural_steel_a36',
    name: 'Structural Steel (ASTM A36)',
    category: 'Ferrous Metals',
    density: 7850,
    E: 200, // GPa
    G: 77.2, // GPa
    nu: 0.26,
    yieldStrength: 250, // MPa
    ultimateStrength: 400, // MPa
    compressiveStrength: 250,
    shearStrength: 145,
    thermalExpansion: 12.0,
    isDuctile: true,
    fractureStrain: 0.28,
    color: '#475569',
    source: 'AISC Steel Construction Manual 15th Ed. / ASTM A36',
  },
  {
    id: 'stainless_steel_304',
    name: 'Stainless Steel (AISI 304)',
    category: 'Ferrous Metals',
    density: 8000,
    E: 193,
    G: 75,
    nu: 0.29,
    yieldStrength: 215,
    ultimateStrength: 505,
    compressiveStrength: 215,
    shearStrength: 125,
    thermalExpansion: 17.3,
    isDuctile: true,
    fractureStrain: 0.40,
    color: '#64748b',
    source: 'ASM Specialty Handbook: Stainless Steels',
  },
  {
    id: 'aluminum_6061_t6',
    name: 'Aluminium Alloy (6061-T6)',
    category: 'Non-Ferrous Metals',
    density: 2700,
    E: 68.9,
    G: 26,
    nu: 0.33,
    yieldStrength: 276,
    ultimateStrength: 310,
    compressiveStrength: 276,
    shearStrength: 207,
    thermalExpansion: 23.2,
    isDuctile: true,
    fractureStrain: 0.17,
    color: '#0284c7',
    source: 'Aluminum Association Standards & Data / MIL-HDBK-5J',
  },
  {
    id: 'structural_aluminum_7075_t6',
    name: 'Aerospace Aluminium (7075-T6)',
    category: 'Non-Ferrous Metals',
    density: 2810,
    E: 71.7,
    G: 26.9,
    nu: 0.33,
    yieldStrength: 503,
    ultimateStrength: 572,
    compressiveStrength: 503,
    shearStrength: 331,
    thermalExpansion: 23.4,
    isDuctile: true,
    fractureStrain: 0.11,
    color: '#0369a1',
    source: 'MMPDS-01 Aerospace Structural Metals Handbook',
  },
  {
    id: 'structural_timber_douglas_fir',
    name: 'Structural Timber (Douglas Fir)',
    category: 'Timber',
    density: 530,
    E: 13.1,
    G: 0.78,
    nu: 0.30,
    yieldStrength: 35, // Proportional limit parallel to grain
    ultimateStrength: 50,
    compressiveStrength: 45,
    shearStrength: 7.5,
    thermalExpansion: 3.5,
    isDuctile: false,
    fractureStrain: 0.02,
    color: '#b45309',
    source: 'NDS National Design Specification for Wood Construction',
  },
  {
    id: 'structural_concrete_c30',
    name: 'Structural Concrete (C30/37)',
    category: 'Concrete / Ceramic',
    density: 2400,
    E: 33.0,
    G: 13.8,
    nu: 0.20,
    yieldStrength: 3.5, // Tensile cracking
    ultimateStrength: 3.8, // Tensile rupture
    compressiveStrength: 38.0, // Compressive cube strength
    shearStrength: 4.2,
    thermalExpansion: 10.0,
    isDuctile: false,
    fractureStrain: 0.0035,
    color: '#78716c',
    source: 'Eurocode 2 / ACI 318-19 Building Code',
  },
  {
    id: 'cast_iron_gray',
    name: 'Gray Cast Iron (ASTM Class 40)',
    category: 'Ferrous Metals',
    density: 7200,
    E: 110,
    G: 44,
    nu: 0.25,
    yieldStrength: 180, // Approximate tensile
    ultimateStrength: 290,
    compressiveStrength: 860, // Much stronger in compression
    shearStrength: 380,
    thermalExpansion: 11.5,
    isDuctile: false,
    fractureStrain: 0.008,
    color: '#334155',
    source: 'ASTM A48 / Shigley Mechanical Engineering Design',
  },
  {
    id: 'copper_pure',
    name: 'Pure Copper (C11000 ETP)',
    category: 'Non-Ferrous Metals',
    density: 8940,
    E: 117,
    G: 44,
    nu: 0.34,
    yieldStrength: 69,
    ultimateStrength: 220,
    compressiveStrength: 69,
    shearStrength: 150,
    thermalExpansion: 16.5,
    isDuctile: true,
    fractureStrain: 0.45,
    color: '#ea580c',
    source: 'CDA Copper Development Association Database',
  },
  {
    id: 'structural_brass_cartridge',
    name: 'Cartridge Brass (C26000 70/30)',
    category: 'Non-Ferrous Metals',
    density: 8530,
    E: 105,
    G: 40,
    nu: 0.35,
    yieldStrength: 110,
    ultimateStrength: 340,
    compressiveStrength: 110,
    shearStrength: 220,
    thermalExpansion: 19.9,
    isDuctile: true,
    fractureStrain: 0.50,
    color: '#ca8a04',
    source: 'MatWeb Materials Property Data',
  },
  {
    id: 'titanium_ti6al4v',
    name: 'Titanium Grade 5 (Ti-6Al-4V)',
    category: 'Alloys',
    density: 4430,
    E: 114,
    G: 44,
    nu: 0.342,
    yieldStrength: 880,
    ultimateStrength: 950,
    compressiveStrength: 970,
    shearStrength: 550,
    thermalExpansion: 8.6,
    isDuctile: true,
    fractureStrain: 0.14,
    color: '#0f766e',
    source: 'AMS 4911 / Aerospace Materials Specification',
  }
];

export function getMaterialById(id: string): Material {
  const found = STANDARD_MATERIALS.find(m => m.id === id);
  return found || STANDARD_MATERIALS[0];
}
