import { TopicData, TopicId } from '../types';

export const TOPICS_DATA: TopicData[] = [
  {
    id: 'axial_stress',
    title: 'Axial Stress',
    category: 'Fundamentals',
    subtitle: 'Direct Normal Stress in Tension & Compression',
    governingFormula: '\\sigma = \\frac{P}{A}',
    standardRef: 'ASTM E8 / AISC 360-16 / Beer & Johnston Ch. 1',
    keyConcepts: ['Normal Stress', 'Tension vs Compression', 'Cross-sectional Area', 'Factor of Safety', 'Allowable Stress'],
    description: 'Investigate how axial force distributed over cross-sectional area creates internal normal stress, and see how varying geometric cross-sections directly alters stress intensity.',
    iconName: 'ArrowUpDown',
    theory: {
      concept: 'Axial stress is the internal resisting force per unit area acting perpendicularly to a section cut. Tensile stress elongates the member, while compressive stress causes shortening.',
      governingTheory: 'Saint-Venant’s Principle establishes that stress distribution becomes uniform across the cross-section at a distance roughly equal to the largest cross-sectional dimension from the point of load application.',
      derivation: 'Equilibrium of an infinitesimal slice: \\Sigma F_x = 0 \\implies P = \\int_A \\sigma \\, dA. Assuming uniform displacement across the cross-section, \\sigma is constant, yielding P = \\sigma A \\implies \\sigma = P / A.',
      assumptions: [
        'Prismatic bar with uniform cross-sectional area A along its entire length',
        'Line of action of resultant axial force passes through the centroid of the cross-section',
        'Homogeneous, isotropic, and linear-elastic material behavior',
        'Small deformation theory',
      ],
      practicalApplications: [
        'Bridge truss tension ties and suspension hangers',
        'Building structural columns under gravity compression',
        'Aircraft fuselage tie-rods and hydraulic actuator pistons',
      ],
      commonMistakes: [
        'Neglecting eccentric loading which introduces simultaneous bending stress (\\sigma = P/A \\pm My/I)',
        'Applying nominal area without subtracting bolt hole reductions (net section area)',
        'Overlooking compressive buckling in long slender compression struts',
      ],
    },
  },
  {
    id: 'axial_deformation',
    title: 'Axial Deformation',
    category: 'Fundamentals',
    subtitle: 'Elastic Elongation and Contraction of Bars',
    governingFormula: '\\delta = \\frac{P L}{A E}',
    standardRef: 'ASTM E111 / ISO 6892-1 / Hibbeler Ch. 4',
    keyConcepts: ['Axial Elongation', 'Bar Stiffness EA/L', 'Young’s Modulus', 'Length Proportionality', 'Thermal Strain'],
    description: 'Explore the linear elastic elongation/shortening of structural members under axial load. Observe the governing relationship between load, length, area, and elastic modulus.',
    iconName: 'MoveHorizontal',
    theory: {
      concept: 'Axial deformation \\delta is the cumulative change in length of a member subjected to tension or compression, governed by the axial stiffness EA/L.',
      governingTheory: 'Combining Hooke’s law (\\sigma = E\\epsilon) with the kinematic strain definition (\\epsilon = \\delta/L) and equilibrium (\\sigma = P/A) yields the elastic elongation formula.',
      derivation: 'For a differential segment dx: d\\delta = \\epsilon \\, dx = \\frac{\\sigma(x)}{E(x)} dx = \\frac{P(x)}{A(x) E(x)} dx. Integrating from 0 to L: \\delta = \\int_0^L \\frac{P(x)}{A(x) E(x)} dx = \\frac{PL}{AE} \\text{ (for constant properties)}.',
      assumptions: [
        'Material remains within the proportional linear elastic limit (\\sigma \\le \\sigma_{pl})',
        'Prismatic geometry with constant Young’s modulus E along the member span',
        'No lateral buckling occurs during compressive loading',
      ],
      practicalApplications: [
        'Prestressed concrete tendon tensioning elongations',
        'Thermal expansion gap sizing in railroad tracks and bridges',
        'Deflection control in precision optical stages and crane boom cables',
      ],
      commonMistakes: [
        'Mixing unit prefixes (e.g., using E in GPa with length in mm and load in kN without 10^3 conversion factors)',
        'Neglecting self-weight deformation for very long vertical cables or deep well drill pipes',
      ],
    },
  },
  {
    id: 'hookes_law',
    title: 'Hooke’s Law',
    category: 'Fundamentals',
    subtitle: 'Linear Elastic Constitutive Stress-Strain Relation',
    governingFormula: '\\sigma = E \\cdot \\epsilon, \\quad \\nu = -\\frac{\\epsilon_{\\text{lat}}}{\\epsilon_{\\text{long}}}',
    standardRef: 'ASTM E132 / BS EN ISO 527 / Gere & Goodno Ch. 1',
    keyConcepts: ['Proportional Limit', 'Elastic Modulus E', 'Poisson’s Ratio ν', 'Lateral Strain', 'Modulus of Resilience'],
    description: 'Examine the fundamental constitutive law connecting normal stress and strain within the elastic regime, including lateral strain and Poisson ratio effects.',
    iconName: 'Maximize2',
    theory: {
      concept: 'Hooke’s Law states that within the elastic range, stress is linearly proportional to strain. Poisson’s ratio \\nu governs the transverse contraction when stretched longitudinally.',
      governingTheory: 'Generalized Hooke’s Law connects multiaxial 3D stresses to strains using Young’s modulus E, Shear modulus G, and Poisson’s ratio \\nu with G = E / [2(1 + \\nu)].',
      derivation: 'Under uniaxial tension \\sigma_x: \\epsilon_x = \\sigma_x / E, \\epsilon_y = -\\nu \\sigma_x / E, \\epsilon_z = -\\nu \\sigma_x / E. Volumetric strain \\epsilon_v = \\epsilon_x + \\epsilon_y + \\epsilon_z = \\frac{\\sigma_x}{E}(1 - 2\\nu).',
      assumptions: [
        'Isotropic material (identical mechanical properties in all spatial directions)',
        'Stress level stays strictly below the elastic limit',
        'Isothermal ambient conditions without temperature fluctuations',
      ],
      practicalApplications: [
        'Strain gauge sensor calibration and telemetry',
        'Design of elastomeric seals and vibration dampers',
        'Structural displacement modeling in finite element analysis',
      ],
      commonMistakes: [
        'Assuming Hooke’s law applies beyond the yield point where plastic slip occurs',
        'Confusing Young’s modulus (elastic stiffness) with yield strength (load capacity)',
      ],
    },
  },
  {
    id: 'stress_strain_lab',
    title: 'Stress-Strain Tensile Lab',
    category: 'Fundamentals',
    subtitle: 'Virtual Universal Testing Machine (UTM) Tensile Test',
    governingFormula: '\\sigma = \\frac{P}{A_0}, \\quad \\epsilon = \\frac{\\Delta L}{L_0}',
    standardRef: 'ASTM E8/E8M / ISO 6892-1 / AS 1391',
    keyConcepts: ['Elastic Limit', 'Yield Point', 'Strain Hardening', 'Necking & Fracture', 'Toughness & Ductility'],
    description: 'Operate a virtual tensile testing machine. Apply progressive displacement/load to various engineering specimens and track the live stress-strain curve from elasticity through necking and rupture.',
    iconName: 'Activity',
    theory: {
      concept: 'A uniaxial tensile test pulls a standard dogbone specimen to failure, producing a stress-strain diagram that reveals stiffness, yield strength, tensile strength, ductility, and fracture toughness.',
      governingTheory: 'Engineering stress \\sigma = P/A_0 and strain \\epsilon = \\Delta L/L_0 are based on initial dimensions, whereas True stress \\sigma_t = P/A and True strain \\epsilon_t = \\ln(L/L_0) account for continuous cross-sectional reduction.',
      derivation: 'Modulus of Resilience u_r = \\int_0^{\\epsilon_y} \\sigma \\, d\\epsilon = \\frac{\\sigma_y^2}{2E}. Modulus of Toughness u_t = \\int_0^{\\epsilon_f} \\sigma \\, d\\epsilon (total area under the stress-strain curve).',
      assumptions: [
        'Standard dogbone specimen geometry according to ASTM E8 (gauge length = 50 mm)',
        'Quasi-static tensile loading rate without dynamic strain-rate hardening',
      ],
      practicalApplications: [
        'Material certification and quality inspection in steel mills and aerospace fabrication',
        'Energy absorption evaluation for automotive crashworthiness structures',
      ],
      commonMistakes: [
        'Confusing engineering stress with true stress during localized necking',
        'Measuring gauge length extension from machine crosshead displacement without extensometers',
      ],
    },
  },
  {
    id: 'shear_stress',
    title: 'Direct Shear Stress',
    category: 'Torsion & Shear',
    subtitle: 'Shear Force Distribution on Parallel Planes',
    governingFormula: '\\tau = \\frac{V}{A}',
    standardRef: 'AISC 360-16 Section J3 / Eurocode 3 / Hibbeler Ch. 1',
    keyConcepts: ['Average Shear Stress', 'Single vs Double Shear', 'Bolted/Riveted Joints', 'Shear Strain γ', 'Shear Modulus G'],
    description: 'Analyze shear stresses developed across planar sections in lap joints, clevis pins, and punched plates, along with angular shear deformation.',
    iconName: 'Layers',
    theory: {
      concept: 'Direct shear stress \\tau acts tangentially to the cross-sectional plane, produced by opposing forces acting along closely spaced parallel planes.',
      governingTheory: 'In double shear configurations (clevis pin or butt joint with two cover plates), the applied shear force is split across two failure planes, doubling the connection capacity.',
      derivation: 'Single shear: \\tau_{\\text{avg}} = V / A = P / (\\pi d^2 / 4). Double shear: \\tau_{\\text{avg}} = V / (2A) = P / [2(\\pi d^2 / 4)].',
      assumptions: [
        'Uniform distribution of shear stress across the bolt or pin shear plane',
        'Negligible friction between connected plies unless designed as a slip-critical joint',
      ],
      practicalApplications: [
        'Structural steel bolted and riveted connections',
        'Cotter pins, dowels, and machine keyways',
        'Punched sheet metal manufacturing and guillotine cutting',
      ],
      commonMistakes: [
        'Failing to check bearing stress on the connected plates (\\sigma_b = P / (d \\cdot t))',
        'Assuming threads are excluded from the shear plane when they are actually intercepted',
      ],
    },
  },
  {
    id: 'torsion',
    title: 'Torsion of Circular Shafts',
    category: 'Torsion & Shear',
    subtitle: 'Torsional Shear Stress & Angle of Twist',
    governingFormula: '\\frac{T}{J} = \\frac{\\tau}{r} = \\frac{G \\theta}{L}',
    standardRef: 'ASTM A938 / ISO 7800 / Beer & Johnston Ch. 3',
    keyConcepts: ['Angle of Twist θ', 'Polar Moment J', 'Shear Stress Gradient', 'Solid vs Hollow Shaft Efficiency', 'Torsional Rigidity GJ'],
    description: 'Twist circular solid and hollow shafts in real time. Observe how shear stress increases linearly from zero at the center to maximum at the outer surface, and see helical surface deformation.',
    iconName: 'RotateCw',
    theory: {
      concept: 'Torsion creates circumferential shear stresses that vary linearly with radial distance from the longitudinal axis, reaching maximum at the outer circumference.',
      governingTheory: 'Circular cross-sections remain planar and undistorted during twisting (no warping). Hollow shafts place material where radius r is largest, maximizing polar moment J with minimum mass.',
      derivation: 'From shear strain \\gamma = r \\theta / L and Hooke’s law \\tau = G \\gamma: \\tau(r) = G r \\theta / L. Internal torque T = \\int_A r \\tau \\, dA = \\frac{G \\theta}{L} \\int_A r^2 \\, dA = \\frac{G \\theta J}{L} \\implies \\tau_{\\max} = \\frac{T c}{J}.',
      assumptions: [
        'Circular solid or tubular cross-section (non-circular sections warp out of plane)',
        'Homogeneous, isotropic linear elastic material response',
        'Small angular twist \\theta where geometry changes are negligible',
      ],
      practicalApplications: [
        'Automotive drive shafts and power takeoff (PTO) axles',
        'Turbine and generator rotor shafts in power generation plants',
        'Torsion spring suspension bars in armored vehicles and sports cars',
      ],
      commonMistakes: [
        'Applying circular torsion formulas (\\tau = Tc/J) to square, rectangular, or I-beam sections which warp heavily',
        'Ignoring stress concentration factors at shaft keyways and diameter transition fillets',
      ],
    },
  },
  {
    id: 'beam_bending',
    title: 'Beam Equilibrium & SFD / BMD',
    category: 'Beams & Flexure',
    subtitle: 'Support Reactions, Shear Force & Bending Moment Diagrams',
    governingFormula: 'V(x) = \\frac{dM}{dx}, \\quad q(x) = -\\frac{dV}{dx}',
    standardRef: 'AISC 360 / ASCE 7-22 / Hibbeler Ch. 6',
    keyConcepts: ['Simply Supported & Cantilever', 'Point Loads & UDL/UVL', 'Shear Force Diagram (SFD)', 'Bending Moment Diagram (BMD)', 'Points of Contraflexure'],
    description: 'Interact with simply supported, cantilever, fixed, and overhanging beams. Drag point loads and distributed loads dynamically to see immediate reaction forces and real-time SFD/BMD plots.',
    iconName: 'Sliders',
    theory: {
      concept: 'Beams are structural members designed to support transverse loads through internal shear forces V(x) and bending moments M(x).',
      governingTheory: 'Differential equilibrium relations: the slope of the Shear Force Diagram equals the load intensity -q(x), and the slope of the Bending Moment Diagram equals the shear force V(x). Maximum bending moment occurs where shear force equals zero.',
      derivation: 'For a differential slice dx: \\Sigma F_y = 0 \\implies V - (V + dV) - q \\, dx = 0 \\implies \\frac{dV}{dx} = -q. \\Sigma M = 0 \\implies -M + (M + dM) - V \\, dx = 0 \\implies \\frac{dM}{dx} = V.',
      assumptions: [
        'Static equilibrium holds for the entire beam and any isolated cut section',
        'Loads act in the principal plane of symmetry of the beam cross-section',
      ],
      practicalApplications: [
        'Highway and railway bridge girders',
        'Building floor joists, purlins, and transfer beams',
        'Crane overhead runway runways and cantilevered balcony beams',
      ],
      commonMistakes: [
        'Confusing sign conventions: standard engineering BMD is positive sagging (compression top, tension bottom)',
        'Forgetting that concentrated point loads cause an instantaneous vertical jump in the SFD',
      ],
    },
  },
  {
    id: 'flexural_stress',
    title: 'Flexural Bending Stress',
    category: 'Beams & Flexure',
    subtitle: 'The Elastic Flexure Formula & Stress Distribution',
    governingFormula: '\\sigma = \\frac{M y}{I} = \\frac{M}{Z}',
    standardRef: 'AISC 360-16 / Eurocode 3 / Beer & Johnston Ch. 4',
    keyConcepts: ['Flexure Formula', 'Compression & Tension Zones', 'Section Modulus Z', 'Moment of Inertia I', 'Neutral Axis Fiber'],
    description: 'Inspect cross-sectional stress gradients in bending. Cut through any section along the beam span to view linear fiber stress distribution from peak compressive fiber to maximum tensile fiber.',
    iconName: 'GitCommit',
    theory: {
      concept: 'When a beam is bent, fibers on the convex side stretch in tension, fibers on the concave side shorten in compression, and fibers along the neutral axis experience zero strain and stress.',
      governingTheory: 'Euler-Bernoulli Beam Theory: Plane cross-sections perpendicular to the neutral axis remain plane and perpendicular after bending. The stress distribution is purely linear across depth y.',
      derivation: 'Kinematic longitudinal strain \\epsilon = -y / \\rho. Hooke’s law \\sigma = E \\epsilon = -E y / \\rho. Internal resisting moment M = \\int_A -y \\sigma \\, dA = \\frac{E}{\\rho} \\int_A y^2 \\, dA = \\frac{E I}{\\rho} \\implies \\sigma(y) = -\\frac{M y}{I}.',
      assumptions: [
        'Beam has a symmetric cross-section and is loaded in the plane of symmetry',
        'Linear elastic material behaving identically in tension and compression',
        'Cross-section dimensions are small compared to beam span (span / depth \\ge 5)',
      ],
      practicalApplications: [
        'Selection of standard structural steel W-shapes, timber glulam beams, and reinforced concrete girders',
        'Design of aircraft wing spars and ship hull box girders',
      ],
      commonMistakes: [
        'Measuring y from the top or bottom edge rather than from the centroidal Neutral Axis',
        'Using the wrong axis moment of inertia (Ix for major-axis vs Iy for minor-axis bending)',
      ],
    },
  },
  {
    id: 'beam_shear_stress',
    title: 'Transverse Shear in Beams',
    category: 'Beams & Flexure',
    subtitle: 'Shear Stress Distribution Across Cross-Sections',
    governingFormula: '\\tau = \\frac{V Q}{I b}',
    standardRef: 'AISC 360-16 Chapter G / Hibbeler Ch. 7',
    keyConcepts: ['First Moment of Area Q', 'Parabolic Stress Profile', 'Web Shear in I-Beams', 'Max Shear at Neutral Axis', 'Flange vs Web Shear'],
    description: 'Visualize the transverse and horizontal shear stress distribution across rectangular, I-beam, and pipe sections with live color heatmaps.',
    iconName: 'BarChart2',
    theory: {
      concept: 'Bending is accompanied by transverse shear force V, which generates complementary horizontal and vertical shear stresses \\tau(y) across the depth of the beam.',
      governingTheory: 'Shear stress is highest at the neutral axis where First Moment of Area Q is maximized, and drops to zero at the top and bottom free surfaces. In I-beams, the thin web carries over 90% of the total shear.',
      derivation: 'Horizontal equilibrium on a cut section of length dx: \\Delta H = \\int_{y_1}^{c} \\Delta \\sigma \\, dA = \\frac{dM}{I} \\int_{y_1}^{c} y \\, dA = \\frac{V dx}{I} Q. Shear flow q = \\Delta H / dx = VQ / I \\implies \\tau = q / b = \\frac{VQ}{Ib}.',
      assumptions: [
        'Shear stress is uniformly distributed across the section width b at depth y',
        'Prismatic straight beam under pure flexure and shear without torsion',
      ],
      practicalApplications: [
        'Fastener spacing (nails, bolts, spot welds) in built-up composite beams',
        'Web crippling and shear buckling checks in deep steel plate girders',
        'Horizontal longitudinal shear checks in glued-laminated timber beams',
      ],
      commonMistakes: [
        'Using the total area A instead of the First Moment of Area Q of the portion above the cut',
        'Confusing section width b at the neutral axis with total flange width',
      ],
    },
  },
  {
    id: 'beam_deflection',
    title: 'Beam Deflection & Elastic Curve',
    category: 'Beams & Flexure',
    subtitle: 'Differential Equation of the Elastic Deflection Curve',
    governingFormula: 'E I \\frac{d^2 v}{dx^2} = M(x), \\quad \\delta_{\\max} = \\frac{5 w L^4}{384 E I}',
    standardRef: 'IBC Table 1604.3 / AISC Design Guide 3 / Gere Ch. 9',
    keyConcepts: ['Elastic Curve v(x)', 'Slope θ(x)', 'Maximum Deflection δ_max', 'Flexural Rigidity EI', 'Span-to-Deflection Ratio (L/360)'],
    description: 'Simulate structural beam deflection under varied boundary conditions and loading patterns. Inspect elastic slope curves, curvature, and maximum mid-span displacement.',
    iconName: 'TrendingDown',
    theory: {
      concept: 'Beam deflection is the lateral translation v(x) of the neutral axis from its unloaded horizontal reference line under applied bending loads.',
      governingTheory: 'The governing second-order differential equation of the elastic curve connects beam curvature \\kappa \\approx d^2v/dx^2 directly to bending moment M(x) divided by flexural rigidity EI.',
      derivation: 'From geometry: curvature \\kappa = 1/\\rho = d\\theta / dx \\approx d^2v/dx^2. From flexure: 1/\\rho = M / (EI). Combining yields EI \\frac{d^2v}{dx^2} = M(x). Integrating twice and applying boundary conditions solves v(x).',
      assumptions: [
        'Small slope approximation ((dv/dx)^2 \\ll 1) so curvature \\kappa \\approx d^2v/dx^2',
        'Deformations due to transverse shear are negligible compared to flexure (Euler-Bernoulli assumption)',
      ],
      practicalApplications: [
        'Building serviceability limits (L/360 to prevent plaster ceiling cracking, L/240 for roof ponding)',
        'Machine tool bed stiffness requirements to maintain machining tolerances',
      ],
      commonMistakes: [
        'Using strength (yield limit) as the sole design criteria when deflection serviceability governs',
        'Neglecting the fourth-power dependence on span length (\\delta \\propto L^4) for distributed loads',
      ],
    },
  },
  {
    id: 'neutral_axis',
    title: 'Neutral Axis & Fiber Mechanics',
    category: 'Beams & Flexure',
    subtitle: 'Deformation of Longitudinal Fibers & Strain Profile',
    governingFormula: '\\epsilon(y) = -\\frac{y}{\\rho} = -\\kappa y, \\quad \\bar{y} = \\frac{\\sum A_i y_i}{\\sum A_i}',
    standardRef: 'Beer & Johnston Ch. 4 / Hibbeler Ch. 6',
    keyConcepts: ['Neutral Surface', 'Radius of Curvature ρ', 'Fiber Strain Gradient', 'Curvature κ', 'Centroidal Alignment'],
    description: 'Look inside the longitudinal fibers of a bent beam. Observe upper fibers contracting in compression, lower fibers stretching in tension, and the zero-strain neutral surface.',
    iconName: 'Compass',
    theory: {
      concept: 'The neutral axis is the locus of points across the cross-section where longitudinal normal stress and strain are identically zero during pure bending.',
      governingTheory: 'For elastic homogeneous beams, the neutral axis passes precisely through the area centroid of the cross-section. For composite or asymmetric sections, it shifts towards the stiffer/larger flange.',
      derivation: 'Resultant axial force in pure bending must vanish: N = \\int_A \\sigma \\, dA = \\int_A \\left(-\\frac{Ey}{\\rho}\\right) dA = -\\frac{E}{\\rho} \\int_A y \\, dA = 0. Therefore, the first moment of area \\int_A y \\, dA = 0, proving the NA passes through the centroid.',
      assumptions: [
        'Pure bending without axial thrust or net normal force',
        'Homogeneous cross-section with uniform Young’s modulus E',
      ],
      practicalApplications: [
        'Centroid and neutral axis location in asymmetric sections (T-beams, C-channels, composite decks)',
        'Placement of prestressing cables at maximum eccentricity relative to the NA',
      ],
      commonMistakes: [
        'Assuming the neutral axis always sits at mid-height (h/2) for asymmetric T or L shapes',
      ],
    },
  },
  {
    id: 'principal_stress',
    title: 'Stress Transformation & Principal Stresses',
    category: 'Stress Transformation',
    subtitle: '2D Plane Stress Transformation & Maximum Shear',
    governingFormula: '\\sigma_{1,2} = \\frac{\\sigma_x + \\sigma_y}{2} \\pm \\sqrt{\\left(\\frac{\\sigma_x - \\sigma_y}{2}\\right)^2 + \\tau_{xy}^2}',
    standardRef: 'ASTM E837 / AISC 360-16 / Beer & Johnston Ch. 7',
    keyConcepts: ['Plane Stress Element', 'Angle Rotation θ', 'Principal Planes θp', 'Max In-Plane Shear τ_max', 'Stress Invariants'],
    description: 'Rotate an infinitesimal 2D stress element interactively. Watch normal and shear stresses transform continuously with orientation angle and identify the principal planes with zero shear.',
    iconName: 'RotateCcw',
    theory: {
      concept: 'Stress components change depending on the orientation angle of the coordinate plane. Principal stresses are the maximum and minimum normal stresses on planes where shear stress is zero.',
      governingTheory: 'Stress is a second-order tensor. The sum of normal stresses is invariant under rotation: \\sigma_x + \\sigma_y = \\sigma_1 + \\sigma_2 = \\text{constant}.',
      derivation: 'Equilibrium on a wedge element inclined at angle \\theta: \\sigma_{x\'} = \\frac{\\sigma_x+\\sigma_y}{2} + \\frac{\\sigma_x-\\sigma_y}{2}\\cos 2\\theta + \\tau_{xy}\\sin 2\\theta. Setting d\\sigma_{x\'}/d\\theta = 0$ gives $\\tan 2\\theta_p = \\frac{2\\tau_{xy}}{\\sigma_x - \\sigma_y}.',
      assumptions: [
        'Plane stress condition (\\sigma_z = \\tau_{xz} = \\tau_{yz} = 0)',
        'Infinitesimal element static equilibrium',
      ],
      practicalApplications: [
        'Pressure vessel helical weld seam stress calculations',
        'Brittle material fracture angle prediction (concrete/cast iron cracks perpendicular to \\sigma_1)',
      ],
      commonMistakes: [
        'Forgetting that principal planes are oriented at 90° to each other in physical space, corresponding to 180° on Mohr’s circle',
      ],
    },
  },
  {
    id: 'mohrs_circle',
    title: 'Mohr’s Circle for Plane Stress',
    category: 'Stress Transformation',
    subtitle: 'Graphical Plane Stress Transformation & State Analysis',
    governingFormula: '\\left(\\sigma - \\sigma_{\\text{avg}}\\right)^2 + \\tau^2 = R^2',
    standardRef: 'Otto Mohr (1882) / Hibbeler Ch. 9 / Beer & Johnston Ch. 7',
    keyConcepts: ['Mohr Circle Center & Radius', 'Pole Point Method', 'Synchronized Rotation (2θ vs θ)', 'Principal Coordinates', 'Pure Shear State'],
    description: 'Interact with an engineering-grade Mohr’s Circle. Drag state markers around the circle and observe the exact real-time synchronized rotation of the physical square stress element.',
    iconName: 'Circle',
    theory: {
      concept: 'Mohr’s Circle is a graphical representation of the 2D plane stress transformation equations, where the horizontal axis represents normal stress \\sigma and the vertical axis represents shear stress \\tau.',
      governingTheory: 'Every point on the circle corresponds to the stress state on an inclined plane. Center C = ((\\sigma_x + \\sigma_y)/2, 0) and Radius R = \\sqrt{[(\\sigma_x - \\sigma_y)/2]^2 + \\tau_{xy}^2}. Physical element rotation \\theta maps to 2\\theta on Mohr’s circle.',
      derivation: 'Squaring and adding transformation equations: (\\sigma_{x\'} - \\sigma_{\\text{avg}})^2 + \\tau_{x\'y\'}^2 = [(\\sigma_x - \\sigma_y)/2]^2 + \\tau_{xy}^2 = R^2, which is the standard equation of a circle (x - h)^2 + y^2 = R^2.',
      assumptions: [
        '2D plane stress state',
        'Sign convention: Tension positive (+), clockwise shear on right vertical face positive or standard Cartesian',
      ],
      practicalApplications: [
        'Strain rosette rosette transformation to compute principal strains in aerospace fuselages',
        'Geotechnical Mohr-Coulomb soil failure analysis',
      ],
      commonMistakes: [
        'Rotating by \\theta on Mohr’s circle instead of 2\\theta',
        'Misplotting shear stress sign conventions on vertical axes',
      ],
    },
  },
  {
    id: 'columns_buckling',
    title: 'Column Stability & Euler Buckling',
    category: 'Stability & Failure',
    subtitle: 'Critical Buckling Load of Compression Members',
    governingFormula: 'P_{cr} = \\frac{\\pi^2 E I}{(K L)^2} = \\frac{\\pi^2 E A}{\\lambda^2}',
    standardRef: 'AISC 360-16 Chapter E / Eurocode 3 / Euler (1744)',
    keyConcepts: ['Euler Critical Load P_cr', 'Effective Length Factor K', 'Slenderness Ratio λ = KL/r', 'Critical Buckling Stress σ_cr', 'Bifurcation of Equilibrium'],
    description: 'Compress slender columns under Pin-Pin, Fixed-Fixed, Fixed-Free, and Fixed-Pin conditions. Watch the structure remain straight until the bifurcation point, where it buckles dynamically.',
    iconName: 'Minimize2',
    theory: {
      concept: 'Buckling is a sudden geometric instability mode of failure where a slender column under compressive load fails by lateral bowing rather than material yielding or crushing.',
      governingTheory: 'Euler’s formula determines the bifurcation load where adjacent bent equilibrium states become possible. The effective length factor K accounts for end fixity: Pin-Pin (K=1.0), Fixed-Fixed (K=0.5), Fixed-Free (K=2.0), Fixed-Pin (K=0.7).',
      derivation: 'Differential equation for pin-ended column: EI \\frac{d^2v}{dx^2} = -P v \\implies \\frac{d^2v}{dx^2} + \\omega^2 v = 0 \\text{ where } \\omega^2 = P/EI. General solution v(x) = A \\sin(\\omega x) + B \\cos(\\omega x). Boundary condition v(0)=0 \\implies B=0; v(L)=0 \\implies A \\sin(\\omega L) = 0 \\implies \\omega L = \\pi \\implies P_{cr} = \\frac{\\pi^2 EI}{L^2}.',
      assumptions: [
        'Ideal column: perfectly straight with purely concentric axial load applied through centroid',
        'Slenderness ratio \\lambda \\ge \\lambda_c (elastic buckling regime where \\sigma_{cr} \\le \\sigma_{y})',
      ],
      practicalApplications: [
        'Structural building column and bridge pier design',
        'Hydraulic cylinder piston rods and automotive pushrods',
        'Aircraft fuselage stringers and rocket booster casings',
      ],
      commonMistakes: [
        'Using major axis inertia Ix instead of weak-axis inertia Iy (columns always buckle about the axis of least resistance)',
        'Applying Euler’s formula to short stocky columns where material yielding governs before elastic instability',
      ],
    },
  },
  {
    id: 'combined_loading',
    title: 'Combined Stresses & Superposition',
    category: 'Stability & Failure',
    subtitle: 'Superposition of Axial, Bending, Shear & Torsional Stresses',
    governingFormula: '\\sigma = \\frac{P}{A} \\pm \\frac{M y}{I}, \\quad \\tau = \\frac{T r}{J} + \\frac{V Q}{I b}',
    standardRef: 'ASME Boiler & Pressure Vessel Code / Hibbeler Ch. 8',
    keyConcepts: ['Principle of Superposition', 'Critical Point Selection', 'Equivalent Stress', 'Combined Normal & Shear', '3D Stress State'],
    description: 'Subject a structural shaft/beam to simultaneous axial load, transverse bending, and torque. Compute resultant normal and shear stresses at critical surface points.',
    iconName: 'Grid',
    theory: {
      concept: 'Real structural members frequently experience simultaneous axial thrust, bending moments, transverse shear, and torsional twisting.',
      governingTheory: 'The Principle of Superposition allows linear combinations of individual stresses at specific critical locations to establish the total multi-axial stress tensor.',
      derivation: 'Normal stresses add algebraically: \\sigma_{\\text{total}} = \\sigma_{\\text{axial}} + \\sigma_{\\text{bending}} = \\frac{P}{A} \\pm \\frac{M y}{I}. Shear stresses add vectorially: \\tau_{\\text{total}} = \\tau_{\\text{torsion}} + \\tau_{\\text{shear}} = \\frac{T r}{J} + \\frac{V Q}{I b}.',
      assumptions: [
        'Linear elastic behavior within Hooke’s law',
        'Small deformations such that loading geometry does not alter member configuration significantly',
      ],
      practicalApplications: [
        'Rotating turbine drive shafts carrying heavy bevel gear loads',
        'Offshore drilling platform tubular members under wave and topside gravity loads',
      ],
      commonMistakes: [
        'Adding normal stress \\sigma directly to shear stress \\tau (they must be transformed into principal stresses or von Mises equivalent stress)',
      ],
    },
  },
  {
    id: 'failure_safety',
    title: 'Yield Theories & Safety Factors',
    category: 'Stability & Failure',
    subtitle: 'Tresca, von Mises & Rankine Failure Criteria',
    governingFormula: '\\sigma_{vM} = \\sqrt{\\sigma_1^2 - \\sigma_1\\sigma_2 + \\sigma_2^2} \\le \\frac{\\sigma_y}{SF}',
    standardRef: 'von Mises (1913) / Tresca (1864) / Shigley Ch. 5',
    keyConcepts: ['von Mises (Distortion Energy)', 'Tresca (Max Shear Stress)', 'Rankine (Max Normal Stress)', 'Utilization Ratio', 'Safety Factor SF'],
    description: 'Evaluate structural safety using classic failure theories. Plot the 2D yield locus ellipse and hexagon, tracking whether your stress state is Safe, Yielding, or in Rupture.',
    iconName: 'ShieldAlert',
    theory: {
      concept: 'Yield criteria predict the onset of permanent plastic deformation or brittle fracture in multiaxial stress states based on uniaxial tensile test data.',
      governingTheory: 'von Mises (Distortion Energy Theory) accurately predicts yielding in ductile metals when shear distortion energy exceeds that at tensile yield. Tresca (Maximum Shear Stress Theory) provides a conservative hexagonal boundary.',
      derivation: 'Distortion energy density u_d = \\frac{1+\\nu}{3E} [(\\sigma_1 - \\sigma_2)^2 + (\\sigma_2 - \\sigma_3)^2 + (\\sigma_3 - \\sigma_1)^2]. Equating to uniaxial yield \\sigma_y gives the von Mises equivalent stress \\sigma_{vM} = \\sqrt{\\frac{1}{2}[(\\sigma_1-\\sigma_2)^2 + (\\sigma_2-\\sigma_3)^2 + (\\sigma_3-\\sigma_1)^2]}.',
      assumptions: [
        'Isotropic ductile material response for von Mises and Tresca',
        'Brittle material behavior for Maximum Normal Stress (Rankine) theory',
      ],
      practicalApplications: [
        'Pressure vessel shell thickness safety verification',
        'Automotive chassis and aerospace bulkhead structural sizing',
      ],
      commonMistakes: [
        'Using Maximum Normal Stress theory for ductile structural steel instead of von Mises',
        'Confusing Safety Factor (SF = capacity / demand) with Utilization Ratio (UR = demand / capacity = 1/SF)',
      ],
    },
  },
  {
    id: 'what_if_lab',
    title: 'What-If? Scenario Engine',
    category: 'Special Labs',
    subtitle: 'Dynamic Proportionality & Sensitivity Exploration',
    governingFormula: '\\Delta Y = f(\\Delta X_1, \\Delta X_2, ...)',
    standardRef: 'Engineering Design Sensitivity / EVLab Core',
    keyConcepts: ['Sensitivity Analysis', 'Non-linear Scaling (d³ & d⁴)', 'Material Tradeoffs', 'Optimization', 'Weight vs Strength'],
    description: 'Explore rapid engineering "What If?" scenarios: "What if beam depth doubles?", "What if steel is replaced with titanium?", "What if column length is cut in half?" with instant impact diagnostics.',
    iconName: 'HelpCircle',
    theory: {
      concept: 'Sensitivity analysis examines how variations in geometric dimensions or material properties propagate non-linearly to govern stresses, deflections, and weights.',
      governingTheory: 'Geometric power laws: Moment of Inertia scales cubically with depth (I \\propto h^3) and to the fourth power with diameter (I \\propto d^4), creating exponential sensitivity.',
      derivation: 'Logarithmic sensitivity derivative: \\frac{\\partial(\\ln \\delta)}{\\partial(\\ln L)} = 3 for point load (\\delta \\propto L^3) and 4 for distributed load (\\delta \\propto L^4).',
      assumptions: [
        'All comparative designs follow standard engineering code assumptions',
      ],
      practicalApplications: [
        'Weight-reduction optimization in racecars and spacecraft structures',
        'Value engineering and cost reduction studies in commercial building frames',
      ],
      commonMistakes: [
        'Assuming linear scaling for structural deflections and buckling capacities',
      ],
    },
  },
  {
    id: 'comparison_lab',
    title: 'Case A vs Case B Comparison',
    category: 'Special Labs',
    subtitle: 'Side-by-Side Multi-Case Performance Benchmarking',
    governingFormula: '\\Delta \\% = \\frac{B - A}{A} \\times 100\\%',
    standardRef: 'Comparative Structural Benchmarking / EVLab Core',
    keyConcepts: ['Case Comparison', 'Design Alternatives', 'Efficiency Ratio', 'Weight Comparison', 'Safety Margin Delta'],
    description: 'Compare two engineering designs side-by-side. Benchmark stress, deformation, mass, safety factor, and structural efficiency with synchronized visual feedback.',
    iconName: 'Columns',
    theory: {
      concept: 'Benchmarking design alternatives A vs B allows engineers to quantify structural efficiency gains, weight reductions, and safety margin improvements.',
      governingTheory: 'Specific strength and specific stiffness (performance per unit weight) determine optimal material and section choices.',
      derivation: 'Efficiency index \\eta = \\frac{M_{\\text{capacity}}}{\\text{Weight}} = \\frac{\\sigma_y Z}{\\rho A L}.',
      assumptions: [
        'Equal boundary conditions and external loads applied to both alternatives',
      ],
      practicalApplications: [
        'Trade studies between structural steel vs extruded aluminum in crane booms',
        'Solid vs hollow tube cross-section optimization for racecar roll cages',
      ],
      commonMistakes: [
        'Comparing maximum stress without checking elastic deflection limits',
      ],
    },
  },
  {
    id: 'educational_lab',
    title: 'Guided Virtual Experiment Lab',
    category: 'Special Labs',
    subtitle: 'Step-by-Step Interactive Experiments & Concept Quizzes',
    governingFormula: '\\text{Learn} \\rightarrow \\text{Predict} \\rightarrow \\text{Experiment} \\rightarrow \\text{Verify}',
    standardRef: 'ABET EAC Criteria / EVLab Guided Curriculum',
    keyConcepts: ['Structured Scientific Method', 'Tensile Test Experiment', 'Flexural Test Experiment', 'Euler Column Test', 'Concept Verification'],
    description: 'Follow guided laboratory protocols with step-by-step procedures, observation recording, interactive data logging, and conceptual mastery checks.',
    iconName: 'BookOpen',
    theory: {
      concept: 'Guided virtual laboratory protocols simulate real mechanical testing laboratory experiments with step-by-step procedures and concept mastery quizzes.',
      governingTheory: 'The experiential learning cycle: Learn theoretical governing equations -> Formulate predictive hypothesis -> Conduct interactive virtual experiment -> Verify results against analytical formulas.',
      derivation: 'Analytical vs experimental correlation: \\text{Error \\%} = \\left|\\frac{\\text{Theoretical} - \\text{Observed}}{\\text{Theoretical}}\\right| \\times 100\\%.',
      assumptions: [
        'Standard testing protocols according to ASTM, ISO, and AISC standards',
      ],
      practicalApplications: [
        'University engineering mechanics curriculum laboratory instruction',
        'Professional engineer continuing education and certification review',
      ],
      commonMistakes: [
        'Skipping pre-test calibration and boundary condition verification',
      ],
    },
  },
];

export function getTopicById(id: TopicId): TopicData {
  const found = TOPICS_DATA.find(t => t.id === id);
  return found || TOPICS_DATA[0];
}
