import React, { useState, useEffect } from 'react';
import { BookMarked, Plus, Trash2, Download, Check, FileText, Sparkles, Clock, Calculator } from 'lucide-react';
import { NotebookEntry, EducationLevel, ExperimentMetadata, CalculationItem } from '../../types/physics';
import { formatValue } from '../../utils/physicsMath';

interface ExperimentNotebookProps {
  currentExperiment: ExperimentMetadata;
  educationLevel: EducationLevel;
  currentParams: Record<string, number>;
  currentObservables: Record<string, any>;
  calculatedValues: Record<string, CalculationItem>;
}

export const ExperimentNotebook: React.FC<ExperimentNotebookProps> = ({
  currentExperiment,
  educationLevel,
  currentParams,
  currentObservables,
  calculatedValues,
}) => {
  const [entries, setEntries] = useState<NotebookEntry[]>(() => {
    try {
      const saved = localStorage.getItem('physlab_notebook_entries');
      return saved ? JSON.parse(saved) : [];
    } catch {
      return [];
    }
  });

  const [studentNotes, setStudentNotes] = useState('');
  const [conclusion, setConclusion] = useState('');
  const [activeEntryId, setActiveEntryId] = useState<string | null>(null);

  // Save entries to localStorage
  useEffect(() => {
    try {
      localStorage.setItem('physlab_notebook_entries', JSON.stringify(entries));
    } catch (e) {
      console.warn('Failed to save to localStorage', e);
    }
  }, [entries]);

  const handleRecordTrial = () => {
    const newEntry: NotebookEntry = {
      id: `entry-${Date.now()}`,
      experimentId: currentExperiment.id,
      experimentTitle: currentExperiment.title,
      timestamp: new Date().toLocaleString(),
      educationLevel: educationLevel,
      parameters: { ...currentParams },
      observations: { ...currentObservables },
      calculatedValues: Object.fromEntries(
        Object.entries(calculatedValues).map(([k, v]) => [k, (v as CalculationItem).value])
      ),
      studentNotes: studentNotes || 'Logged experimental run.',
      conclusion: conclusion || 'Observations consistent with governing physics principles.',
    };

    setEntries([newEntry, ...entries]);
    setActiveEntryId(newEntry.id);
    setStudentNotes('');
    setConclusion('');
  };

  const handleDeleteEntry = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setEntries(entries.filter((en) => en.id !== id));
    if (activeEntryId === id) setActiveEntryId(null);
  };

  const handleExportReport = () => {
    const reportText = `
# PHYSICAL VIRTUAL LABORATORY EXPERIMENTAL REPORT
**Experiment**: ${currentExperiment.title}
**Date Generated**: ${new Date().toLocaleString()}
**Education Depth**: ${educationLevel.toUpperCase()}
**Governing Laws**: ${currentExperiment.theory.physicalLaws.join('; ')}

---

## LOGGED EXPERIMENTAL RUNS (${entries.length} Trials Recorded)
${entries
  .map(
    (e, idx) => `
### Trial #${idx + 1} - ${e.timestamp}
- **Input Parameters**: ${JSON.stringify(e.parameters, null, 2)}
- **Measured Observations**: ${JSON.stringify(e.observations, null, 2)}
- **Theoretical Calculations**: ${JSON.stringify(e.calculatedValues, null, 2)}
- **Student Notes**: ${e.studentNotes}
- **Conclusion**: ${e.conclusion}
`
  )
  .join('\n\n')}

---
*Generated by Interactive Physics Virtual Laboratory*
    `.trim();

    const blob = new Blob([reportText], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Lab_Report_${currentExperiment.id}_${Date.now()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const activeEntry = entries.find((e) => e.id === activeEntryId) || entries[0];

  return (
    <div
      id="experiment-notebook"
      className="bg-[#080808] border border-white/10 rounded-xl p-4 shadow-xl flex flex-col h-full overflow-hidden"
    >
      {/* Header - Elegant Dark */}
      <div className="flex items-center justify-between border-b border-white/10 pb-3 mb-3">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded bg-cyan-600/20 border border-cyan-500/40 flex items-center justify-center text-cyan-400 font-bold">
            <BookMarked className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-xs font-bold text-white uppercase tracking-wider font-mono">
              Laboratory Notebook & Data Logger
            </h3>
            <p className="text-[10px] text-white/40 font-mono">
              Quantitative Experimental Runs & Data Logs
            </p>
          </div>
        </div>

        <button
          onClick={handleExportReport}
          disabled={entries.length === 0}
          className={`flex items-center gap-1.5 px-3 py-1 text-xs font-mono uppercase tracking-wider rounded transition-colors ${
            entries.length > 0
              ? 'bg-cyan-600 hover:bg-cyan-500 text-black font-bold'
              : 'bg-white/5 text-white/20 border border-white/5 cursor-not-allowed'
          }`}
        >
          <Download className="w-3.5 h-3.5" /> Export Markdown Report
        </button>
      </div>

      {/* Main Split Body: Left Form to Record Trial, Right Table/List */}
      <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 gap-3 overflow-hidden">
        {/* Left Column: Live Record Capture Form (5 Cols) */}
        <div className="lg:col-span-5 bg-[#050505] border border-white/10 rounded-lg p-4 flex flex-col justify-between overflow-y-auto space-y-3">
          <div>
            <div className="flex items-center justify-between mb-2">
              <span className="text-[10px] font-mono text-cyan-500 uppercase tracking-widest font-bold">
                Live State Snapshot
              </span>
              <span className="text-[10px] font-mono text-white/40">Ready to Log</span>
            </div>

            {/* Current Values Preview */}
            <div className="p-3 bg-[#0A0A0A] border border-white/10 rounded-lg text-xs space-y-2 mb-3">
              <div className="text-[10px] font-bold text-white/50 uppercase font-mono">
                Current Environmental Parameters:
              </div>
              <div className="flex flex-wrap gap-1">
                {Object.entries(currentParams).map(([k, v]) => (
                  <span key={k} className="text-[10px] font-mono bg-[#050505] border border-white/10 px-2 py-0.5 rounded text-white/70">
                    {k}: <strong className="text-cyan-400">{formatValue(Number(v), 2)}</strong>
                  </span>
                ))}
              </div>

              <div className="text-[10px] font-bold text-white/50 uppercase font-mono pt-1">
                Live Measured Observables:
              </div>
              <div className="flex flex-wrap gap-1">
                {Object.entries(currentObservables).map(([k, v]) => (
                  <span key={k} className="text-[10px] font-mono bg-[#050505] border border-white/10 px-2 py-0.5 rounded text-white/70">
                    {k}: <strong className="text-orange-400">{typeof v === 'number' ? formatValue(v, 2) : String(v)}</strong>
                  </span>
                ))}
              </div>
            </div>

            {/* Qualitative Notes Input */}
            <div className="space-y-2">
              <div>
                <label className="text-[10px] font-mono uppercase text-white/60 block mb-1">
                  Empirical Observations & Physical Notes:
                </label>
                <textarea
                  value={studentNotes}
                  onChange={(e) => setStudentNotes(e.target.value)}
                  placeholder="Record what was physically observed during this trial..."
                  rows={2}
                  className="w-full bg-[#0A0A0A] border border-white/10 rounded p-2 text-xs text-white placeholder:text-white/20 focus:outline-none focus:border-cyan-500 font-mono"
                />
              </div>

              <div>
                <label className="text-[10px] font-mono uppercase text-white/60 block mb-1">
                  Scientific Deduction / Conclusion:
                </label>
                <textarea
                  value={conclusion}
                  onChange={(e) => setConclusion(e.target.value)}
                  placeholder="Does this confirm the theoretical physical law? Why?"
                  rows={2}
                  className="w-full bg-[#0A0A0A] border border-white/10 rounded p-2 text-xs text-white placeholder:text-white/20 focus:outline-none focus:border-cyan-500 font-mono"
                />
              </div>
            </div>
          </div>

          <button
            onClick={handleRecordTrial}
            className="w-full py-2.5 bg-cyan-600 hover:bg-cyan-500 text-black font-bold uppercase text-xs tracking-widest rounded flex items-center justify-center gap-2 transition-colors font-mono"
          >
            <Plus className="w-4 h-4" /> Save Trial to Notebook
          </button>
        </div>

        {/* Right Column: Recorded Trials List & Inspector (7 Cols) */}
        <div className="lg:col-span-7 bg-[#050505] border border-white/10 rounded-lg p-4 flex flex-col overflow-hidden">
          <div className="flex items-center justify-between pb-2 mb-2 border-b border-white/10">
            <span className="text-[10px] font-mono uppercase font-bold text-white/70">
              Recorded Trials ({entries.length})
            </span>
            <span className="text-[10px] text-white/40 font-mono">Persisted Locally</span>
          </div>

          {entries.length === 0 ? (
            <div className="flex-1 flex flex-col items-center justify-center text-white/30 text-xs font-mono space-y-2">
              <FileText className="w-8 h-8 stroke-1 text-white/20" />
              <span>NO EXPERIMENTAL TRIALS LOGGED YET</span>
            </div>
          ) : (
            <div className="flex-1 space-y-2 overflow-y-auto pr-1">
              {entries.map((entry, index) => (
                <div
                  key={entry.id}
                  onClick={() => setActiveEntryId(entry.id)}
                  className={`p-3 rounded-lg border transition-all cursor-pointer ${
                    activeEntry?.id === entry.id
                      ? 'bg-[#0A0A0A] border-cyan-500/60 shadow-lg shadow-cyan-500/10'
                      : 'bg-[#050505] border-white/10 hover:border-white/20'
                  }`}
                >
                  <div className="flex items-center justify-between mb-1.5">
                    <span className="text-xs font-bold text-white font-mono uppercase">
                      Trial #{entries.length - index}: {entry.experimentTitle}
                    </span>
                    <div className="flex items-center gap-2">
                      <span className="text-[10px] text-white/40 font-mono">{entry.timestamp}</span>
                      <button
                        onClick={(e) => handleDeleteEntry(entry.id, e)}
                        className="text-white/30 hover:text-rose-400 transition-colors p-1"
                        title="Delete Trial"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-2 text-[10px] font-mono bg-[#050505] p-2 rounded border border-white/5 mb-1.5">
                    <div>
                      <span className="text-white/40">PARAMS: </span>
                      <span className="text-cyan-400">
                        {Object.entries(entry.parameters)
                          .map(([k, v]) => `${k}=${formatValue(Number(v), 1)}`)
                          .join(', ')}
                      </span>
                    </div>
                    <div>
                      <span className="text-white/40">OBSERVED: </span>
                      <span className="text-orange-400">
                        {Object.entries(entry.observations)
                          .map(([k, v]) => `${k}=${typeof v === 'number' ? formatValue(v, 1) : v}`)
                          .join(', ')}
                      </span>
                    </div>
                  </div>

                  <p className="text-xs text-white/70 italic">"{entry.studentNotes}"</p>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
