import React, { useState, useMemo, useEffect } from 'react';
import {
  Compass,
  BookOpen,
  FlaskConical,
  LineChart,
  Brain,
  BookMarked,
  GraduationCap,
  Layers,
  Search,
  Filter,
  Sparkles,
  ArrowRight,
  ChevronRight,
  RefreshCw,
  HelpCircle,
  Columns,
  CheckCircle2,
  Atom,
  Activity,
  Globe,
  Droplets,
  Waves,
  Flame,
  Zap,
  Eye,
  Sliders,
} from 'lucide-react';
import 'katex/dist/katex.min.css';
import { EXPERIMENTS_REGISTRY, DOMAIN_INFO } from './data/experiments';
import { EducationLevel, ExperimentMetadata, PhysicsDomain, CalculationItem } from './types/physics';
import { SimulationWorkspace } from './components/laboratory/SimulationWorkspace';
import { InteractiveGraph } from './components/laboratory/InteractiveGraph';
import { LiveCalculationPanel } from './components/laboratory/LiveCalculationPanel';
import { WhyDidThisHappenEngine } from './components/laboratory/WhyDidThisHappenEngine';
import { PredictionMode } from './components/laboratory/PredictionMode';
import { WhatIfExplorer } from './components/laboratory/WhatIfExplorer';
import { ComparisonMode } from './components/laboratory/ComparisonMode';
import { ExperimentNotebook } from './components/laboratory/ExperimentNotebook';
import { renderLatex, formatValue } from './utils/physicsMath';

type ActiveTab = 'discover' | 'learn' | 'experiment' | 'analyze' | 'understand' | 'notebook';

export function PhysicsLab() {
  // Navigation & Active States
  const [activeTab, setActiveTab] = useState<ActiveTab>('experiment');
  const [selectedExperimentId, setSelectedExperimentId] = useState<string>('newtons-second-law');
  const [educationLevel, setEducationLevel] = useState<EducationLevel>('college');
  const [selectedDomain, setSelectedDomain] = useState<PhysicsDomain | 'all'>('all');
  const [searchQuery, setSearchQuery] = useState('');

  // Active Experiment Object
  const currentExperiment = useMemo(() => {
    return (
      EXPERIMENTS_REGISTRY.find((e) => e.id === selectedExperimentId) ||
      EXPERIMENTS_REGISTRY[0]
    );
  }, [selectedExperimentId]);

  // Parameters State for current experiment
  const [params, setParams] = useState<Record<string, number>>(() => {
    const initial: Record<string, number> = {};
    currentExperiment.parameters.forEach((p) => {
      initial[p.id] = p.defaultValue;
    });
    return initial;
  });

  // Reset params when switching experiment
  useEffect(() => {
    const initial: Record<string, number> = {};
    currentExperiment.parameters.forEach((p) => {
      initial[p.id] = p.defaultValue;
    });
    setParams(initial);
    setHistoricalData([]);
  }, [currentExperiment.id]);

  const handleParamChange = (paramId: string, value: number) => {
    setParams((prev) => ({ ...prev, [paramId]: value }));
  };

  // Live Observables generated by Simulation Engine
  const [observables, setObservables] = useState<Record<string, any>>({});

  // Historical data points for Interactive Graphs
  const [historicalData, setHistoricalData] = useState<Record<string, any>[]>([]);

  const handleObservablesUpdate = (newObs: Record<string, any>) => {
    setObservables(newObs);
    setHistoricalData((prev) => {
      const merged = { ...params, ...newObs };
      const nextArr = [...prev, merged];
      return nextArr.length > 200 ? nextArr.slice(nextArr.length - 200) : nextArr;
    });
  };

  // Synchronized Derivations Calculation Engine
  const calculatedValues = useMemo(() => {
    switch (currentExperiment.id) {
      case 'newtons-second-law': {
        const m = params.mass ?? 5;
        const F = params.appliedForce ?? 25;
        const mu = params.frictionCoeff ?? 0.2;
        const g = params.gravity ?? 9.81;
        const N = m * g;
        const fk = mu * N;
        const Fnet = Math.max(0, F - fk);
        const a = Fnet / m;
        return {
          acceleration: {
            value: a,
            unit: 'm/s²',
            formula: 'a = \\frac{F_{net}}{m} = \\frac{F_{app} - f_k}{m}',
            substitution: `a = \\frac{${formatValue(F)} - ${formatValue(fk)}}{${formatValue(m)}} = ${formatValue(a)} \\text{ m/s}^2`,
            interpretation: `A net driving force of ${formatValue(Fnet)} N produces an acceleration of ${formatValue(a)} m/s² on a ${formatValue(m)} kg mass.`,
          },
          frictionForce: {
            value: fk,
            unit: 'N',
            formula: 'f_k = \\mu_k N = \\mu_k m g',
            substitution: `f_k = ${formatValue(mu)} \\times ${formatValue(m)} \\times ${formatValue(g)} = ${formatValue(fk)} \\text{ N}`,
            interpretation: `Normal reaction contact force produces opposing kinetic friction of ${formatValue(fk)} N.`,
          },
        };
      }
      case 'projectile-motion': {
        const v0 = params.launchSpeed ?? 30;
        const thetaDeg = params.launchAngle ?? 45;
        const thetaRad = (thetaDeg * Math.PI) / 180;
        const g = params.gravity ?? 9.81;
        const maxH = (v0 * Math.sin(thetaRad)) ** 2 / (2 * g);
        const totalR = (v0 ** 2 * Math.sin(2 * thetaRad)) / g;
        const tFlight = (2 * v0 * Math.sin(thetaRad)) / g;
        return {
          maximumHeight: {
            value: maxH,
            unit: 'm',
            formula: 'H_{max} = \\frac{(v_0 \\sin\\theta)^2}{2g}',
            substitution: `H_{max} = \\frac{(${formatValue(v0)} \\sin(${thetaDeg}^\\circ))^2}{2(${formatValue(g)})} = ${formatValue(maxH)} \\text{ m}`,
            interpretation: `Vertical velocity reaches zero at apex height of ${formatValue(maxH)} m.`,
          },
          totalRange: {
            value: totalR,
            unit: 'm',
            formula: 'R = \\frac{v_0^2 \\sin(2\\theta)}{g}',
            substitution: `R = \\frac{${formatValue(v0)}^2 \\sin(2 \\times ${thetaDeg}^\\circ)}{${formatValue(g)}} = ${formatValue(totalR)} \\text{ m}`,
            interpretation: `Horizontal flight distance covered over ${formatValue(tFlight)} seconds of flight time.`,
          },
        };
      }
      case 'simple-pendulum': {
        const L = params.length ?? 1.5;
        const g = params.gravity ?? 9.81;
        const T = 2 * Math.PI * Math.sqrt(L / g);
        const f = 1 / T;
        return {
          oscillationPeriod: {
            value: T,
            unit: 's',
            formula: 'T = 2\\pi \\sqrt{\\frac{L}{g}}',
            substitution: `T = 2\\pi \\sqrt{\\frac{${formatValue(L)}}{${formatValue(g)}}} = ${formatValue(T)} \\text{ s}`,
            interpretation: `Each full pendulum swing cycle takes exactly ${formatValue(T)} seconds. Mass has zero effect.`,
          },
          naturalFrequency: {
            value: f,
            unit: 'Hz',
            formula: 'f = \\frac{1}{T} = \\frac{1}{2\\pi} \\sqrt{\\frac{g}{L}}',
            substitution: `f = \\frac{1}{${formatValue(T)}} = ${formatValue(f)} \\text{ Hz}`,
            interpretation: `Completes ${formatValue(f)} full oscillations per second.`,
          },
        };
      }
      default: {
        return {
          primaryObservable: {
            value: observables.velocity || observables.current || observables.pressure || 0,
            unit: 'SI',
            formula: currentExperiment.theory.governingEquations[0]?.formulaLatex || 'y = f(x)',
            substitution: 'Simulated under active environmental parameters.',
            interpretation: 'Governed by fundamental physical conservation principles.',
          },
        };
      }
    }
  }, [currentExperiment.id, params, observables]) as unknown as Record<string, CalculationItem>;

  // Filtered experiments for Discover View
  const filteredExperiments = useMemo(() => {
    return EXPERIMENTS_REGISTRY.filter((exp) => {
      const matchDomain = selectedDomain === 'all' || exp.domain === selectedDomain;
      const matchSearch =
        searchQuery === '' ||
        exp.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        exp.concept.toLowerCase().includes(searchQuery.toLowerCase());
      return matchDomain && matchSearch;
    });
  }, [selectedDomain, searchQuery]);

  return (
    <div className="flex flex-col h-screen w-screen bg-[#050505] text-[#E0E0E0] font-sans overflow-hidden select-none">
      {/* Top Main Navigation Header - Elegant Dark */}
      <header className="h-14 border-b border-white/10 flex items-center justify-between px-6 bg-[#0A0A0A] shrink-0 z-40">
        {/* Brand & Lab Title */}
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 bg-cyan-600 rounded flex items-center justify-center font-bold text-black shadow-lg shadow-cyan-600/20">
            Φ
          </div>
          <div>
            <h1 className="text-sm font-semibold tracking-tight uppercase text-white flex items-center gap-2">
              Interactive Physics <span className="text-cyan-500">Lab</span>
            </h1>
            <p className="text-[10px] text-white/40 font-mono tracking-wider">
              {currentExperiment.title.toUpperCase()}
            </p>
          </div>
        </div>

        {/* 5 Core Journey Steps & Views */}
        <nav className="flex items-center gap-6 text-xs font-medium uppercase tracking-widest text-white/50">
          <button
            onClick={() => setActiveTab('discover')}
            className={`pb-1 transition-colors ${
              activeTab === 'discover'
                ? 'text-cyan-400 border-b-2 border-cyan-400 font-bold'
                : 'hover:text-white'
            }`}
          >
            Discover
          </button>
          <button
            onClick={() => setActiveTab('learn')}
            className={`pb-1 transition-colors ${
              activeTab === 'learn'
                ? 'text-cyan-400 border-b-2 border-cyan-400 font-bold'
                : 'hover:text-white'
            }`}
          >
            Theory
          </button>
          <button
            onClick={() => setActiveTab('experiment')}
            className={`pb-1 transition-colors ${
              activeTab === 'experiment'
                ? 'text-cyan-400 border-b-2 border-cyan-400 font-bold'
                : 'hover:text-white'
            }`}
          >
            Experiment
          </button>
          <button
            onClick={() => setActiveTab('analyze')}
            className={`pb-1 transition-colors ${
              activeTab === 'analyze'
                ? 'text-cyan-400 border-b-2 border-cyan-400 font-bold'
                : 'hover:text-white'
            }`}
          >
            Analyze
          </button>
          <button
            onClick={() => setActiveTab('understand')}
            className={`pb-1 transition-colors ${
              activeTab === 'understand'
                ? 'text-cyan-400 border-b-2 border-cyan-400 font-bold'
                : 'hover:text-white'
            }`}
          >
            Understand
          </button>
          <button
            onClick={() => setActiveTab('notebook')}
            className={`pb-1 transition-colors ${
              activeTab === 'notebook'
                ? 'text-cyan-400 border-b-2 border-cyan-400 font-bold'
                : 'hover:text-white'
            }`}
          >
            Notebook
          </button>
        </nav>

        {/* Right Tools: Education Level & AI Assistant */}
        <div className="flex items-center gap-3">
          {/* Education Level Selector */}
          <div className="flex items-center gap-1.5 bg-white/5 px-2.5 py-1 border border-white/10 rounded uppercase text-[10px] font-mono">
            <span className="text-white/40">MODE:</span>
            <select
              value={educationLevel}
              onChange={(e) => setEducationLevel(e.target.value as EducationLevel)}
              className="bg-transparent text-[10px] font-bold text-cyan-400 focus:outline-none cursor-pointer uppercase"
            >
              <option value="school" className="bg-[#0A0A0A] text-[#E0E0E0]">
                School (Class 9-10)
              </option>
              <option value="college" className="bg-[#0A0A0A] text-[#E0E0E0]">
                College (Class 11-12)
              </option>
              <option value="university" className="bg-[#0A0A0A] text-[#E0E0E0]">
                University (BSc)
              </option>
              <option value="advanced" className="bg-[#0A0A0A] text-[#E0E0E0]">
                Advanced / Research
              </option>
            </select>
          </div>
        </div>
      </header>

      {/* Main Experience Layout */}
      <main className="flex-1 flex overflow-hidden p-3 gap-3 bg-[#050505]">
        {/* 1. DISCOVER VIEW */}
        {activeTab === 'discover' && (
          <div className="flex-1 flex flex-col bg-[#080808] border border-white/10 rounded-xl p-6 overflow-y-auto">
            <div className="flex flex-wrap items-center justify-between gap-4 mb-6">
              <div>
                <h2 className="text-lg font-semibold text-white uppercase tracking-wider flex items-center gap-2">
                  <Compass className="w-5 h-5 text-cyan-500" /> Physical Systems & Experiments
                  Catalog
                </h2>
                <p className="text-xs text-white/50 mt-1">
                  Select a textbook physics concept to build its physical situation and begin
                  empirical testing
                </p>
              </div>

              {/* Search Bar */}
              <div className="relative w-72">
                <Search className="w-4 h-4 text-white/40 absolute left-3 top-2.5" />
                <input
                  type="text"
                  placeholder="Search laws, formulas, phenomena..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full bg-[#050505] border border-white/10 rounded-lg pl-9 pr-3 py-2 text-xs text-white placeholder:text-white/30 focus:outline-none focus:border-cyan-500 font-mono"
                />
              </div>
            </div>

            {/* Physics Domains Filter Pills */}
            <div className="flex flex-wrap gap-2 mb-6">
              <button
                onClick={() => setSelectedDomain('all')}
                className={`px-3 py-1.5 rounded-lg text-xs font-mono uppercase tracking-wider transition-all ${
                  selectedDomain === 'all'
                    ? 'bg-cyan-600 text-black font-bold'
                    : 'bg-[#050505] text-white/50 border border-white/10 hover:text-white'
                }`}
              >
                All Domains ({EXPERIMENTS_REGISTRY.length})
              </button>
              {Object.entries(DOMAIN_INFO).map(([domKey, dom]) => (
                <button
                  key={domKey}
                  onClick={() => setSelectedDomain(domKey as PhysicsDomain)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-mono uppercase tracking-wider transition-all ${
                    selectedDomain === domKey
                      ? 'bg-cyan-600 text-black font-bold'
                      : 'bg-[#050505] text-white/50 border border-white/10 hover:text-white'
                  }`}
                >
                  {dom.name}
                </button>
              ))}
            </div>

            {/* Experiments Cards Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {filteredExperiments.map((exp) => (
                <div
                  key={exp.id}
                  onClick={() => {
                    setSelectedExperimentId(exp.id);
                    setActiveTab('experiment');
                  }}
                  className={`p-5 rounded-xl border transition-all cursor-pointer flex flex-col justify-between group ${
                    selectedExperimentId === exp.id
                      ? 'bg-[#0A0A0A] border-cyan-500/60 shadow-xl shadow-cyan-500/10'
                      : 'bg-[#050505] border-white/10 hover:border-white/20 hover:bg-[#0A0A0A]'
                  }`}
                >
                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-[10px] font-bold uppercase tracking-widest text-cyan-500">
                        {exp.domain.toUpperCase()}
                      </span>
                      <span className="text-[10px] text-white/40 font-mono uppercase">{exp.difficulty}</span>
                    </div>
                    <h3 className="text-sm font-bold text-white group-hover:text-cyan-400 transition-colors mb-1">
                      {exp.title}
                    </h3>
                    <p className="text-xs text-white/60 line-clamp-2 mb-3 leading-relaxed">{exp.concept}</p>
                  </div>

                  <div className="pt-3 border-t border-white/10 flex items-center justify-between text-xs text-cyan-400 font-mono uppercase">
                    <span>Enter Laboratory</span>
                    <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* 2. LEARN VIEW */}
        {activeTab === 'learn' && (
          <div className="flex-1 flex flex-col bg-[#080808] border border-white/10 rounded-xl p-6 overflow-y-auto space-y-6">
            <div className="border-b border-white/10 pb-4 flex items-center justify-between">
              <div>
                <span className="text-[10px] font-mono text-cyan-500 uppercase tracking-widest font-bold">
                  Theoretical Foundations & Mathematical Formulations
                </span>
                <h2 className="text-xl font-bold text-white uppercase tracking-tight mt-1">
                  {currentExperiment.title}
                </h2>
                <p className="text-xs text-white/50 mt-1">{currentExperiment.subtitle}</p>
              </div>
              <button
                onClick={() => setActiveTab('experiment')}
                className="flex items-center gap-1.5 px-6 py-2 bg-cyan-600 hover:bg-cyan-500 text-black font-bold uppercase text-xs tracking-widest rounded transition-colors"
              >
                Launch Virtual Lab <ArrowRight className="w-4 h-4" />
              </button>
            </div>

            {/* Core Overview */}
            <div className="bg-[#050505] border border-white/10 rounded-xl p-5 space-y-3">
              <h3 className="text-[10px] font-bold uppercase tracking-widest text-cyan-500 flex items-center gap-1.5">
                <BookOpen className="w-3.5 h-3.5" /> Phenomenon Overview & Physical Laws
              </h3>
              <p className="text-xs text-white/70 leading-relaxed">
                {currentExperiment.theory.overview}
              </p>
              <div className="pt-2 grid grid-cols-1 md:grid-cols-2 gap-2">
                {currentExperiment.theory.physicalLaws.map((law, idx) => (
                  <div
                    key={idx}
                    className="p-3 bg-[#0A0A0A] border border-white/10 rounded font-mono text-xs text-white"
                    dangerouslySetInnerHTML={{ __html: renderLatex(law) }}
                  />
                ))}
              </div>
            </div>

            {/* Governing Mathematical Formulations */}
            <div className="space-y-3">
              <h3 className="text-[10px] font-bold uppercase tracking-widest text-cyan-500">
                Governing Equations by Academic Depth
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                {currentExperiment.theory.governingEquations.map((eq, i) => (
                  <div
                    key={i}
                    className="bg-[#050505] border border-white/10 rounded-xl p-4 flex flex-col justify-between"
                  >
                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-[10px] font-mono uppercase bg-white/5 px-2 py-0.5 rounded text-cyan-400 border border-white/10">
                          {eq.level} Depth
                        </span>
                      </div>
                      <h4 className="text-xs font-bold text-white mb-2">{eq.name}</h4>
                      <div
                        className="p-3 bg-[#0A0A0A] border border-white/10 rounded text-center font-mono text-cyan-400 my-2 overflow-x-auto"
                        dangerouslySetInnerHTML={{ __html: renderLatex(eq.formulaLatex, true) }}
                      />
                      <p className="text-[11px] text-white/60 mt-2 leading-relaxed">{eq.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Real World Applications */}
            <div className="bg-[#050505] border border-white/10 rounded-xl p-5 space-y-3">
              <h3 className="text-[10px] font-bold uppercase tracking-widest text-cyan-500">
                Real-World Applications & Technological Manifestations
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-xs text-white/70">
                {currentExperiment.theory.realWorldApplications.map((app, i) => (
                  <div key={i} className="flex items-center gap-2 p-2.5 bg-[#0A0A0A] border border-white/5 rounded">
                    <CheckCircle2 className="w-3.5 h-3.5 text-cyan-400 shrink-0" />
                    <span>{app}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* 3. EXPERIMENT VIEW (Core Laboratory Canvas & Mathematical Synchronizer) */}
        {activeTab === 'experiment' && (
          <div className="flex-1 grid grid-cols-1 xl:grid-cols-12 gap-3 overflow-hidden">
            {/* Primary Simulation Workspace (8 Cols) */}
            <div className="xl:col-span-8 h-full flex flex-col">
              <SimulationWorkspace
                experiment={currentExperiment}
                educationLevel={educationLevel}
                params={params}
                onParamChange={handleParamChange}
                observables={observables}
                onObservablesUpdate={handleObservablesUpdate}
                calculatedValues={calculatedValues}
              />
            </div>

            {/* Live Mathematical Derivation & Synchronizer (4 Cols) */}
            <div className="xl:col-span-4 h-full flex flex-col space-y-3 overflow-hidden">
              <LiveCalculationPanel
                parameters={params}
                parameterDefs={currentExperiment.parameters}
                equations={currentExperiment.theory.governingEquations}
                educationLevel={educationLevel}
                calculatedValues={calculatedValues}
              />
            </div>
          </div>
        )}

        {/* 4. ANALYZE VIEW (Interactive Dynamic Graph & Dual Comparison) */}
        {activeTab === 'analyze' && (
          <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 gap-3 overflow-hidden">
            <div className="lg:col-span-7 h-full flex flex-col">
              <InteractiveGraph
                channels={currentExperiment.graphChannels}
                data={historicalData}
                title={`${currentExperiment.title} — Empirical Graph Channel`}
              />
            </div>
            <div className="lg:col-span-5 h-full flex flex-col">
              <ComparisonMode
                experiment={currentExperiment}
                currentParams={params}
                onApplyCaseParams={(caseName, p) => {
                  setParams(p);
                  setActiveTab('experiment');
                }}
              />
            </div>
          </div>
        )}

        {/* 5. UNDERSTAND VIEW ("Why Did This Happen?" + Prediction + What-If) */}
        {activeTab === 'understand' && (
          <div className="flex-1 grid grid-cols-1 lg:grid-cols-3 gap-3 overflow-hidden">
            {/* Why Did This Happen Engine */}
            <div className="h-full flex flex-col">
              <WhyDidThisHappenEngine
                experiment={currentExperiment}
                educationLevel={educationLevel}
                currentObservables={observables}
              />
            </div>

            {/* Hypothesis & Prediction Lab */}
            <div className="h-full flex flex-col">
              <PredictionMode
                quiz={currentExperiment.predictionQuiz}
                onApplyCondition={(p) => setParams((prev) => ({ ...prev, ...p }))}
                onRunSimulation={() => setActiveTab('experiment')}
                isSimulationRunning={false}
              />
            </div>

            {/* What-If Physical Scenarios */}
            <div className="h-full flex flex-col">
              <WhatIfExplorer
                experiment={currentExperiment}
                currentParams={params}
                onApplyParams={(p) => {
                  setParams((prev) => ({ ...prev, ...p }));
                  setActiveTab('experiment');
                }}
              />
            </div>
          </div>
        )}

        {/* 6. NOTEBOOK VIEW */}
        {activeTab === 'notebook' && (
          <div className="flex-1 h-full">
            <ExperimentNotebook
              currentExperiment={currentExperiment}
              educationLevel={educationLevel}
              currentParams={params}
              currentObservables={observables}
              calculatedValues={calculatedValues}
            />
          </div>
        )}
      </main>

      {/* Elegant Dark Footer Status Bar */}
      <footer className="h-8 bg-[#050505] border-t border-white/10 flex items-center px-6 justify-between text-[10px] text-white/40 font-mono shrink-0">
        <div className="flex items-center gap-4">
          <span>
            SYSTEM ID: <strong className="text-white/70">{currentExperiment.id.toUpperCase()}</strong>
          </span>
          <span className="text-white/20">•</span>
          <span>
            DOMAIN: <strong className="text-cyan-400">{currentExperiment.domain.toUpperCase()}</strong>
          </span>
          <span className="text-white/20">•</span>
          <span>
            MODE: <strong className="text-white/70">{educationLevel.toUpperCase()}</strong>
          </span>
        </div>
        <div className="flex items-center gap-4">
          <span>
            INTEGRATION: <strong className="text-cyan-400">RK4 / 60 FPS</strong>
          </span>
          <span className="text-white/20">•</span>
          <span>© INTERACTIVE PHYSICS VIRTUAL LAB</span>
        </div>
      </footer>
    </div>
  );
}

export default PhysicsLab;
